### ISSUE TITLE
DeviceTwin, Update desired properties from device side

### ISSUE THREAD

**Issue by Patrik-Berglund** [Azure/azure-iot-sdk-c#1060]
Hi,

We are using the IoT Hub C SDK in our product. Some configuration of the product are handled from the cloud side via desired properties in the device twin. 

The product has a UI (display and operating panel) and in the near future changing the same configuration parameters from both the product and cloud side will be needed. 

Any advice in how to handle this?

**Comment by mamokarz** [comment]
Hi @Patrik-Berglund,

There are many possible concurrency problems, and many different policies to handle it. For example, let’s image a thermostat, where the user can change the temperature using a phone APP, that uses Azure Device Twin, or on the device control panel. Image the current temperature is 30, and the user wants it on 33, the user goes to the APP and push the “UP” button once (to 31), but the thermostat is not connected at that point, and the user decides to go to the control panel and push the “UP” button 3 times there. The temperature goes to 33 as desired, but then, the thermostat reconnects and receive the new temperature as 31 from the Device Twin. So, at that point, the device shall decide if it should accept or not the new value.

To properly make this decision, the device shall understand that there was a concurrency problem and provide the means for the system to make the right decision about it. There are 3 well know categories of [concurrency controls]( https://blogs.msdn.microsoft.com/marcelolr/2010/07/16/optimistic-and-pessimistic-concurrency-a-simple-explanation/) between 2 actors:

1.	<b>Optimistic</b>: Both actors can execute changes at the same time and the system will only check the conflict when the data is pushed. 
2.	<b>Pessimistic</b>: Only one actor can change the content at a time, when the first actor request the data for change, the system will block the same request for the second actor.
3.	<b>Semi-optimistic</b>: An optimistic system when the actor can block the content if necessary.

Concurrency controls that can block the data is normally not a good solution on systems that have actors on the cloud. So, you probably need to implement an optimistic concurrency mechanism on your device. To do that, you should split the concurrency problem in 2 steps, (1) identify the conflict, (2) resolve the conflict. 

### Identifying the conflict ###

The way that you can identify the conflict on your data is adding an etag on it. The etag shall be a random value, and you may reserve one of them to be the “force”. The “set” function that will change the data should require the new value together with the current etag. It will only accept the new value if the etag matches the current etag or if it is the “force” value. Once the “set” accept the new value, it will generate a new etag and return it to the caller. 

The “set” shall follow this pseudo-code for a variable `my_val`, in this case, `-1` is the “force” (the most common “force” is `*`, if your etag is a string):
 ```
typedef struct ETAGGED_MY_VAL_TAG
{
    int value;
    int dtetag;
} ETAGGED_MY_VAL;

static ETAGGED_MY_VAL myVal = 
{ 
    .value = 0, 
    .dtetag = newDTetag() 
};

RESULT getMyVal(ETAGGED_MY_VAL* returnVal)
{
    returnVal->value = myVal.value;
    returnVal->dtetag = myVal.dtetag;
    return __SUCCESS__;
}

RESULT setMyVal(ETAGGED_MY_VAL newVal, int* returnDTetag) 
{
    if((newVal.dtetag == -1) or match(newVal.dtetag, myVal.dtetag))
    {
        myVal.value = newVal.value;
        myVal.dtetag = newDTetag();
        *returnDTetag = myVal.dtetag;
        reportUpdatedMyVal(myVal);
        return __SUCCESS__;
    }
    return __FAIL__;
}
```
Once you have it implemented, on the Device Twin, you should have the same property on both Desired and Reported properties, and both shall expose its own etag. The current value of the property in the device is the one on the Reported property, so <b>the Reported property is the real value</b>. The value in the Desired property is the latest one requested by the actors in the cloud, that can be different of the one in the Reported property (for example if another actor change it on the control panel).

To change a property, the actor in the cloud shall write the new value with the latest etag (from the Reported property) to the Desired property. And this actor will know that its value was accepted when the new value shows in the Reported property, with a new etag. The `reportUpdatedMyVal(myVal);` on the pseudo-code should do that.

### Resolving the conflict ###

Normally, the actor in the control panel does not care about concurrency, so, it may do all operations using “force” as the etag. 

On the other hand, actors in the cloud may have its value rejected by the etag (precondition failed), or overwritten by another actor, local or on the cloud. In this case, the service client APP shall handle it, depending on its business model. It can be the case where the APP will resend the value with the new etag, or it can be that the APP will show an alert to the user telling that its value was overwritten, or it can be any other conflict policy that you what to implement. 

But now, with the etag, the device knows that who is trying to change a property, knows its latest value before change it, and if the APP received a new etag on the Reported property, but the new value is not the one that the APP sent, is because the APP value was rejected.

**Comment by mamokarz** [comment]
Hi @Patrik-Berglund,

I hope the previous description has helped you in your project. I'll close this issue for now, but feel free to reopen it if you need any clarification on that.

Regards,
Marcos

**Comment by az-iot-builder-01** [comment]
@Patrik-Berglund, @mamokarz, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
