### ISSUE TITLE
IoT Client Disconnects after idle period 

### ISSUE THREAD

**Issue by baker1971** [Azure/azure-iot-sdk-c#107]
Azure C SDK for Linux client 1.0.8 running in OprenWRT 5.0 and Linux 3.0.35 kernel
[Azure_108_DISCONNECTED.txt](https://github.com/Azure/azure-iot-sdk-c/files/893733/Azure_108_DISCONNECTED.txt)

With your team's help, we integrated the Azure client to allow our customers to collect data from Modbus TCP/RTU and CANbus ports of industrial devices (e.g. power meters and solar controllers) to Azure platform. 

If the iot client keeps sending messages to Azure iothub, everything is fine but when the client is idle and not sending messages to iothub, the client randomly e.g. after 40 min, gets disconnected (see attached log) and never able to reconnect back unless we kill and restart the client program thread. 

Please assist.

**Comment by jtanner-msft** [comment]
Hello @amplifiedengr,

  Thank you for your request and providing the data log and all of the details on what versions you are using.

  In the log you will notice that even if your client is not sending any data for a while, a series of PINGREQ and PINGRESP messages happen about every 4 minutes.  However about every 40 to 48 minutes, a disconnect will happen which is initiated by the client.  This is because a new SAS token needs to be generated and then needs to be used to establish the connect to the IoT Hub for the next hours period.

  Beyond that regular sequence however, eventually you can see that we get an error when calling socketio_open:
Error: Time:Sat Apr  1 11:47:45 2017 File:/home/amplified/azure-iot-sdks/c/azure-c-shared-utility/adapters/socketio_berkeley.c Func:socketio_open Line:321 Failure: select failure.
Error: io_open failed

  Once this issue happens I believe is when you will no longer be able to re-establish a connection with the IoT Hub from the client until you restart the device.  This is likely due to either a low memory issue or some other problem related to having run out a similar resource on the device.

  I wanted to mention that the C client SDK you are running, version 1.0.8 was released on May 20th, 2016.  So at this time it’s about 10 months old.  The current C SDK is now up to version: 1.1.10.  There have been a number of changes and improvements during this time around retry logic and resource management that could well resolve the problem you are seeing.  Please update your client to the latest C client SDK version and perform your tests again.  If you do continue to see a problem please enable logging and provide a new trace so I can take a look.

  Thanks,

~Jonathan

**Comment by baker1971** [comment]
Thank you for quick reply mate. Will rebuild using 1.1.10 and see if the socketio error is resolved.

**Comment by jtanner-msft** [comment]
Closing this GitHub issue as we're continuing the investigation directly offline.
