### ISSUE TITLE
MQTT over websockets

### ISSUE THREAD

**Issue by TreesaChandy** [Azure/azure-iot-sdk-c#1085]
I need to use MQTT over Web sockets inorder to use proxy.But when I use this protocol I get segmentation fault after a period of time.

**Comment by rafilho** [comment]
Hi @TreesaChandy, can you please provide additional details for this issue? Please follow the New Bug template so we can have all the information needed to investigate this problem. Thank you.

**Comment by rafilho** [comment]
We have fixed some issues on using MQTT over websockets. However, without additional details, it is hard to understand if this issue is related to the fixes we have done. Since there was no updates to this issue for more than a month, I am closing it for now. Please reopen if this is still a problem. Thanks.

**Comment by az-iot-builder-01** [comment]
@TreesaChandy, @rafilho, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
