### ISSUE TITLE
Can't build both iot-edge-v1 SDK and latest azure-iot-sdkc in a single project.

### ISSUE THREAD

**Issue by JesvinJoseph** [Azure/azure-iot-sdk-c#1095]
I developed an application using both iot-edge-v1 SDK and azue-iot-sdk-c. Now I am stuck at the 1.2.12 version of the sdk-c. I can't upgrade to the latest version of sdk-c because of [this issues](https://github.com/Azure/iot-edge-v1/issues/663) which I raised on the issue page of iot-edge-v1. Is upgrading to iot-edge-v2 is the only solution to solve this? Can you help?

**Comment by rafilho** [comment]
Hello @JesvinJoseph, unfortunately this is the only solution to solve it for now. The Edge team has this work on their backlog, but still no timeline for upgrading the version of the C SDK. I will close this issue here, since we are already tracking it on the Edge project ( #https://github.com/Azure/iot-edge-v1/issues/663). Feel free to reopen if you need any help specifically related to the C SDK. Thanks.

**Comment by az-iot-builder-01** [comment]
@JesvinJoseph, @rafilho, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
