### ISSUE TITLE
AMQP <-> Eventhub <-> C SDK <-> C# SDK system properties mismatch

### ISSUE THREAD

**Issue by czyba** [Azure/azure-iot-sdk-c#111]
I have noticed a couple of mismatches in behavior as well as interface between the different SDKs and the IoT Hub documentation.

If you take a look at the [documentation for messages](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messaging#message-format) you can see that a message should have fields `To` and `UserId`. From the client side, the `To` field isn't necessary since it's implicitly defined as the corresponding IoTHub. The `UserId` field, should be defined as far as I understand it.

Furthermore, the [C# SDKs Message Class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.message?view=azuredevicesclient-1.2.6) allows me to set both fields. The [C SDKs equivalent](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/inc/iothub_message.h), as far as I know, is not able to set either field. I can see why there is no method for the `To` property, but there should be one for the `UserId` property, even if it should be the same as the DeviceId.

When I receive a message from the C SDK with the [C# EventData Class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.eventdata?view=azureservicebus-4.0.0) and take a look at the system properties, both fields are missing. This is unexpected, because the documentation as well as the [AMQP Protocol](http://www.amqp.org/sites/amqp.org/files/amqp.pdf) Chapter 3.2 let me believe that both fields should exist.

On the other hand, in the [C SDKs EventData class](https://github.com/Azure/azure-event-hubs-c/blob/master/eventhub_client/inc/eventdata.h) does not even provide me with a way to access system properties like the C# SDK does.

I have also discussed this issue on [stackoverflow ](http://stackoverflow.com/questions/43200966/how-do-i-set-certain-system-properties-with-the-azure-iot-c-sdk-for-the-amqp-pro) with Rita Han - MSFT, who proposed a workaround solution by setting the `To` and `UserId` properties via the application properties instead of the system / message properties.

So I wonder:

- Is this mismatch between the APIs and behaviors intentional?
- Is there some "proper" way of setting those properties with the C SDK?
- What is the actual semantic of `UserId` and when should it be set?
- Is this an issue with the C SDK? If so, is it going to be fixed?

Kind Regards,
Christopher Czyba

**Comment by olivierbloch** [comment]
Hi @czyba 
As you noted on SO, this indeed seems to be a bug in the C SDK that should take care of populating To and UserId and also let the user access them like in other languages.
We'll take a closer look.
Thanks

**Comment by chrit-msft** [comment]
@czyba Thank you for reporting this.  I am in the middle of reviewing the source and our documentation to understand the differences between the SDK's.  I will provide you with updates as we progress forward.

**Comment by chrit-msft** [comment]
@czyba I have discussed this issue with the C SDK owner and would like to answer the 4 questions you posted above. 

•Is this mismatch between the APIs and behaviors intentional?
Behavior should be aligned between the SDKs and this is being investigated.

•Is there some "proper" way of setting those properties with the C SDK?
The system uses these and sets them properly.
If you are attempting to identify the origin of the device sending the message use the Device Connection ID.
If you need your own custom way of identifing message origin you can use the application properties as indicated in the information provided on stackoverflow.

•What is the actual semantic of  UserId  and when should it be set?
UserID is used in the cloud to device message by the system and it is not
intended to be set by the user in a device to cloud message.

•Is this an issue with the C SDK? If so, is it going to be fixed?
No it isn't an issue with C SDK.  The C# SDK incorrectly exposes these system properties.  The SDK Teams are working on aligning the SDKs.

Please let me know if this sufficiently answers your questions.

**Comment by czyba** [comment]
Hi @chrit-msft,

Thanks for your answer. This clears up the mismatch I noticed when I tried to use the SDKs. I will adjust my code according to your answers. Thanks again!

Kind Regards,
Christopher Czyba

**Comment by chrit-msft** [comment]
@czyba based on your comment above I will close this thread.
