### ISSUE TITLE
[public-preview]Publish the Device Capability Model from the Device

### ISSUE THREAD

**Issue by matsujirushi** [Azure/azure-iot-sdk-c#1154]
I checked [digitaltwin_sample_model_definition.c](https://github.com/Azure/azure-iot-sdk-c/blob/public-preview/digitaltwin_client/samples/digitaltwin_sample_model_definition/digitaltwin_sample_model_definition.c) and [digitaltwin_model_definition.h](https://github.com/Azure/azure-iot-sdk-c/blob/public-preview/digitaltwin_client/inc/digitaltwin_model_definition.h).

API name is here:
DigitalTwin_ModelDefinition_Publish_**Interface**

Can I public the device capability model from the device and interfaces? (Both)

**Comment by jspaith** [comment]
@matsujirushi  - apologies for delay here.  This is a really good question and points to a poor naming decision on our part.

This is designed to retrieve *both* interfaces and device capability models.

I have opened #1212 to track fixing the name. I will also reach out to our other device SDKs since they may have the same issue with similar confusion.

Thank you for bringing this to our attention.  Because I think I've answered the question and we're tracking the underlying problem, I'm going to close this out.  By all means if there's other things that aren't clear on this or anywhere else, please reactive this or open a new issue.

**Comment by az-iot-builder-01** [comment]
@matsujirushi, @jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
