### ISSUE TITLE
Question of Azure SAS token refresh time

### ISSUE THREAD

**Issue by eme-jonesng** [Azure/azure-iot-sdk-c#1182]
- OS and version used: Embedded platform with FreeRTOS
- SDK version used: 
[/releases/tag/2019-05-16](https://github.com/Azure/azure-iot-sdk-c/releases/tag/2019-05-16)
`SHA-1:11d5150aeb26635862cf50484af9c7e8badd52a0`

**Description:**
My device is using MQTT to connect to the Iot Hub and I found that it keeps disconnect and reconnect after 48 minutes. Then I found that we can use IoTHubClient_LL_SetOption() to set the sas_token_lifetime. If I set the time less then 48 minutes, it works. However, for value larger than 48 minutes, it is still 48 minutes. 
For our application, we want to minimize the re-connection time per day to 1. Is it possible? or there is other concern?

Thank you.

**Comment by khilscher** [comment]
Try the following to override the SAS token lifetime. You should see a disconnect and a reconnect at 80% of the sas token lifetime. 

        //Override SAS token lifetime
        size_t sas_lifetime = 86400;
        (void)IoTHubDeviceClient_SetOption(device_handle, OPTION_SAS_TOKEN_LIFETIME, &sas_lifetime);

**Comment by ewertons** [comment]
@khilscher ,
you are absolutely correct.

@eme-jonesng ,
if you check this code, you will see the option name that can be used to set the SAS token expiration time:
https://github.com/Azure/azure-iot-sdk-c/blob/2019-10-07/iothub_client/src/iothub_client_core_ll.c#L2310

It gets consumed by our MQTT internal transport here:
https://github.com/Azure/azure-iot-sdk-c/blob/2019-10-07/iothub_client/src/iothubtransport_mqtt_common.c#L2405

So that should allow you to control the amount of time the MQTT transport waits until it attempts to refresh the SAS token. 
Please be aware of:
- the [80% safety multiplier](https://github.com/Azure/azure-iot-sdk-c/blob/2019-10-07/iothub_client/src/iothubtransport_mqtt_common.c#L2406) that @khilscher mentioned;
- if not set, the default duration of the auto-generated SAS tokens is [one hour](https://github.com/Azure/azure-iot-sdk-c/blob/2019-10-07/iothub_client/src/iothub_client_authorization.c#L87);
- An increase in the SAS token lifetime (using the SetOption and option above) may result in failure if done after the client has already connected. Please set the lifetime right after using _CreateFromConnectionString, and before calling _DoWork or initiating any operation with the device client instance.

**Comment by az-iot-builder-01** [comment]
@eme-jonesng, @khilscher, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
