### ISSUE TITLE
using iothub service client  behind a proxy

### ISSUE THREAD

**Issue by Benjamin118** [Azure/azure-iot-sdk-c#1233]
Hi,

On Ubuntu 18.04 platform
SDK ref. : 1.3.5

We need to use SDK service client behind a proxy.

This SDK uses amqp transport (messaging).

How is it possible to use AMQP/WS with using proxy, as it is done in SDK client ?

Thank you in advance

**Comment by ewertons** [comment]
Hi @Benjamin118 ,

unfortunately the Azure Iot Hub service client in C is currently prioritized below the other languages we support ([C#](https://github.com/Azure/azure-iot-sdk-csharp), [Java](https://github.com/Azure/azure-iot-sdk-java)), since it is not being extensively used in small devices.

It would be possible to have the service client connecting through a proxy, though.
If you look at this sample (lines [70](https://github.com/Azure/azure-iot-sdk-c/blob/DeviceStreaming/iothub_client/samples/iothub_client_c2d_streaming_sample/iothub_client_c2d_streaming_sample.c#L70) and [179](https://github.com/Azure/azure-iot-sdk-c/blob/DeviceStreaming/iothub_client/samples/iothub_client_c2d_streaming_sample/iothub_client_c2d_streaming_sample.c#L179)), inspect how the proxy-related code is used with the "xio" component (xio is our abstracted interface for data I/O).
That code would need to be injected [here](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_service_client/src/iothub_messaging_ll.c#L1160).

If you would like to post a pull request with the changes though, I would help reviewing and merging it expeditiously to unblock you.

**Comment by ewertons** [comment]
@Benjamin118 , we will close this issue for now, but please feel free to reopen it if you would like to follow up.

**Comment by az-iot-builder-01** [comment]
@Benjamin118, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
