### ISSUE TITLE
Add PKCS #11 support.

### ISSUE THREAD

**Issue by markrad** [Azure/azure-iot-sdk-c#1246]
**Is your feature request related to a problem? Please describe.**
Feature request: Many HSMs can be conveniently accessed by a standardized API called PKCS 11. By supporting this in the SDK itself it would allow a much easier path for those wishing to use an HSM that supports this interface. Essentially having out of the box support in the manner of the existing TPM support.

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
The alternative is making extensive modifications to the SDK code to support the HSM.

**Comment by ewertons** [comment]
As per offline discussion, we have come to an agreement that the new Azure SDK for Embedded C suite would be the best place for this enhancement to be done.
We filed an internal task to track this request.
Thanks,
Azure IoT SDK Team.

**Comment by ronnytittoto** [comment]
Hi team, is PKCS #11 support now available?
Thanks!

**Comment by CIPop** [comment]
@ronnytittoto yes, support has been added for OpenSSL on Linux by supporting OpenSSL ENGINEs. (Windows should already have support if the Windows Certificate Store is used instead of files on disk with a proper HSM/PKCS#11 driver.)

For most cases, we recommend using our SDK in conjunction with [Azure Identity Service](https://azure.github.io/iot-identity-service/).
Examples of both Azure Identity Service as well as using a PKCS#11 Engine are available [here](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/devdoc/iothubclient_c_library.md#openssl-engine-examples). 

This support has been added in https://github.com/Azure/azure-iot-sdk-c/pull/1798

**Comment by kiranpradeep** [comment]
@CIPop Is this support (pkcs11 via OpenSSL engine) limited to iothub client or does it equally apply to dps client? From the PR, it appears like both are supported. But this query is since, as part of #1798, although samples in [iothub_client](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client) folder have been updated, the samples in [provisioning_client](https://github.com/Azure/azure-iot-sdk-c/tree/master/provisioning_client/samples) were left untouched.

**Comment by CIPop** [comment]
@kiranpradeep The feature was added to the common TLS layer but we have only tested it to work with the IoT Hub client and various OpenSSL engines.

**Comment by kiranpradeep** [comment]
@CIPop Thanks. To confirm the understanding, can we provide a string like `pkcs11:object=ec-privkey;type=private?pin-value=1234` in custom HSM module API (in custom_hsm_get_alias_key) and expect the openssl engine/pkcs11 integration to take over? 
<sub> Fully understand that this might be untested </sub>

**Comment by CIPop** [comment]
@kiranpradeep you would also need to configure the type of Key, engine name, etc - similar to the Hub sample and documentation, but yes, _in theory_ it should work.

**Comment by Styne13** [comment]
Are there any news using SSL Engine support in Provisioning Client?
We also try to achieve this by calling `Prov_Device_SetOption(prov_device_handle, OPTION_OPENSSL_ENGINE, opensslEngine);` and `Prov_Device_SetOption(prov_device_handle, OPTION_OPENSSL_PRIVATE_KEY_TYPE, &x509_key_from_engine);` with `opensslEngine` set to `e4sss` (our engine_id configured in default _openss.cnf_ in _/usr/lib/ssl-1.1/_).
Outputs from SSL Engine Plugin are displayed, so it seems that the private key reference read by _custom_hsm_get_alias_key_ is used to access the HSE.
Unfortunately execution stops with `free(): invalid pointer Aborted` after everything is set up and _Prov_Device_Register_Device()_ is called.
