### ISSUE TITLE
CPU Utilization is always above 60% 

### ISSUE THREAD

**Issue by sarangkalbande** [Azure/azure-iot-sdk-c#126]
OS -Ubuntu 14.04
SDK - Version 1.0.8
CPU :- ARM M Corte x-A9, 800MHz z (Freescale  i .MX6-S)

# Description of the issue:
While running C SDK on my Device CPU Utilization always shows between 40% to 60%.
My Application is actually not doing much of processing work then only thing remain is C SDK.

I would like to know what is causing C SDK to use higher CPU.

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by czyba** [comment]
Hi @sarangkalbande ,

that is something I've been wondering about for a while as well. On my development machine I never noticed it before. Once I tested this on my embedded, Linux-based device, however, I noticed a load of roughly 20% in idle.

OS Debian Jessie
SDK -  Version 2017-03-24
CPU - 400MHz PowerPc (I forgot the actual name / brand)

**Comment by ollyw** [comment]
I have looked at this a little bit using the sample C SDK, and I think it is because the SDK seems to use poll based communications. For example, from a sample:
``` 
             for (index = 0; index < DOWORK_LOOP_NUM; index++)
                {
                    IoTHubClient_LL_DoWork(iotHubClientHandle);
                    ThreadAPI_Sleep(1);
                }
```
You may consider that this loop is doing work, then sleeping for a second, but actually the ThreadAPI_Sleep API is in _milliseconds_ (unlike most sleep functions). Therefore, if you assume that the DoWork takes a millisecond of CPU, and then sleep for a millisecond, you would get 50% CPU on a single device. 

If you don't need low latency comms, then sleep for longer (e.g. 15 milliseconds), to use less CPU.

It would be nice to understand if there is any support for true asynchronous behavior in future SDKs. Most modern libs support event based processing from the network stack (e.g. libevent, libuv), which provide low latency and low CPU, not a comprise of one or the other. It would be really nice to get some info on this from an expert.
*Caveat: I am not an expert, just started looking at Azure IoT this week!*

**Comment by anthonyvercolano** [comment]
In response to the OP, could you characterize which C API you were using?  Is it a close copy of the provided samples?  Does it use the convenience layer (IoTHubClient functions without the _LL_ in their name)?

In response to Ollyw:
Good post!

The important thing to note here is that these are *samples*.  They are by no means efficient.

If you were writing production quality code you would almost certainly not be calling the DoWork function in a tight loop.

If you were doing a simple telemetry only app, depending on your protocol and desire to keep the connection open, you might only call DoWork while your send is still pending and then every minute or so to have a keep alive.  If you were only expecting cloud to device messages you might only call DoWork even less.

IoTHubClient_LL_GetSendStatus can be your friend here.  It can tell you if there is pending work.   Also, there are callbacks available for getting confirmation that a send has completed.

Things like sensitivity to data transmission costs could make it very reasonable to close the connection if there are any quiet periods between sends.  A closed connection should use zero cpu cycles.

The convenience layer is very easy to code but one is likely to find that it consumes the most cpu cycles.

**Comment by czyba** [comment]
@ollyw, @anthonyvercolano 

The same code can be found for the non-LL versions which start their own threads. See the [ScheduleWork_Thread](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothub_client.c#L544) method. So this is not only an issue with the samples. It exists within the "convenience" api as well!

@anthonyvercolano 
I have to disagree with couple of your statements. Your statements are only true if you have one type of application - an application which only sends events and does not receive any messages from the cloud.

If you wish to receive messages you run into a conundrum. You have no other choice than to poll! You poll with `IoTHubClient_LL_DoWork` and receive the callback from the same thread. And since I don't know when I receive a C2D message I have no other choice than to poll frequently. Of course this has the advantage of being able to avoid multithreading and all the issues, i.e. synchronization, related to it.  I have yet to find a mechanism where I can ask if the IotHubClient if it has anything to receive and then to call DoWork, however.

Either way, I have not yet found a solution which allows me to:

- receive messages asynchronously as early as possible, although I can do this by polling frequently
- and have next to no load if no messages are being send or received

If I have missed anything or if you have any suggestions on how to work with the SDK such that this works, please, feel free to enlighten me.

Kind Regards,
Christopher Czyba

**Comment by ollyw** [comment]
@anthonyvercolano Thanks for the response, and thanks for Microsoft's ongoing open source efforts. It is much appreciated.

@czyba well done for finding that the high-level/convenience client also does indeed call `ThreadAPI_Sleep(1)` in a tight loop. This is too aggressive for most use cases. It may be useful for there to be an option to set the poll rate, and default it to something more like 5ms.

For my use case, I do actually want the lowest possible latency, but not at the expense of consuming all my CPU cycles, as the system needs to do other tasks too! Exposing the underlying socket handle would at least allow the use of select(). Even a blocking read for a few of milliseconds is better than a sleep. Use of kpoll and other devices would really be better though.

As a related note, I see that the high-level client's worker does thread synchronisation using `iotHubClientInstance->LockHandle`. I can't find any documentation of the thread safety of the APIs, it seems like using the convenient client is not only more 'convenient' but addresses thread safety, which I could not find discussed with regard to using the LL API. The high level API source code reveals that IoTHubClient_SendEventAsync takes a lock, but LL API doesn't AFAIK, so it when directing people to use the LL API, it should be made clear that the LL API is not threadsafe

**Comment by anthonyvercolano** [comment]
For czyyw:

My response was not meant to be an end all description of how to write a device client.  It was to point out a couple of the many issues one needs to think about.

Yes, given the constraint that one wants to respond to a cloud to device (c2d) message, perhaps a tight loop is necessary or perhaps the device client can handle a response within one or two seconds...

ollyw:
That tight loop in schedulework is a topic of discussion here.  Who knows where that might lead.

LL routines don't do synchronization.  It isn't immediately obvious from the documentation.  However, a close reading of:

https://azure.github.io/azure-iot-sdk-c/iothub__client__ll_8h.html

does actually say this.  You do need to look closely though.

Also documentation that describes the LL routines at a more global level can be found in:

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-device-sdk-c-iothubclient 

I've entered a PBI requesting more obvious documentation on this.

We are always looking to improve our device clients.  Developer feedback, including thoughts on how the client can be more "reactive" are welcome and affect our sdk development priorities.
