### ISSUE TITLE
build.sh documentation missing

### ISSUE THREAD

**Issue by seank-com** [Azure/azure-iot-sdk-c#129]
The build steps for the SDK say to use CMake but there is a build_all/Linux/build.sh script that seems to build. What is the purpose of this script? Are there two ways to build the SDK, should we ignore this script as it is only used internally? A build_all/README.md would be helpful to explain what the purpose of this set of folders is for.

**Comment by czyba** [comment]
Hi @seank-com 

For building the SDK it doesn't really matter which one you take. The `build.sh` script itself is simply a wrapper script for cmake. I believe the main reason for that scripts existence is that it's not trivial for someone to find out all possible SDK-defined cmake flags, i.e. how to enable/disable certain protocols and so on. Furthermore you can call `build.sh --help` in order to found out the usage of the script.

There is one major difference however. If you use the `build.sh` script, you cannot `make install` the libraries and sources. See [this issue](https://github.com/Azure/azure-iot-sdk-c/issues/71) for more information. If you wish to install them in your system/sysroot you need to use cmake and build the four components separately and with the `-Duse_installed_dependencies=ON` argument when calling `cmake`.

As a sidenote, you could also just call `cmake`, go to the build directory and use the `ccmake` to see all the flags in an ncurses gui.

I hope this helps. Kind Regards,
Christopher Czyba

**Comment by tameraw** [comment]
@czyba - Thanks for your helpful notes.
@seank-com - cmake should be used with the SDK. The build.sh have been a legacy way of building and are currently used internally for our build system. We intend to migrate away from those scripts and remove them from our repo in the future.
