### ISSUE TITLE
Stuck on IoTHubClient_LL_DoWork when message interval longer than 2 minutes

### ISSUE THREAD

**Issue by ellainec** [Azure/azure-iot-sdk-c#1323]
I have successfully connected and sent telemetry to my Azure IoT Central Application with the following code and kit: 
https://github.com/Avnet/azure-iot-mbed-client/blob/master/AvnetBG96_azure_client.cpp 
NUCLEO L496ZG-P MCU, X-NUCLEO-IKS01A2 sensor board, BG96 shield Cat.M1/NB1 & EGPRS module
Everything works fine when the message intervals are 2 minutes or less, but once I try anything longer like 3 minutes the code hangs in IoTHubClient_LL_DoWork. 
Two questions: 
1) Keeping the BG96 module powered on the whole time, how do I increase the message interval if I want to send, say, every 10 minutes?
2) If I want to implement Power Save Mode on my BG96 module, are there any other function calls or checks I have to implement in order for my code to not hang during DoWork?

**Comment by gregman-msft** [comment]
Thanks for the feedback, @ellainec, a few follow-ups/recommendations:

- Can you please open this issue on the Avent repo? Since there are runtime/platform specific dependencies that we may not be able to consider without familiarity with the solution.

- If you're calling DoWork every 10 minutes, the connection is likely to be disconnecting and you will need to re-establish the connection prior. You should be able to look at the IoT Hub logs sent to stdout to find this information.

Feel free to re-open this if it looks to be an issue with the SDK and further details.

**Comment by az-iot-builder-01** [comment]
@ellainec, @gregman-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
