### ISSUE TITLE
Module identities for IoT device usage

### ISSUE THREAD

**Issue by krokoko** [Azure/azure-iot-sdk-c#1365]
Hello team !

While using the IoT C device SDK for connecting an IoT device (not IoT edge device) to the hub, i realized in the portal that a device can have some module identities. Do you have an example somewhere on how to use those module identities along with the device concept, or there is not yet any implementation in the SDK to support that ? Thank you ! :)

**Comment by ewertons** [comment]
Hi @krokoko ,
there are no examples because that is not the intended use of the module identities. They are really designed to be used in Edge scenarios.

Note that using the connection string of a module identity with the [module client API](https://github.com/Azure/azure-iot-sdk-c/blob/2019-11-08/iothub_client/inc/iothub_module_client.h) is technically possible.

**Comment by krokoko** [comment]
@ewertons : thank you ! I was indeed wondering if it was possible to use the module client API, and if there were any upcoming features for iot devices using this module concept. Thanks again !

**Comment by az-iot-builder-01** [comment]
@ewertons, @krokoko, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
