### ISSUE TITLE
Timeout of invoking a module method is ignored

### ISSUE THREAD

**Issue by corollaries** [Azure/azure-iot-sdk-c#1378]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**
x86_64 Intel Industrial PC, Custom OS built with Yocto.
Compiled IoT Edge module on Ubuntu 18.04 with gcc 5.4.0.

**SDK Version**
Azure IoT C SDK 1.3.7

**IoT Edge Version**
IoT Edge 1.0.8.4, build: 26769994.

**Protocol**
MQTT

**Description**
When calling `IoTHubModuleClient_ModuleMethodInvokeAsync` from a custom IoT Edge module the timeout parameter is ignored / not used by the `Azure IoT C SDK`.

Given the following scenario:
1. Invoke module method with a timeout of 10 seconds.
2. Module method takes longer than 10 seconds to respond.
3. Timeout is not triggered at 10 seconds but after 30 seconds.

Expected:
1. Invoke module method with a timeout of 10 seconds.
2. Module method takes longer than 10 seconds to respond.
3. Timeout is triggered at 10 seconds. 

**Possible solution**
I did some digging in the `Azure IoT C SDK` and noticed the following line in `iothub_client_edge.c:42`

```c
static const char* const PAYLOAD_FMT = "{\"methodName\":\"%s\",\"timeout\":%d,\"payload\":%s}";
```
The `timeout` property is passed to the `Edge Hub` but after going through the source I could not find any code that reads this particular property. I then changed this line to the following.
```c
static const char* const PAYLOAD_FMT = "{\"methodName\":\"%s\",\"responseTimeoutInSeconds\":%d,\"payload\":%s}";
```
This gives the expected behavior that I was searching for since the `responseTimeoutInSeconds` **is** being read by the `Edge Hub`.

I noticed that either `responseTimeoutInSeconds` and `connectTimeoutInSeconds` can be set. 
What should the behavior of the timeout parameter be when invoking a module method? If needed, I can create a PR for the fix.

**Comment by ewertons** [comment]
Hi @corollaries ,
thank you very much for all your investigation!
Let us confirm the issue with the Edge team and a fix will be provided soon.

**Comment by darobs** [comment]
Hello @corollaries, 

I apologize for the the delay.  I've contacted the other IoT Edge team members so we can assign someone to look at this.

**Comment by varunpuranik** [comment]
@corollaries , @ewertons -
Yes, this seems like a bug in the SDK. EdgeHub expects the properties to be responseTimeoutInSeconds and connectTimeoutInSeconds. 
This is what the C# SDK sets as well. https://github.com/Azure/azure-iot-sdk-csharp/blob/4c7c9f2fa6b5dd2b709dd8195129334cdbd218c6/iothub/service/src/JobClient/CloudToDeviceMethod.cs#L115

Does the timeout work with the Service client in the C SDK, when invoked against IoTHub?

**Comment by corollaries** [comment]
@varunpuranik Did not test this since we're not using the service client, but after quick dive in the code I found the following. 

In `iothub_service_client/src/iothub_devicemethod.c:44`: `RELATIVE_PATH_FMT_DEVIECMETHOD_PAYLOAD` is defined like:
```
static const char* const RELATIVE_PATH_FMT_DEVIECMETHOD_PAYLOAD = "{\"methodName\":\"%s\",\"timeout\":%d,\"payload\":%s}";
```

No `responseTimeoutInSeconds` or `connectTimeoutInSeconds` is set. So I think the same problem exists in the Service client as well.

**Comment by ewertons** [comment]
Hi @corollaries , reviewing this issue again it seems a gap in the C SDK service client.
However, the service client in the C SDK is being kept only for historic reasons. It is not being actively maintained anymore.
As a workaround, please explore the service client on the other Azure IoT SDKs that do support it (e.g., Azure IoT SDK for C# or Java), or feel free to fork this repo and make the changes locally.

**Comment by corollaries** [comment]
@ewertons My original post was about the module client, not the service client. My latest comment on this issue was that this issue also persists in the service client, but we're not using that so it's fine. It would however be nice to get this resolved within the module client. From what I can see there have been no changes to the payload that's being sent so I'm assuming this bug is therefore not fixed.

**Comment by jspaith** [comment]
@corollaries - you're correct there is a bug here and it hasn't yet been fixed.  And like we said above the focus of all this is on module client, not service client which is for the most deprecated on C.

I'm changing the tag on this issue to a bug because it's pretty clear.  I apologize for all the trouble this has caused.

Unfortunately we cannot fix the API as it currently is.  Because of back-compat.  If a customer had taken the sample for instance - which has timeout=1 - then IoT Edge is ignoring this and is using 30 seconds by default.  If that customer updated the SDK after we made such a change, then they'd get a behavior change of devices in field.  Methods would start timing out after a second when we respected timeout.  The existing behavior is at least deterministic in that IoT Edge is just going to timeout whenever it feels so moved.

This means we're getting into `IoTHubModuleClient_LL_ModuleMethodInvoke2` territory where the new API would do the right payload.  Then we'd full on deprecate the original ones but can't remove.

I don't really have a timeframe for such a fix, and I'm happy to be corrected if my interpretation of all this is wrong.  

We clearly need to document in the product itself in any case since we need to be up front.  I want to sleep on this a bit more but I have a [proposed doc+sample change](https://github.com/Azure/azure-iot-sdk-c/tree/jspaith-doc-cleanup-2) that'll be basis for PR next week.  There's some other needed doc changes not directly related to that in this same fix.

**Comment by jspaith** [comment]
We're going to close this issue as it's realistically not something being fixed in any timeframe and based on complexity of fix and existing customer demand.

To summarize:
* The issue is that the C SDK - only when running in an IoT Edge hosted container - is sending the wrong JSON format to IoT Edge specifying a timeout on module/device invocation from the module client.  As @corollaries correctly analyzed above, this could be fixed by replacing `PAYLOAD_FMT` in `iot_client_edge.c` with lines below.

```c
static const char* const PAYLOAD_FMT = "{\"methodName\":\"%s\",\"responseTimeoutInSeconds\":%d,\"payload\":%s}";
```

* We cannot make that change directly in the official C SDK because of back-compat.  A customer setting timeout=1 in the API today would have Edge treating it as a 30 second timeout because of the bug.  If customer ever took a hypothetical SDK update that have fixed it, they'd be unknowingly be getting a timeout=1.  This could well pass their tests in a happy environment but break things out in the field for them and be really unpleasant for them to debug.

* The API not respecting the timeout has been documented.

* Creating a `IoTHubModuleClient_ModuleMethodInvokeAsync2` is only way to address this which is possible but a fair amount of plumbing work in both core and UT to enable.  Since we haven't heard strong demand for this it's not something we're going to invest in unless we get more data about needing it.  If other folks are hitting this issue they should add a comment to this issue and tag @jspaith, @wduraes, and @ericwol-msft.

Once again our apologies that this problem made it out in the first place.
