### ISSUE TITLE
C SDK connectionString for Azure Compute & Storage emulator

### ISSUE THREAD

**Issue by DattatrayHinge** [Azure/azure-iot-sdk-c#138]
Hi,

I am using Azure IOT C SDK with Visual Studio 2015 and running sample "iothub_client_sample_mqtt" from given sample.

I want to use Azure emulator for development. Now the problem is I cannot find connectionString for IOT C SDK anywhere given in help files

Please let me know how to construct connectionString for IOT C SDK while using Azure emulator.

OS - Windows 10,
SDK version - IOTHUB_SDK_VERSION "1.1.13"
Visual Studio 2015

Thanks

**Comment by olivierbloch** [comment]
Hi @DattatrayHinge Azure IoT Hub cannot be run in any emulator at this point. You have to provision an instance of the service in the Cloud to work with it.
In order to create device identities and get connection strings for your devices, you can find instructions [here](https://github.com/Azure/azure-iot-device-ecosystem/blob/master/setup_iothub.md).
