### ISSUE TITLE
no API to get METHOD_HANDLE for the IoTHubDeviceClient_DeviceMethodResponse()

### ISSUE THREAD

**Issue by szsobocinski** [Azure/azure-iot-sdk-c#1437]
The iothub_device_client API provides a `IoTHubDeviceClient_DeviceMethodResponse()` call that may be used to respond asynchronously to a device method request. This method requires a METHOD_HANDLE parameter that identifies the request that is being responded to.
However, there is no clear way to get this METHOD_HANDLE from the iothub_device_client API. The only device method callack can be registered by `IoTHubDeviceClient_SetDeviceMethodCallback()`, but this doesn't provide METHOD_HANDLE and seems to require synchronous response to the request.

The underlying iothub_client API has a `IoTHubClient_SetDeviceMethodCallback_Ex()` that allows to register a callback with METHOD_HANDLE and actually works fine, but this API is marked deprecated now.

Considering the above, how the `IoTHubDeviceClient_DeviceMethodResponse()` is intended to be used by the SDK client, specifically where to get the METHOD_HANDLE parameter from?

**Comment by ewertons** [comment]
Hi @szsobocinski ,
apologies for the delay on the response, we have been reassigned to work on new development and that impacted the replies.

Your point seems very valid, we can see that METHOD_HANDLE is exposed through the [IOTHUB_CLIENT_INBOUND_DEVICE_METHOD_CALLBACK](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/inc/iothub_client_core_common.h#L159) function pointer. 

This pointer is used on the callback of [IoTHubClient_SetDeviceMethodCallback_Ex](https://github.com/Azure/azure-iot-sdk-c/blob/f8c73aca05763fa7fe222b455e9b71d82d2afb8c/iothub_client/inc/iothub_client.h#L337), defined in the deprecated iothub_client.h header.

We need to verify why this was not ported to iothub_device_client.h. 
Once we clarify on that, we will post an update.

**Comment by jspaith** [comment]
@szsobocinski yes your feedback is indeed valid.  Basically `IoTHubDeviceClient_DeviceMethodResponse` never should have made it into the iothub_device_client.h header file as the deprecated "coreClient" equivalent is used internally only.  That was my fault since I was overseeing that new header creation and I apologize it slipped through.

On this one specifically, I'm closing.  But... I've reactivated #1647 since it tracks async response to direct methods all-up which would basically be an umbrella for this issue.  

I don't have ETA on #1647 but it won't be in immediate term.  If we fix that, we'll most likely plumb up the required structure for this.  OR if we create a brand new API for this behavior , we would mark `IoTHubDeviceClient_DeviceMethodResponse` as formally deprecated.

**Comment by az-iot-builder-01** [comment]
@szsobocinski, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
