### ISSUE TITLE
Get Edge device name from inside an Edge module

### ISSUE THREAD

**Issue by gri6507** [Azure/azure-iot-sdk-c#1501]
I am writing an IoT Edge module using the azure-iot-sdk-c library. I would like to get the name of the current edge device at runtime into my module. Is there C API to do that?

When I do `docker exec <ContainerIdOfRunningModule> /bin/bash -c 'env'` I can see that there is a `IOTEDGE_DEVICEID` environment variable set in the container. However, getting the module name from the environment seems fragile as the name of that environment variable may change over time.

**Comment by ewertons** [comment]
Hi @gri6507 ,

We apologize for the long delay, but we were assigned to work on new code development and that affected our github response time.

Your question should have been filed on iotedge repo, since it seems specific to Azure IoT Edge.
We filed this issue on your behalf on the correct repo: https://github.com/Azure/iotedge/issues/3327 

This issue will now be closed. Please feel free to open a new issue if you have any questions related to this azure-iot-sdk-c SDK.

Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@gri6507, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
