### ISSUE TITLE
X509 cert with Azure IoTHub

### ISSUE THREAD

**Issue by zainuvk** [Azure/azure-iot-sdk-c#1524]
Looking for some help with the steps outlined here https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md

The issue is I am getting an error '9728:error:0607907F:digital envelope routines:EVP_PKEY_get0_RSA:expecting an rsa key:crypto\evp\p_lib.c:469:" whenever I try to get the key from PFX or PEM  which are generated using Powershell command as explained in the article .

 
![image](https://user-images.githubusercontent.com/13005040/80845754-d433d000-8c27-11ea-863a-c2c693c3cd10.png)
 

This screenshot below shows error while using PFX .
 
![image](https://user-images.githubusercontent.com/13005040/80845766-deee6500-8c27-11ea-9998-8594c5fb55dd.png)
 

I am trying to authenticate Raspberry Pi with X509  to Azure IoT Hub and would be later trying another device from Teltonika
 
The steps would be as expalined in this doc https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support

1)Get the Root certificate

2)Get the cert file and key file and create a TLS connection to Azure IoT Hub
 
But extracting key  from PFX or PEM generated through powershell is failing with the above said error. 

I did took the other approach ie; trying the Bash shell extraction of crt and key file from PFX went through without any error
![image](https://user-images.githubusercontent.com/13005040/80845784-ef9edb00-8c27-11ea-86df-c3a5320e8d27.png)
 

But then the challenge was certificate chain was not properly maintained 

![image](https://user-images.githubusercontent.com/13005040/80845793-f594bc00-8c27-11ea-9a1e-ebda5374e45e.png)
 

The certificate chain  is proper for PFX generated through powershell commands though.
 
![image](https://user-images.githubusercontent.com/13005040/80845800-fcbbca00-8c27-11ea-8aba-5d91218b297b.png) 

 

And if  crt and key  generated from Bash shell is used in Python script it fails and error is shown below
 
![image](https://user-images.githubusercontent.com/13005040/80845805-02191480-8c28-11ea-812c-a1fbe050e30a.png)
 

May be CRL check is failing  or certificate chain is not set.Probably there is something which I am missing and need some expert to review and guide.Could you please guide or share some pointers on how to move forward.

**Comment by CIPop** [comment]
@zainuvk could you please add the exact commands you tried?
For example, in [Step 2](https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md#step-2---create-the-certificate-chain) you need to choose between `ECC` and `RSA` certificates.  Choosing ECC (Elliptic Curve) would cause the export error above.

You can try `openssl ec` instead of `openssl rsa` to check if you've generated a PFX file containing a pub/pri ECC key-pair instead of an RSA one. Also, since you are working on Windows, you can double-click on the PFX file, import it and view the contents to understand if it's ECC or RSA.

Either way, please note that the scripts are for testing purposes only and, depending on the hardware used by OpenSSL, may have weak private keys (for example see [this IEEE article](https://spectrum.ieee.org/tech-talk/telecom/security/low-entropy-iot-internet-of-things-devices-security-news-rsa-encryption)).

**Comment by CIPop** [comment]
No answer for a month. Closing for now. Please add the required information before re-opening.

**Comment by az-iot-builder-01** [comment]
@zainuvk, @CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
