### ISSUE TITLE
IoTHubDeviceClient_SendReportedState not updating device twin on Azure portal

### ISSUE THREAD

**Issue by MogheesBinZahid** [Azure/azure-iot-sdk-c#1600]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Raspberry Pi, Raspbian Stretch Lite (Release 2018-11-13)
Cross Compiled on (Raspbian 8.3.0-6+rpi1) using GCC  8.3.0

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Release 2019-01-31

**Protocol**

MQTT

**Describe the Bug**
I am using [azure iot c sdk](https://github.com/Azure/azure-iot-sdk-c). I have implemented device twins with help this [link](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-c-c-module-twin-getstarted). I can recieve any change in device from backend. My code for device twin send reported properties part is

    void AzureIoT::sendMessage(char* message)
    {
     const char* reportedState = "{ \"interval\": 7000, \"LockerId\": 6}";
     size_t reportedStateSize = strlen(message);
     BOOST_LOG_TRIVIAL(info) << "reportedStateSize - [" << reportedState << "]";
     BOOST_LOG_TRIVIAL(info) << " MESSAGE - [" <<message<< "]";
    IoTHubDeviceClient_SendReportedState(device_handle, (const unsigned char*)(message), reportedStateSize, reportedStateCallback, NULL)	
    }	

The output of above code is:
**See Console Logs**

If I use **reportedState** instead of **message** in **IoTHubDeviceClient_SendReportedState** function the device twin is updated on azure portal successfully but I am not able to achieve this on with  **message** as a parameter. With **message** as a argument it is returning status code 400. Below function is working fine:

    IoTHubDeviceClient_SendReportedState(device_handle, (const unsigned char*)(reportedState), reportedStateSize, reportedStateCallback, NULL)

The message is created as follow:

    sprintf(telemetry_msg_buffer, "{ \"LockerID\": %d, \"LockerVoltage\": %.3f, \"Unit\": \"%s\"}",
    				locker_ID, locker_voltage, scale);

 

  [1]: https://i.stack.imgur.com/n3Sk5.png

**Console Logs**
[Azure IoT hub device twin code Output][1]

**Comment by ewertons** [comment]
Hi @MogheesBinZahid ,
The code you posted presents some questions, since you are passing the size of `reportedState`, but `message` as the data variable to the function.
You should either use just `message` and strlen(`message`) or `reportedState` and strlen(`reportedState`).

I would say the problem you are having is not related to the SDK itself, but to the language and wrapper design you are using.
Are you able to attach a debugger and step into IoTHubDeviceClient_SendReportedState all the way down to see what is carried in terms of pointer and what that pointer points to?

Is `message` containing a non-empty valid json string with a null terminator at the end? Please attach a debugger and check or print it and also validate the string you see against a json validator ([here is a list](https://www.bing.com/search?q=json+validator)).

**Comment by MogheesBinZahid** [comment]
Thanks for the reply @ewertons . I am using strlen(`message`) in (`reportedStateSize`) it was a mistake in adding the code sorry for that. I have verified the json from json validator it is a valid json. I will attach and debugger and see what is happening inside IoTHubDeviceClient_SendReportedState. I will get back to you if problem persist

**Comment by az-iot-builder-01** [comment]
@MogheesBinZahid, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
