### ISSUE TITLE
Renew SAS token without disconnect using AMQP

### ISSUE THREAD

**Issue by MartinTJDK** [Azure/azure-iot-sdk-c#1625]
We have been using MQTT (WebSocket) and SAS token with an expiry time of 1 hour.
The SAS token is generated and fetched from a server, and is refreshed/requested each hour.
To avoid the need for disconnect and the reconnect, which MQTT requires in order to accept a new SAS token, we are trying to use AMQP.
But it is difficult to find out how we can force the revalidation of the connection using a new SAS token.
Can anyone point me in the right direction?
Thanks.

**Comment by ewertons** [comment]
Hi @MartinTJDK ,
the Azure IoT C SDK does not have logic to request a new SAS token if the one provided expires.
Currently the only option is to destroy the device client and create a new one with the new SAS token.

**Comment by ewertons** [comment]
The SAS token is held by the "Authorization Module":
https://github.com/Azure/azure-iot-sdk-c/blob/41ffe848773c03985df395a4ca29d986b142033b/iothub_client/src/iothub_client_core_ll.c#L829

The validation of tokens is done in this part of the code:
https://github.com/Azure/azure-iot-sdk-c/blob/41ffe848773c03985df395a4ca29d986b142033b/iothub_client/src/iothub_client_authorization.c#L573

That function (IoTHubClient_Auth_Is_SasToken_Valid) gets invoked in this module, which pertains to the AMQP transport:
https://github.com/Azure/azure-iot-sdk-c/blob/41ffe848773c03985df395a4ca29d986b142033b/iothub_client/src/iothubtransport_amqp_cbs_auth.c#L278 

Here you would need to make changes to `create_and_put_SAS_token_to_cbs` so it doesn't fail if the result is SAS_TOKEN_STATUS_INVALID. The block that handles sas tokens

https://github.com/Azure/azure-iot-sdk-c/blob/41ffe848773c03985df395a4ca29d986b142033b/iothub_client/src/iothubtransport_amqp_cbs_auth.c#L278

should be similar to the one that handles device key and auto-generation of sas tokens

https://github.com/Azure/azure-iot-sdk-c/blob/41ffe848773c03985df395a4ca29d986b142033b/iothub_client/src/iothubtransport_amqp_cbs_auth.c#L264

Next, there should be changes to `IoTHubClient_Auth_Get_SasToken` to invoke a callback (or in your case simpler, read from an ENV VAR?) to get a new SAS token from user application. The change in that function would probably happen in this block:
https://github.com/Azure/azure-iot-sdk-c/blob/41ffe848773c03985df395a4ca29d986b142033b/iothub_client/src/iothub_client_authorization.c#L439

If you go with the option of having a callback for the authorization module to request new sas tokens, the constructor `IoTHubClient_Auth_Create`

https://github.com/Azure/azure-iot-sdk-c/blob/41ffe848773c03985df395a4ca29d986b142033b/iothub_client/src/iothub_client_authorization.c#L95

will also need to be changed to take a callback as argument (e.g., `requestSasTokenCallback`). 

Finally, this modified `IoTHubClient_Auth_Create` needs to be updated in the client core layer here:https://github.com/Azure/azure-iot-sdk-c/blob/41ffe848773c03985df395a4ca29d986b142033b/iothub_client/src/iothub_client_core_ll.c#L829

, and all the changes necessary to expose passing the `requestSasTokenCallback` callback to this layer.
Since you already use `IoTHubDeviceClient_Create` (which calls finally into `IoTHubClientCore_LL_CreateImpl`) to pass the SAS token, you could modify the `IOTHUB_CLIENT_CONFIG` struct here:

https://github.com/Azure/azure-iot-sdk-c/blob/41ffe848773c03985df395a4ca29d986b142033b/iothub_client/inc/iothub_client_core_common.h#L185

to take the `requestSasTokenCallback`.

**Comment by ewertons** [comment]
If you would like to collaborate with a PR I can discuss with my team to help add tests and get this enhancement added to the SDK code base.

**Comment by MartinTJDK** [comment]
Hi @ewertons,
Thanks a lot for the detailed description of adding the feature. Since I am working for a client (on this issue), I will have to ask them, if we should move forward with the enhancement.
Does any of the other SDKs (python/java/C#/...) lack the same feature, or do they implement the feature?
Please ask you team, if they will help with questions and review feedback, if I (and/or my client) decides to go for it.
Is all the AMQP logic ready for "upgrading" the security? I see, that is does support some sort of auth handling, when the AMQP "gateway" manages serveral devices.
Could you point me to a AMQP WIN32 example, which includes the iot sdk c source and not only the nuget packages - just to ease the development for me.
Thanks

**Comment by ericwol-msft** [comment]
C# has this feature. https://github.com/Azure/azure-iot-sdk-csharp
