### ISSUE TITLE
Creating IOT Hub App Project 

### ISSUE THREAD

**Issue by qzzf1w** [Azure/azure-iot-sdk-c#1645]
I am running your samples on RaspBerry PI 

Great!!

Now I want to write my own app.

I can recall seeing a page that walked through some of the steps.

I cant find it now.

Was it yours?

In particular I have created a custom HSM.

Which was a bit hairy to get working in t he sample environment.

How do I productionize this code?
Create the make files etc.
On Raspbian

**Comment by danewalton** [comment]
Few things here:

Note that the "custom hsm" that you have compiled is likely not secure as the private key is stored in memory and is just passed through in the function. So I hesitate to say that this implementation is enough for "production". There are security risks there. There is some good documentation [here](https://docs.microsoft.com/en-us/azure/iot-fundamentals/security-recommendations) which details best practices for security that I highly recommend you read before you go "production".

As far as the make file stuff, you can use CMake to do that pretty easily since our repo uses CMake. Basics for that can be found [here](https://cmake.org/cmake/help/latest/guide/tutorial/index.html).

**Comment by qzzf1w** [comment]
Thanks @danewalton for the speedy response!

I am not using the sample outright.
I am using a unique X509 certificate for each device.

Unfortunately my device does not have a physical HSM (or TPM)
My actual preference would be to use an Azuresphere.
But my customer (a manufacturer) has chosen against these
HW solutions for cost reasons.
So I am using file system based storage.

My customer is aware of the security implications.
They made a business decision weighing probability/impact/cost/customer appetite for spend.
And this is where they landed.

My sense is that this is not a isolated scenario for manufacturers.

Thanks for the pointer to the general CMake document.

I could swear I saw instructions more specific to Azure IOT C linux somewhere.
Maybe I am confused.
Will dive into this today.

May come back with specifi questions.

**Comment by danewalton** [comment]
We have some directions for cross compiling here:
https://github.com/Azure/azure-iot-sdk-c/blob/d59cc5c46d6d92881578c55d12b6f4449954e859/doc/SDK_cross_compile_example.md

If you have some specific questions/issues, feel free to open issues targeting them. It makes it easier to track and easy for others to learn from similar circumstances. I will go ahead and close this issue for now since the root question seems to be answered. Feel free to drop a comment asking us to reopen if you feel like it is unsolved. Thanks for the questions!

**Comment by az-iot-builder-01** [comment]
@danewalton, @qzzf1w, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
