### ISSUE TITLE
expiration of baltimore root ca and consequences for mqtt

### ISSUE THREAD

**Issue by coffeeaddict19** [Azure/azure-iot-sdk-c#1656]
When I inspect the Baltimore Root CA here:
https://github.com/Azure/azure-iot-sdk-c/blob/master/certs/certs.c
I see that it expires on May 12, 2025.

I have MQTT selected in my application as the protocol to use. My application is running in North America.

The CA certificates in certs.c are hard coded into my azure application. Obviously I need to change this, but some questions first:

What is the consequence when the Baltimore CA expires and my application is connected to IoT Hub in the North American region? Will D2C and C2D messages stop working?

Is there any plan to release a Baltimore CA certificate in advance of the May 12 2025 expiration? If so, how much of an overlap is planned?

What is the recommended Azure way to push down the updated CA to my application when it becomes available i.e Device Twin, C2D Message?

**Comment by alexmrtn** [comment]
Similar question have been discussed earlier: #1308 

I still have the same concern as you about this root CA update!

**Comment by ewertons** [comment]
Hi @coffeeaddict19 and @alexmrtn ,
thanks for the questions.

Here are the responses for each:

>What is the consequence when the Baltimore CA expires and my application is connected to IoT Hub in the North American region? Will D2C and C2D messages stop working?

The root certificate is used to validate the server certificate when TLS is negotiated.
That only happens during connection or reconnection of the Azure IoT client.
So when the Baltimore CA expires, the next time you try to connect to the Azure IoT Hub or if the client is running and needs to reconnect (because of loss of internet, for example), the client will fail to connect because its TLS layer will fail validating the server certificate.

>Is there any plan to release a Baltimore CA certificate in advance of the May 12 2025 expiration? If so, how much of an overlap is planned?

We do not have advertised plans yet, but for sure we will update the certs.c file in our repo earlier than that. 

>What is the recommended Azure way to push down the updated CA to my application when it becomes available i.e Device Twin, C2D Message?

There is no pre-defined way of how you should update certificates in your device.
If you do chose to use Device Twin for updating the cert, make sure you design your solution so you do not carry the root cert in your device's twin document all the time, as it will be transferred on the wire from the IoT Hub to the device every time the device request the full twin document (either by subscribing for Twin updates - which happens every time the client connects/reconnects - or calling IoTHubDeviceClient*_GetTwinAsync)..

**Comment by coffeeaddict19** [comment]
That you for your response. I'll close the issue. @ewertons  If you could please re-open it when the new root certificate becomes available and update the issue with the official announcement that a new cert is available, that would be helpful.

**Comment by az-iot-builder-01** [comment]
@coffeeaddict19, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by ericwol-msft** [comment]
Here is the technical blog link. If possible, you should also pin the other two root certs, as they will be use to sign the new IoT service certificates. 

https://techcommunity.microsoft.com/t5/internet-of-things/azure-iot-tls-changes-are-coming-and-why-you-should-care/ba-p/1658456

To continue without disruption due to this change, Microsoft recommends that client applications or devices pin the Baltimore root -
```
Baltimore Root CA
(Thumbprint: d4de20d05e66fc53fe1a50882c78db2852cae474)
```
To prevent future disruption, client applications or devices should also pin the following roots:
```
Microsoft RSA Root Certificate Authority 2017
(Thumbprint: 73a5e64a3bff8316ff0edccc618a906e4eae4d74)
```
```
Digicert Global Root G2
(Thumbprint: df3c24f9bfd666761b268073fe06d1cc8d4f82a4)
```

**Comment by coffeeaddict19** [comment]
Thank you very much! @ewertons does that imply that those two root CA's should be in the repo then i.e:
https://global-root-g2.chain-demos.digicert.com/info/index.html
https://actrsaroot2017.pki.microsoft.com/

?

**Comment by ericwol-msft** [comment]
No, moving forward, we will not be storing the certs in the repo and should be handled externally by the applications.
