### ISSUE TITLE
SimulateX509Device error: Error in sample: One or more errors occurred. (Operation is not valid due to the current state of the object.)

### ISSUE THREAD

**Issue by Waldulmer** [Azure/azure-iot-sdk-c#1684]
I run the application SimulateX509Device.exe from the command prompt and receive the following error.
![image](https://user-images.githubusercontent.com/22600469/95021856-9c4f0f80-0641-11eb-96ab-7b4b919e9c6f.png)
![image](https://user-images.githubusercontent.com/22600469/95021972-2d25eb00-0642-11eb-8541-68bd29148918.png)
![image](https://user-images.githubusercontent.com/22600469/95022026-91e14580-0642-11eb-8fe7-ce88d9f2a888.png)
Any suggestions on how to solve the error are appreciated. Regards.
[SimulateX509Device.zip](https://github.com/Azure/azure-iot-sdk-c/files/5323747/SimulateX509Device.zip)

**Comment by ewertons** [comment]
Hi @Waldulmer ,
this issue seems related to C# code.
The correct repository to file this issue on is https://github.com/Azure/azure-iot-sdk-csharp
We filed an issue in that repo on your behalf. Please follow up on issue https://github.com/Azure/azure-iot-sdk-csharp/issues/1596

Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@Waldulmer, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
