### ISSUE TITLE
Question for API IoTHubDeviceClient_LL_UploadToBlob() 

### ISSUE THREAD

**Issue by neotrip** [Azure/azure-iot-sdk-c#1692]
For API IoTHubDeviceClient_LL_UploadToBlob()

It includes two stages:

1. stage1:  authentication between client and server 
2. stage2:  uploading files to server

Are there any APIs to process stage1(authentication-stage) and stage2(uploading-stage) seperately?

If I get fail in stage1(authentication-stage) , then I may give up stage2(uploading-stage) explicitely.

**Comment by ewertons** [comment]
Hi @neotrip ,
no we do not separate the stages. If the IoTHubDeviceClient_LL_UploadToBlob() fails on stage 1 it will not proceed to stage 2.

**Comment by neotrip** [comment]
Hi ewertons,

Thanks for your reply.  

Just make sure again. So we have no seperate APIs to implement above stage1 and stage2, if I need to upload a flie?  Other azure-iot-sdk-c interfaces  may also be okay for me.

Following sample code, has interface "IoTHubDeviceClient_LL_SetConnectionStatusCallback()", seems it may get athentication status. But I fail to get authentication status by it, together with "IoTHubDeviceClient_LL_UploadToBlob". 

Thank you so much!!!

https://github.com/Azure/azure-iot-sdk-c/blob/3871e2fa70de79f72720bc4fdc21e4f3251d0269/provisioning_client/samples/prov_dev_client_ll_sample/prov_dev_client_ll_sample.c#L282

https://github.com/Azure/azure-iot-sdk-c/blob/3871e2fa70de79f72720bc4fdc21e4f3251d0269/provisioning_client/samples/prov_dev_client_ll_sample/prov_dev_client_ll_sample.c#L108-L128

**Comment by jspaith** [comment]
> Just make sure again. So we have no seperate APIs to implement above stage1 and stage2, if I need to upload a flie? 

Absolutely correct.  The API is monolithic as currently implemented.

>Following sample code, has interface "IoTHubDeviceClient_LL_SetConnectionStatusCallback()", seems it may get athentication status.

That is a perfectly reasonable assumption.  Unfortunately due to how the libraries are implemented, it's not correct.  `IoTHubDeviceClient_LL_SetConnectionStatusCallback` monitors the connection callback of "standard" MQTT|AMQP|HTTP sessions to IoT Hub for doing "standard" things like telemetry, device twin, etc.

The UploadToBlob code doesn't plumb into this unfortunately.  You can get a sense in `IoTHubClientCore_LL_UploadMultipleBlocksToBlobEx` where we certainly start with a `IOTHUB_CLIENT_CORE_LL_HANDLE` but then quickly into the uploadToBlob code it only has the `uploadToBlobHandle` which lacks any of this callback information and is a separate HTTP connection to IoT Hub.

I've opened #1700 to fix documentation more clear around this disconnection in reference docs.

**Comment by jspaith** [comment]
I've put a note to myself in #1700 to remind myself to come back to this one.

Since I think we've addressed main concerns - the Upload API is unfortunately monolithic, and we need to document the fact it's not integrated with the callback which 1700 will do - I'm planning on closing this issue.

If I'm closing it wrongly, please either open a new one or tag me in this thread & tell me what else we should monitor here.  We don't look at issues once they're closed so we'd definitely need something active to stay on our radar.

Thanks for your feedback and understanding on all this, @neotrip.

**Comment by jspaith** [comment]
Fixed #1702.

**Comment by neotrip** [comment]
@jspaith, @ewertons 

I still has a question about API IoTHubDeviceClient_LL_UploadToBlob().

It's a monolithic API, and cannot get connection status by "IoTHubDeviceClient_LL_SetConnectionStatusCallback()" as you mentioned.

But can we tell the reason of failure, by the return value of  IoTHubDeviceClient_LL_UploadToBlob().
Per code review, we may get following results:
   -    "IOTHUB_CLIENT_INVALID_ARG"
   -    "IOTHUB_CLIENT_ERROR"
   -    "FILE_UPLOAD_OK"
   -    "FILE_UPLOAD_ERROR"

It is not enough to get more detail reason, such as authentication failure, network failure, too big file ...
Is there any way to get this ?

Thanks a lot

**Comment by jspaith** [comment]
I think the answer here it depends on when you need the error?  If it's during your development cycle, then as long as `LogError` goes to a stdout then you can hopefully make sense of the errors.  Or else ping Ewerton and I and we can try to help and even make the messages better.

Now at runtime - unfortunately the monolithic nature of the API does make what you're doing possible.

**Comment by jspaith** [comment]
@neotrip - I think we've answered the question, at least with regards to what the SDK can presently do at runtime around this.  I'm closing the issue but if there's follow-ups please either create a new issue or respond to this thread and explicitly tag me so we're sure I'll see it.
