### ISSUE TITLE
[DM] Notification on nested model are triggered but model is not updated

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdk-c#170]
- **OS and version used:** Ubuntu 16.04 LTS

- **SDK version used:** 4a4d26d90a6ed27a6b46504845477a03f8b092d0

# Description of the issue:
When using nested models, the desired properties change notification is triggered but the object itself does not reflect those changes. This is not the same behavior as #158 , because this time, the correct value is never received in the callback.

# Code sample exhibiting the issue:
Modify the devicetwin_simplesample to use this twin model

```
BEGIN_NAMESPACE(MyNS);

DECLARE_STRUCT(DeviceInfo,
    ascii_char_ptr, Manufacturer,
    ascii_char_ptr, ModelNumber,
	ascii_char_ptr, SerialNumber,
	ascii_char_ptr, FirmwareVersion,
	ascii_char_ptr, HardwareVersion,
	ascii_char_ptr, SoftwareVersion
);

DECLARE_STRUCT(SyncTime,
		bool, Enabled,				///< Is the sync time is enabeled or not, this is set via DSP, not fro the device itself
		int, Frequency           ///< The frequency, in seconds, at which DSP wants us to update the date ISO 8601 string recurance format (R/PT1H) (
);

DECLARE_STRUCT(TimeZone,
		ascii_char_ptr, CountryCode, ///< ISO 3166 country code
		ascii_char_ptr, ZoneName    ///<Taken from tz table
);

DECLARE_MODEL(TimeModel,
	WITH_REPORTED_PROPERTY(TimeZone, TimeZone),
	WITH_REPORTED_PROPERTY(SyncTime, SyncTime)
);

DECLARE_MODEL(VersionModel,
	WITH_REPORTED_PROPERTY(int, ModelVersion),
	WITH_REPORTED_PROPERTY(ascii_char_ptr, AgentVersion)
);

DECLARE_MODEL(SyncTimeConfigModel,
	WITH_DESIRED_PROPERTY(bool, Enabled),
	WITH_DESIRED_PROPERTY(int, Frequency)
);

DECLARE_MODEL(ConfigModel,
	    WITH_DESIRED_PROPERTY(SyncTimeConfigModel, SyncTime, onSyncTimeChanged)
);

DECLARE_DEVICETWIN_MODEL(DeviceModel,
    WITH_REPORTED_PROPERTY(DeviceInfo, Device),
	WITH_REPORTED_PROPERTY(TimeModel, Time),
	WITH_REPORTED_PROPERTY(VersionModel, Version),
	WITH_DESIRED_PROPERTY(ConfigModel, Config),
	WITH_METHOD(Reboot),
	WITH_METHOD(GetUTCTime)
);

END_NAMESPACE(MyNS);
```
With the following onSynTime callback:

```
void onSyncTimeChanged(void* argument)
{
	(void)argument;
    /*by convention 'argument' is of the type of the MODEL encompassing the desired property*/

	SyncTimeConfigModel* conf = argument;
	printf("Received a new desired SyncTime : [%s] - [%f]", conf->Enabled?"ON":"OFF", conf->Frequency);
}
```

**Comment by jspaith** [comment]
I apologize for the delay here and the fact you've hit this in the 1st place.  

I've confirmed this is indeed a bug in the C SDK serializer.  I have a provisional fix.  What was happening is we weren't taking into account any offset of the nested substructure when passing the pointer into the callback.

I'll get on creating a proper regression testing since this shouldn't have slipped through.  Definitely by end of week.  If you want to play with fix in meantime, the gist is below:

In commanddecoder.c around line 907 (under the SCHEMA_MODEL_IN_MODEL block)

                                    onDesiredProperty((char*)startAddress + offset);
Needs to become
                                    void *writeAddress = (char*)startAddress + offset + Schema_GetModelModelByName_Offset(modelHandle, childName_str);
                                    onDesiredProperty(writeAddress);

**Comment by lmussier** [comment]
@jspaith Thanks for looking into this.
We'll try the fix asap.

**Comment by jspaith** [comment]
Actually the behavior you're seeing is by design.  The comment here gives a flavor:
/*by convention 'argument' is of the type of the MODEL encompassing the desired property*/

So instead of typecasting to SyncTimeConfigModel, you should do this:
```
void onSyncTimeChanged(void* argument)
{
    /*by convention 'argument' is of the type of the MODEL encompassing the desired property*/
	ConfigModel* configModel = (ConfigModel*)argument;
	printf("Received a new desired SyncTime : [%d]\n", configModel->SyncTime.Enabled);
}
```

I can't really change the behavior to pass in the SyncModel because it'd break back-compat with anyone casting against the encapsulating method.

I'll review the docs & samples so this behavior is more obvious.

Once again, sorry you hit this and for delay.

**Comment by lmussier** [comment]
@jspaith Ok, I understand what is going on there.
I'll let you close after your doc change or right now.

Thanks again.

**Comment by jspaith** [comment]
@lmussier I've updated the **onDesiredMaxSpeed** (which is in devicetwin_simplesample and the template others typically use) with much clearer guidance about what the void* is.  

Thanks again for calling this to our attention so hopefully other folks don't stumble over this.
