### ISSUE TITLE
How to club multiple telemetry message and send to cloud as single message.

### ISSUE THREAD

**Issue by rajaggrawal** [Azure/azure-iot-sdk-c#1701]
Our Telemetry message size is short. let say size is around 500B.
As per azure prices , each message which size is <=4KB is charged for one message, means 500B size message will charged for one message(4KB).
So we want to club multiple message and send clubbed message(size near to 4KB) to cloud.

Could you please suggest how to club multiple message to single message and send to iothub?
Or is there any way to send array of telemetry messages ?

**Comment by ewertons** [comment]
Hi @rajaggrawal ,
the C SDK already batches telemetry messages if using the AMQP or HTTP protocol.
If you are using MQTT protocol (more recommended over the other two), there is no batching in the SDK itself. What you can do is to join your messages at your application (using your own design to logically separate messages) and send them as one telemetry each. On the service side you must use your own logic to separate the messages.
The Azure IoT C SDK does not support any specific type for telemetry message payloads, they are treated by the SDK and the Azure IoT Hub as a plain byte array.

**Comment by rajaggrawal** [comment]
@ewertons 

Do i need to invoke any specific c sdk method to batch telemetry for AMQP/HTTP. 
Or is it default taken care by C sdk?

**Comment by rajaggrawal** [comment]
@ewertons 


https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-construct#message-size

As per above link message size include below 3 points

1. The body size in bytes.
2. The size in bytes of all the values of the message system properties.
3. The size in bytes of all user property names and values.

How user will know the message size ?
do we have a method in C sdk for this ?

**Comment by ewertons** [comment]
@rajaggrawal ,

The batching happens automatically within the C SDK if using AMQP or HTTP protocols.

We do not have a function to help calculate the message size or the sizes of its components.
Focusing on telemetry for example, there is part of the publish message that is dedicated to the main topic name expected by the IoT Hub, like:

`devices/<device id>/messages/events/`

On top of that, there might be properties of the message, concatenated as a suffix in the form of a <key>=<value>[&] string, as in:

`devices/<device id>/messages/events/<key>=<value>[&<key>=<value>[...]]`

So that size must be subtracted from the maximum size the accepted by the Azure IoT Hub per packet.
The remaining size can then be used for the payload.

**Comment by ewertons** [comment]
Hi @rajaggrawal ,
we will close this issue for now, but please feel free to reopen it or create a new one if you would like to follow up.
Thanks,
Azure IoT SDK Team

**Comment by az-iot-builder-01** [comment]
@rajaggrawal, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
