### ISSUE TITLE
Location of LogError

### ISSUE THREAD

**Issue by Abhi2109** [Azure/azure-iot-sdk-c#1730]
Hi,
I am using xlogging to log my errors , but i need to know , what is the default error log location and how i can change that to my desired location.

**Comment by danewalton** [comment]
Hi @Abhi2109 do you mean essentially where the "`printf`" essentially is?

**Comment by ewertons** [comment]
If you what you are asking is what @danewalton is mentioned (i.e., you want to change the code to redirect the logs from the console to another sink), this is where our logger implements the print-to-console routines:
https://github.com/Azure/azure-c-shared-utility/blob/master/src/consolelogger.c

**Comment by Abhi2109** [comment]
void consolelogger_log(LOG_CATEGORY log_category, const char* file, const char* func, int line, unsigned int options, const char* format, ...)

in the above function can you please describe what is file (Do i need to specify File path or the name)

Better if you can provide me with detailed description about each of the parameter then i guess would be of great help.

**Comment by Abhi2109** [comment]
Do i need to do enable any option in cmake file so that consolelogger can log that?

**Comment by jspaith** [comment]
There's no cmake option for this specifically.  Note that you do NOT want to set `no_logging` in cmake or else this will strip out the logs from the SDK itself.  If you do nothing on this you'll be fine though since we do log by default.

To specify an alternate log location, you'll want to use [xlogging.h](https://github.com/Azure/azure-c-shared-utility/blob/master/inc/azure_c_shared_utility/xlogging.h) which is located also in the c-utility.  The interesting functions are `xlogging_set_log_function` and `xlogging_set_log_function_GetLastError`.

I do have a sample for you.  **This was from my private developer files and has received 0 test, even from me!**  It won't compile because there's stuff that'd have been confusing and unrelated to logging that I've removed from this.  But if you start at `Module_Initialize` and follow the helpers you'll get a sense of setting up alternate outputs.  This sample, which again has 0 test, writes out to a file.

[loggerSimple.txt](https://github.com/Azure/azure-iot-sdk-c/files/5597843/loggerSimple.txt)

**Comment by az-iot-builder-01** [comment]
@danewalton, @Abhi2109, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
