### ISSUE TITLE
default value of “PROV_OPTION_TIMEOUT”

### ISSUE THREAD

**Issue by neotrip** [Azure/azure-iot-sdk-c#1736]
When I reviewed SDK code, I found PROV_OPTION_TIMEOUT has no default value.

Per Prov_Device_LL_DoWork， does it mean the state machine will wait forever in  CLIENT_STATE_REGISTER_SENT or CLIENT_STATE_STATUS_SENT?   Why not to set a default value inside SDK? 

Thanks!

https://github.com/Azure/azure-iot-sdk-c/blob/26d8aed1362e4434afcf2f62267995bb92e6c262/provisioning_client/src/prov_device_ll_client.c#L1195-L1207

**Comment by jspaith** [comment]
> When I reviewed SDK code, I found PROV_OPTION_TIMEOUT has no default value.

Correct.  By default we don't set anything here.

>Per Prov_Device_LL_DoWork， does it mean the state machine will wait forever in CLIENT_STATE_REGISTER_SENT or CLIENT_STATE_STATUS_SENT? 

No.  That would be bad.  There are some calls in the DoWork function to the transport specific Doworks `prov_transport_dowork` and potentially calls like `prov_transport_register` if state machine demands it.  But DoWork is expected to be called by the application on a periodic timer.


>Why not to set a default value inside SDK?

The model here is that the application itself has some sort of timer for how long it wait (or how many times it will call) `Prov_Device_LL_DoWork`.  So after \<x\> minutes the application itself can decide to either abandon the request or close the DPS down and retry.

The prov timeout option seems to be a convenience where the SDK can track some of this for you instead of monitoring this at your application layer.  But it's not required since your application can do the same thing, and because DoWork() calls never block for "that" long your app thread should always have the opportunity to do this.

Perhaps we should have set a default for this in the SDK.  At this point though it's moot because we would impact back-compat if we guessed a default that was lower than an app managing this state on their own.

**Comment by jspaith** [comment]
I'm closing since I think I answered the question.  If you have followups, by all means open a new issue or put further comments here and tag me so I see it.

**Comment by az-iot-builder-01** [comment]
@neotrip, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
