### ISSUE TITLE
Azure IoT hub getting delay using direct Method call

### ISSUE THREAD

**Issue by MogheesBinZahid** [Azure/azure-iot-sdk-c#1740]
We have free tier of Azure IoT hub. We want to open and close lock using azure IoT hub direct method. The locks are controlled with raspberry pi. The raspberry pi connected with azure IoT hub. The delay in opening a lock after receiving direct method call from Azure is less than 1 sec. Other than 1 sec delay between communication of lock and raspberry pi. We are facing 3-4 sec delay in receiving direct method call from Azure IoT hub. We are using servers of West Europe. Can you tell me if this delay is because we are using free tier?

**Comment by danewalton** [comment]
Hey @MogheesBinZahid the free tier part shouldn't matter. Just so I understand your issue correctly:
- There is a delay from the service (Azure IoT Hub) to the raspberry pi of about 3-4 seconds.
- Once the raspberry pi receives the direct method invocation, there is a delay of less than a second for the lock to open or close (IE the processing of the method and physical action take less than a second).

Do I have that right?

If so, may I ask if you are using the `_LL_` version of the APIs or the convenience layer? If you are using the `_LL_` version, the application must call `do_work` in order to process the message (send/rec). In the samples we have a delay between those successive calls. Is it possible you have a delay higher than needed?

https://github.com/Azure/azure-iot-sdk-c/blob/aa1d586546b061ac7451f5f358e50c27fbfa5308/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L180-L181

**Comment by danewalton** [comment]
Hi @MogheesBinZahid I'm going to go ahead and close this for now. Please let me know if you need additional help and if I should reopen the issue.

**Comment by az-iot-builder-01** [comment]
@MogheesBinZahid, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by MogheesBinZahid** [comment]
Sorry for late reply in first part you are right. We are using Azure IoT C SDK. We are using convenience layer

**Comment by danewalton** [comment]
And just to double check is the situation as I described what is happening? (the two bullet points)

**Comment by MogheesBinZahid** [comment]
Yes you got it right in two bullets points

**Comment by danewalton** [comment]
Okay so off the top of my head, it's possible the device is doing other work before it gets to yours. We have an option here:
https://github.com/Azure/azure-iot-sdk-c/blob/c5c6258b0a1166710979d9df31c13aaebcd76667/iothub_client/inc/iothub_client_options.h#L89
to change that. Note that it can't be between 0 and 100ms as found here:
https://github.com/Azure/azure-iot-sdk-c/blob/c5c6258b0a1166710979d9df31c13aaebcd76667/iothub_client/src/iothub_client_core.c#L1725
Maybe try reducing the interval to 250ms and see if you see improvement?

Something like this in your code:
```c
unsigned int new_timeout = 250;
IoTHubDeviceClient_SetOption(device_handle, OPTION_DO_WORK_FREQUENCY_IN_MS, &new_timeout);
```

**Comment by MogheesBinZahid** [comment]
Ok thanks I will try it and get back to you

**Comment by MogheesBinZahid** [comment]
Hi In _LL_ api version we are setting IoTHubDeviceClient_LL_DoWork frequency ourself but in convience layer API what is default value of OPTION_DO_WORK_FREQUENCY_IN_MS

**Comment by danewalton** [comment]
You know looking at it again I'm sorry, I misread that code snippet. The default `do_work` interval in the convenience layer is 1ms not 1 second. And it must be between 0 and 100ms. So it is indeed as fast as it can be.

Are you able to try the same with a desktop machine (Linux or Windows), connecting to the same hub? I'm curious if you see similar behavior on a different device.

**Comment by danewalton** [comment]
Going to go ahead and close this for now. Let me know if you would like it reopened for further questions.
