### ISSUE TITLE
option "OPTION_BLOB_UPLOAD_TIMEOUT_SECS" doesn't work.

### ISSUE THREAD

**Issue by neotrip** [Azure/azure-iot-sdk-c#1746]
I have simple APP to upload a big file 100M with OPTION_BLOB_UPLOAD_TIMEOUT_SECS of 10sec

1) IoTHubClientCore_LL_SetOption(device_handle, OPTION_BLOB_UPLOAD_TIMEOUT_SECS, 10sec)
2) IoTHubDeviceClient_LL_UploadToBlob(device_handle, ..., 100M)

When 10sec timeout is reached, but file uploading is still under going without quit.
Why option "OPTION_BLOB_UPLOAD_TIMEOUT_SECS" doesn't work?
What shall I do, if I need quit uploading when 10sec timeout fired?

**Comment by ericwol-msft** [comment]
From the documentation at https://github.com/Azure/azure-iot-sdk-c/blob/86c0884e9a0c4332aafba70ca201384495915d7f/doc/Iothub_sdk_options.md

Timeout in seconds of initial connection establishment to IoT Hub. NOTE: This does not specify the end-to-end time of the upload, which is currently not configurable.

**Comment by neotrip** [comment]
okay thanks a lot, @ericwol-msft

**Comment by neotrip** [comment]
@ericwol-msft 

Because IoTHubDeviceClient_LL_UploadToBlob() is blocking and SDK provides no timer for it, so I have to implement timeout mechanism in my APP?

What happens if I destroy the iothub device handle before IoTHubDeviceClient_LL_UploadToBlob() return? Will it force UploadToBlob return at once, or wait  until UploadToBlob finish? 

What happens if IoTHubDeviceClient_LL_UploadToBlob() is called before previous IoTHubDeviceClient_LL_UploadToBlob() return for the same iothub device?

Thanks ?

**Comment by jspaith** [comment]
First you should never ever destroy an `LL` handle from a different thread if any active call to the `LL` layer is in play.  The `LL` is for lower layer which is another way of saying no-locking.  These aren't thread safe APIs.

Even if you moved to the convenience layer (e.g. `IoTHubDeviceClient_UploadToBlobAsync`) which is thread safe, closing the handle isn't going to force the connection to close immediately.  It would block until complete.

One possibility (shoutout to @ericwol-msft who had this idea) is to use `IoTHubDeviceClient_LL_UploadMultipleBlocksToBlobAsync`.  This still blocks from your application layer that calls the function.  However instead of putting in a large block and waiting, the IoT SDK will keep calling your application for the callback you pass in to return the data.  This could monitor the time that had passed (via the `context` passed around) and the callback could itself return a `IOTHUB_CLIENT_FILE_UPLOAD_GET_DATA_ABORT` to stop the process otherwise.

There's sample code demonstrating the callback mechanism [here](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_upload_to_blob_mb/iothub_client_sample_upload_to_blob_mb.c).

**Comment by neotrip** [comment]
@jspaith

If timeout fires and quit from IoTHubDeviceClient_LL_UploadMultipleBlocksToBlobAsync(), the files uploaded in blobstorage may be not complete? Maybe only half of the full content?

Is there any way to delete broken file?

**Comment by neotrip** [comment]
@jspaith

I cannot find API "IoTHubDeviceClient_LL_UploadMultipleBlocksToBlobAsync()".

Do you mean "IoTHubDeviceClient_LL_UploadMultipleBlocksToBlob()"?  And determine weather to quit inside callback function?

**Comment by jspaith** [comment]
For your questions:
* Yes, my initial response had a typo.  `IoTHubDeviceClient_LL_UploadMultipleBlocksToBlob` is what you want.
* If you abort the call partway through, the file will NOT be committed to the storage.  Which I assume is what you'd want.

You can see [here](https://github.com/Azure/azure-iot-sdk-c/blob/c5c6258b0a1166710979d9df31c13aaebcd76667/iothub_client/src/iothub_client_ll_uploadtoblob.c#L79) the SDK has code that creates a different response to the server when your callback returns back `IOTHUB_CLIENT_FILE_UPLOAD_GET_DATA_ABORT`.

You can also manually see this for yourself (and I manually checked this before posting!).  In the [sample](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_upload_to_blob_mb/iothub_client_sample_upload_to_blob_mb.c) I changed `getDataCallback` so on the 100th block I returned `IOTHUB_CLIENT_FILE_UPLOAD_GET_DATA_ABORT`.  I verified that a file was not created, but that uncommenting this GET_DATA_ABORT return did have file happily uploaded.

```c
            // snip rest of file...
            if (block_count < 100)
            {
                snprintf(data_to_upload, sizeof(data_to_upload), data_to_upload_format, block_count);
                *data = (const unsigned char*)data_to_upload;
                *size = strlen(data_to_upload);
                block_count++;
            }
            else
            {
                // This simulates reaching the end of the file. At this point all the data content has been uploaded to blob.
                // Setting data to NULL and/or passing size as zero indicates the upload is completed.

                *data = NULL;
                *size = 0;

                (void)printf("Indicating upload is complete (%d blocks uploaded)\r\n", block_count);
                return IOTHUB_CLIENT_FILE_UPLOAD_GET_DATA_ABORT; // <============= line I added
            }
```

**Comment by neotrip** [comment]
yes, it works
thank you, @jspaith

**Comment by jspaith** [comment]
Sorry we don't currently have a cleaner way to address this and thanks for understanding the workaround.  Closing out the issue but as always don't hesitate to reach out if there's further concerns.

**Comment by az-iot-builder-01** [comment]
@ericwol-msft, @neotrip, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
