### ISSUE TITLE
'segment fault' - after closing SSH session to a device via device streams

### ISSUE THREAD

**Issue by gerhard67** [Azure/azure-iot-sdk-c#1767]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Linux ${mydevice} 4.15.0-1098-azure #109~16.04.1-Ubuntu SMP Wed Sep 30 18:53:14 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux 

**SDK Version (Please Give Commit SHA if Manually Compiling)**

demouser@iiot-lab-edge-vm:~/azure-iot-sdk-c$ git log
commit be574df7ba495f5463c5325a6433406ce754744c
Author: xinyiz1226 <xinyiz@microsoft.com>
Date:   Fri Feb 28 06:05:41 2020 +0800

**Describe the Bug**

I have the same issue, as described here https://github.com/Azure/azure-iot-sdk-c/issues/967
Unfortunately, the issue is closed, but not described who it was fixed. 

steps 

> - start on the device "iothub_client_c2d_streaming_proxy_sample"
> - start on the client "Quickstarts\device-streams-service\proxy.js"
> - start putty to connect 
> - login 
> - exit 
> - iothub_client_c2d_streaming_proxy_sample dumps 

**log on the device** 

${myuser}@${mydevice}:~/azure-iot-sdk-c/cmake/iothub_client/samples/iothub_client_c2d_streaming_proxy_sample$ ./iothub_client_c2d_streaming_proxy_sample
-> 12:28:16 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: ${myiothubname}.azure-devices.net/${mydeviceid}/?api-version=2019-07-01-preview&DeviceClientType=iothubclient%2f1.3.6%20(native%3b%20Linux%3b%20x86_64) | PWD: XXXX | CLEAN: 0
<- 12:28:16 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
-> 12:28:16 SUBSCRIBE | PACKET_ID: 2 | TOPIC_NAME: $iothub/streams/POST/# | QOS: 0 | TOPIC_NAME: $iothub/streams/res/# | QOS: 0
<- 12:28:16 SUBACK | PACKET_ID: 2 | RETURN_CODE: 0 | RETURN_CODE: 0
<- 12:28:31 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: QOS_VALUE_INVALID | TOPIC_NAME: $iothub/streams/POST/TestStream/?$rid=1&$url=wss%3A%2F%2Fdb-001.northeurope-001.streams.azure-devices.net%3A443%2Fbridges%2Fih%2FIoT${myiothubname}%2Fd%2F${mydeviceid}%2Fsid%2F9fabf543585148b382c6f473da874c2e%2Fr%2Fdevice&$auth=${somesecrettoken} | PAYLOAD_LEN: 0
Received stream request (TestStream)
-> 12:28:31 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/streams/res/200/?$rid=1
Client connected to the streaming gateway (WS_OPEN_OK)
Reporting traffic statistics every 10 seconds.
[2020-12-01 12:28:32 UTC+0000] Network traffic (in bytes) (sent=42; received=28)
[2020-12-01 12:28:42 UTC+0000] Network traffic (in bytes) (sent=1328; received=1376)
[2020-12-01 12:28:52 UTC+0000] Network traffic (in bytes) (sent=3584; received=528)
Segmentation fault (core dumped)

**log on the windows client**

listening on port: 2222...
initiating stream
results received from the device: {
  "authorizationToken": "${somesecrettoken} ",
  "isAccepted": true,
  "uri": "wss://db-001.northeurope-001.streams.azure-devices.net:443/bridges/ih/${myiothubname}/d/${mydeviceid}/sid/${mysid}/r/service"
}
got websocket - creating local server on port 2222
client socket disconnected

**dmesg log**
[ 7538.442069] iothub_client_c[15175]: segfault at 0 ip 000000000040dc22 sp 00007ffc7f68bd60 error 4 in iothub_client_c2d_streaming_proxy_sample[400000+84000]

**update ... we now test this also on an RPI**

Linux RevPi40645 4.19.95-rt38-v7+ #1 SMP PREEMPT RT Tue, 16 Jun 2020 13:25:43 +0200 armv7l GNU/Linux
Same result

**Comment by jspaith** [comment]
Thanks @gerhard67 for all the offline communication as well as providing a core dump for me to analyze. 

The issue is in the code below, which is implemented as a callback in the samples themselves. The issue is the `close_code` may be NULL (see uws_client.c `on_underlying_io_bytes_received` processing of `WS_CLOSE_FRAME`).  But our code is dereferencing the NULL.  

An additional issue with this code is it assumes `extra_data` is non-NULL (which wasn't true in Gerhard's repo) and also that it's NULL terminated string, which it's not.

```c
static void on_ws_peer_closed(void* context, uint16_t* close_code, const unsigned char* extra_data, size_t extra_data_length)
{
    (void)context;
    (void)extra_data_length;
    (void)printf("on_ws_peer_closed\r\nCode: %d\r\nData: %s\r\n", *(int*)close_code, extra_data);
}
```

----
While looking at the sample's callback code, I also want us to look a bit more at `on_ws_frame_received`.  The issue here is that it's doing a `memcpy(stream_payload, buffer, size);`, but not checking that the `stream_payload` buffer is large enough to hold the size.

We don't want our samples to buffer over-run (and even if this isn't possible now due to some implementation quirks, that may all change so I'd really want this defensively coded).  I don't know what right behavior here though is, like whether to truncate or throw buffer away and also how to indicate this to whatever the sample is passing data onto.

**Comment by ewertons** [comment]
Fixed. Thanks.

**Comment by az-iot-builder-01** [comment]
@gerhard67, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
