### ISSUE TITLE
What's the deal with creating Debian Packages in general? and Raspberry Pi in particular?

### ISSUE THREAD

**Issue by IanMercer** [Azure/azure-iot-sdk-c#1823]
There is a [script](https://github.com/Azure/azure-iot-sdk-c/blob/master/build_all/packaging/linux/apt-get-release.sh) that appears to be intended for creating packages from the SDK code but it does not appear to have been updated in a long time.

I was able to build an `armhf`* package (cross-compiled with a Toolchain for the Pi4) by adding `SET(CPACK...` and `include(CPack)` to the `CMakeLists.txt` file and by running `cpack -C "Release" -G "DEB"` and I have successfully deployed it to a Raspberry Pi but ...

1) Is there an official plan to provide pre-build Debian packages for Raspberry Pi?
2) Is there a `CPack` definition somewhere that builds a package with all the correct settings?

**Comment by ewertons** [comment]
Hi @IanMercer ,
I would need to check it again, but I believe the existing apt packages we release work on Pi3.
however we haven't updated the release to publish focal fossa packages. 
If the issue is related to not having focal fossa packages, we are discussing adding support for it.
We do not have CPack definitions for azure-iot-sdk-c.

**Comment by IanMercer** [comment]
Specifically looking for Raspbian buster packaged support. All the doc examples I could find refer to cloning and compiling the SDK locally (e.g. https://github.com/Azure-Samples/iot-hub-c-raspberrypi-getstartedkit).

If not CPack then are there other definitions and scripts for creating DEB package builds available somewhere?
