### ISSUE TITLE
IOTHUBMESSAGE_ABANDONED Doesn't seem to be working

### ISSUE THREAD

**Issue by sarangkalbande** [Azure/azure-iot-sdk-c#185]
Setup as below:-
 SDK - 1.1.16, Ubuntu 14.04 and Core is ARM Cortex A9,MQTT

I have been using this SDK for quit a while and recently I have added IOTHUBMESSAGE_ABANDONED in receive message callback.
so basically when I get any message in callback and if the system is busy processing the previous one
I am returning the result as IOTHUBMESSAGE_ABANDONED
But after which I never get this message again.Usually SDK should keep of sending this message till I accept it.
What could be the issue here?
Also after how much time SDK would try to resend it?

**Comment by anthonyvercolano** [comment]
mqtt doesn't support the concept of abandoning a message.

**Comment by sarangkalbande** [comment]
@anthonyvercolano 
Thanks for this info.
If MQTT Doesn't support abandoning feature then why it is used in mqtt sample examples receive callback function.

**Comment by anthonyvercolano** [comment]
Not sure which sample you're referring to.

However, the most likely reason that it was removed was because mqtt doesn't support it and the code in the sample had been uh, um, repurposed, yeah that's it, repurposed from an amqp or http sample.

It's not the SDK.  The amqp protocol specification has the built in the concepts of accept, reject, abandon.  You can mimic it in http.  With mqtt, it is a conscious decision for the service side not to support it.

An article that discusses the topic (pardon the phrase) is https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-c2d  It mentions reject.   It should also say abandon.

I understand if you find this asymmetry curious.

**Comment by sarangkalbande** [comment]
@anthonyvercolano 
Thanks for this info.
Yes, I can see it's mentioned mqtt won't support these features.
but again in current release under  azure-iot-sdk-c/serializer/samples/simplesample_mqtt/simplesample_mqtt.c example I can see abandoning is being used as below snippet

/*this function "links" IoTHub to the serialization library*/
static IOTHUBMESSAGE_DISPOSITION_RESULT IoTHubMessage(IOTHUB_MESSAGE_HANDLE message, void* userContextCallback)
{
    IOTHUBMESSAGE_DISPOSITION_RESULT result;
    const unsigned char* buffer;
    size_t size;
    if (IoTHubMessage_GetByteArray(message, &buffer, &size) != IOTHUB_MESSAGE_OK)
    {
        printf("unable to IoTHubMessage_GetByteArray\r\n");
        result = IOTHUBMESSAGE_ABANDONED;
    }
    else
    {
        /*buffer is not zero terminated*/
        char* temp = malloc(size + 1);
        if (temp == NULL)
        {
            printf("failed to malloc\r\n");
            result = IOTHUBMESSAGE_ABANDONED;
}
Isn't it confusing?

**Comment by anthonyvercolano** [comment]
This sample will be fixed in a future release.  I realize that it is confusing and we appreciate you pointing this out.

**Comment by jebrando** [comment]
The change to remove the abandoned enum from the MQTT sample has been checked in.
