### ISSUE TITLE
[documentation] alternative to deprecated OPTION_MESSAGE_TIMEOUT for MQTT protocol

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#1889]
I am using MQTT protocol. I like to get failure callbacks if the SDK cannot send [[1](https://docs.microsoft.com/en-us/azure/iot-hub/iot-c-sdk-ref/iothub-device-client-ll-h/iothubdeviceclient-ll-sendeventasync)] a message within a specified period of time. Previously we could use OPTION_MESSAGE_TIMEOUT [[2](https://github.com/Azure/azure-iot-sdk-c/blob/86c0884e9a0c4332aafba70ca201384495915d7f/doc/Iothub_sdk_options.md#iot-hub-device-and-module-client-options)] which is deprecated. What is the alternative now? As per this reply [[3](https://github.com/Azure/azure-iot-sdk-c/issues/1626#issuecomment-673579713)], there is a configurable option to specify the message timeout. Is it possible to let us know what that is?

This query is related to #1626. But it had other questions also, so I am re-raising here.

**Comment by danewalton** [comment]
Hi @kiranpradeep here in the header we have listed that MQTT does not have a replacement. Sorry for the inconvenience.

https://github.com/Azure/azure-iot-sdk-c/blob/85227d84bd975096672d420c84b194f43cb2323c/iothub_client/inc/iothub_client_options.h#L43

**Comment by kiranpradeep** [comment]
Thanks for the reply. But that reply also has implications on how we should use the SDK. To confirm the understanding, once we invoked ` SendEventAsync`, and there is no internet connection, the message will be in sdk internal queue **forever**.  Is that correct understanding? If yes, this could lead to out of memory (oom) issues. 

How should we avoid this? Kindly guide. I could try setting retry policy, but as I understand it, retry policies only has impact on when to reestablish the connection. If there is no internet for extended duration, message will stay in sdk internal queue forever leading to oom. Humbly requesting to guide.

**Comment by danewalton** [comment]
Hi @kiranpradeep 

This is the section that is likely most relevant for your situation:
https://github.com/Azure/azure-iot-sdk-c/blob/d1a663b8710893e95bc8421470aee03aa565a550/iothub_client/src/iothubtransport_mqtt_common.c#L2412-L2422

The message will be retried after every `RESEND_TIMEOUT_VALUE_MIN` (60 seconds here), and if it reaches the maximum retry count (as currently is 2), then the client will move to notify the application that the message will cease to be retried due to a `IOTHUB_CLIENT_CONFIRMATION_MESSAGE_TIMEOUT`. At that point the client will remove the message from the queue and go through the disconnect process.
