### ISSUE TITLE
Headers and shared lib in relation to provisioning_service_client/ not included as part of build/install

### ISSUE THREAD

**Issue by jamesiotech** [Azure/azure-iot-sdk-c#1906]
Build the sdk by doing the following ...

```
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib -Dbuild_service_client=OFF -Dbuild_provisioning_service_client=ON -Duse_prov_client=ON -Dbuild_as_dynamic=ON -Dskip_samples=ON ..

make install
```

Headers and libs in relation to azure-iot-sdk-c/provisioning_service_client/ not included in install, even though cmake driven (-Dbuild_provisioning_service_client=ON -Duse_prov_client=ON) such that we add the directory in question i.e ... https://github.com/Azure/azure-iot-sdk-c/blob/master/CMakeLists.txt#L379

How is the Install of provisioning_service_client headers and shared lib handled in https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_service_client/CMakeLists.txt ?

**Comment by ericwol-msft** [comment]
The service client is deprecated in the C SDK. The IoT services APIs are supported in the other SDKs (C#/Python/Java)

**Comment by BinduRao2018** [comment]
Can you clarify the following:
-  Are iothub_service_client and provisioning_service_client  deprecated in the C SDK?
    Does that imply  C SDK cannot be used to support DPS? Should the enrolment has to be done manually?
- Sample code uses built-in custom_hsm_example for device(leaf) certificates required for provisioning as there are no APIs (like in C#/Jave) to pass these certificates. How to use provision client to add a device to IoTHub?

**Comment by ericwol-msft** [comment]
> `Are iothub_service_client and provisioning_service_client deprecated in the C SDK?`

Yes

> Does that imply C SDK cannot be used to support DPS? Should the enrolment has to be done manually?

provisioning_client is used for DPS on the device side. You can configure the automatic device enrolment in the enrolment group. Usually you don't want the device to access IoT service APIs, as this adds another set to credentials to the device. Potentially a higher privilege then necessary. If you want to do Individual Enrollments, then you would need to use one of the other IoT SDKs.

**Comment by BinduRao2018** [comment]
>> What does automatic device enrolment mean - Manually configuring group enrolment with certificates, or is there any way to configure automatically? (Without using provisioning service APIs - reference prov_sc_enrollment_group_sample.c)

>> How to pass device certificates to provision client without using custom_hsm_sample as I don't see any API to pass this info?

**Comment by ericwol-msft** [comment]
> What does automatic device enrolment mean - Manually configuring group enrolment with certificates, or is there any way to configure automatically? 

https://docs.microsoft.com/en-us/azure/iot-dps/how-to-manage-enrollments

> How to pass device certificates to provision client without using custom_hsm_sample as I don't see any API to pass this info?

device certificates are passed to DPS via TLS mutual auth on connection to the DPS service endpoint. The intermediate device cert is validated against the DPS enrolment group.

https://blog.rassie.dk/2018/04/azure-iot-hub-device-provisioning-with-group-enrollments/
https://docs.microsoft.com/en-us/azure/iot-dps/how-to-verify-certificates

**Comment by BinduRao2018** [comment]
Thanks for the links @ericwol-msft 
It is clear to me that I have to add a certificate under DPS and create a group enrolment on the Azure portal. I have gone through the docs available to create leaf certificates. However, my question is, how should these certificates (full-chain & private keys) be passed to SDK for provisioning in the absence of APIs? I will be using the installed version of SDK and won't have access to update custom_hsm_sample and rebuild?

**Comment by ericwol-msft** [comment]
I'm pretty sure 99.9999% that you don't want to use a custom HSM.

Anyways, this is how you use the TLS x509 auth with DPS enrollment group
https://docs.microsoft.com/en-us/azure/iot-dps/tutorial-custom-hsm-enrollment-group-x509

**Comment by BinduRao2018** [comment]
Apologies if I wasn't clear.
I have used the tutorial to understand and test group enrollment & provisioning with custom hsm using prov_dev_client_ll_sample.
We are middleware IoT developers that enable end-users (that own the device) to use our framework to send data to IoTHub.
How can middleware support/enable end-users to present their certificates to provision the devices programmatically in the absence of C SDK API to pass this information? 
In Java SDK, the Provisioning client gets the leaf certificates by the Security Provider package. Is something similar available on C SDK to read the device certificates to pass it to the provisioning client?

**Comment by BinduRao2018** [comment]
In addition, I have a question about Individual Enrolment - You have mentioned
'_If you want to do Individual Enrollments, then you would need to use one of the other IoT SDKs_.' - Could you elaborate further on this, please? Provided example prov_dev_client_ll_sample.c works well with individual enrollment using simulated x.509 device -dice_device_enrollment.

**Comment by CIPop** [comment]
@BinduRao2018 our Provisioning client has been designed around the [DICE/RIoT architecture](https://www.microsoft.com/en-us/research/publication/device-identity-dice-riot-keys-certificates/). In this architecture, devices must implement a form of attestation based on both an X509 Device Certificate as well as information regarding the device firmware (such as a hash). The actual certificate used within the TLS handshake, the _alias_ certificate, is generated on the device and is signed by the device certificate. Both individual and group certificates are supported (in individual enrollment mode, the client certificate's thumbprint should be configured in the DPS instance. In order to pass authentication, the service should be able to create a chain from the alias certificate(s) to one of the individual enrollment thumbprints.

In order to fully implement DICE, you must also use a [Custom Allocation Policy](https://docs.microsoft.com/en-us/azure/iot-dps/how-to-use-custom-allocation-policies?tabs=linux) (Azure Function) to verify that the value present within the Alias certificate matches the expected firmware version on the device.

1. That said, if you wish to bypass the DICE architecture and expose simple client X509 certificate authentication please see the custom HSM documentation and example:  https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/devdoc/using_custom_hsm.md . The example contains both the scaffolding for X509 as well as TPM. For your use case, implement TPM as no-op and create a state object that can be configured by your own public API. 

2. If you wish to properly implement DICE for your particular hardware, please see the implementation within [hsm_client_riot.c](https://github.com/Azure/azure-iot-sdk-c/blob/8f6b4823b7f6652578016ae3b19af871204beafb/provisioning_client/adapters/hsm_client_riot.c) which defines test EC certificate parameters (`get_riot_root_dev_key`) as well as DICE-specific Firmware measurement test values (`RAMDOM_DIGEST` and `firmware_id`). [CEC1702 ](https://www.microchip.com/pressreleasepage/secure-connected-nodes-CEC1702-DICE) is an example of hardware solution implementing DICE DPS.

Note that if no real HSM is used in conjunction with DICE, the device will be prone to various software and hardware-based attacks (fw changes, certificates could be extracted and used from a different location, etc).

I recommend also taking a look at our Embedded C SDK https://github.com/Azure/azure-sdk-for-c for a smaller and simpler DPS C client implementation (https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/samples/iot/paho_iot_provisioning_sample.c).

Closing for now as the questions diverged from the title. Please open new issues if you have more DPS client questions.
