### ISSUE TITLE
How to return back to the main program after retry time has expired?

### ISSUE THREAD

**Issue by Nakul93** [Azure/azure-iot-sdk-c#195]
Hello,
I have scenario where IOT hub would be initially connected via Wifi and if the connection is broken then I need to switch to GSM network. So is there any handler or something that would return to main loop after retrying for a specific period and then I could initiate the connection again using GSM network.

**Comment by ewertons** [comment]
Hi @Nakul93 ,

If you are using the IoTHubClient on Linux or Mac (only these), you have an option of selecting which network interface you would like to use for the connection.

It can be set as in here:
https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/tests/common_e2e/iothubclient_common_e2e.c#L476

To detect if the connection is down, you can use the ConnectionStatusCallback feature, as shown here:
https://github.com/Azure/azure-iot-sdk-c/blob/b128de1dcbfc7cb157d569a05a4a4008a2e2c448/iothub_client/tests/common_e2e/iothubclient_common_e2e.c#L854

**Comment by sarangkalbande** [comment]
@Nakul93 
Nakul, I am handling similar kind of scenario in my application.
So instead of relying completely on SDK Connectivity loss callback its better to have your thread which will monitor network connectivity over various interfaces like ethernet, wifi, cellular, GSM as per your preferences which will also be useful for your application in long run for various scenarios.

if there are no send confirmation ACKs for consecutive 5-6 sent messages then ask your thread to change network preference from non-working to working interface and remember to reset IOT connection string handle, SDK has some issue if the network is changed SDK doesn't resume Automatically till you restart your application or reset IOT Handle

**Comment by Nakul93** [comment]
@sarangkalbande well as of now I am restarting the application each time when one of the interface fails, but you see that is not the ideal way to do it. Actually what happens is when it goes on to the dowork function it only returns if the same interface has re-established the network connection. If you have worked on the lower levels of the SDK then please suggest me how to return to main loop when the current network is down.

**Comment by sarangkalbande** [comment]
@Nakul93 
I don't think SDK can distinguish among connectivity over different interfaces[Current and previous] besides It can only tell you if the connectivity is there or not for the specific interface as ewerton suggested in his comment.
Also, I think this is not something SDK has to handle but the user application has.

For your situation I would suggst set and use connection status callback and if the connection is down your application would come to know then switch to next interface from application and reset the connection string IoT handle and things start to work again,No need to restart complete application

**Comment by ewertons** [comment]
Hi @Nakul93,
were you able to successfully use the ConnectionStatus callback on your application?
Please let us know so we can close this issue.

Thanks,
Microsoft Azure IoT Team

**Comment by Nakul93** [comment]
Yes I was able to use the connectionstatus callback feature. Thanks a lot @ewertons.
