### ISSUE TITLE
Adding iothub sdk into C++ Linux App

### ISSUE THREAD

**Issue by melzoghbi** [Azure/azure-iot-sdk-c#202]
Hi,

I am using VS2017 Preview and i created a new console app (linux). I was able to configure the app and deploy it to a remote Ubuntu box with no issues. 

The issue i am having is when i try to include iothub_client.h in a cpp file, since i get this error when i run the app:

iothub_client.h: No such file or directory

I tried adding my .h path under C/C++ -> General --> Additional Include Directories by pointing to the folder path which include this header file and others as well.

#include <stdio.h>
#include <stdlib.h>

#include "iothub_client.h"    // compiler is throwing error because of this reference.
#include "iothub_message.h"
#include "azure_c_shared_utility/threadapi.h"
#include "azure_c_shared_utility/crt_abstractions.h"
#include "azure_c_shared_utility/platform.h"
#include "iothubtransportmqtt.h"

// Other code is emitted....

int main(void)
{
	iothub_client_sample_mqtt_run();
	return 0;
}

Please note that iothub_client.h is showing under External Dependencies folder in VS 2017 since i added those nuget packages through VS.

![image](https://user-images.githubusercontent.com/11993393/29232316-05d06b16-7eb9-11e7-9312-fb84670518d5.png)

I was able to run this sample [app ](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-device-sdk-c-intro) with no issues, but when i am trying to create a new app that is using new VS linux templates to easier deploy it to a linux environment. Therfore i do not want to configure make configs to cross compile my app into an Ubuntu box.

Any idea how to fix this?

**Comment by tameraw** [comment]
@melzoghbi - Thanks for filing this. We'll take a look.

**Comment by markrad** [comment]
Hi @melzoghbi,

Unfortunately I cannot even get "Hello world" to deploy to my Ubuntu machine. Since VS 2017 is still in preview, I am fairly limited with the amount of support I can provide. Perhaps the VS 2017 team have a bug reporting mechanism. You have more success if you take up this issue with them.

I'll work on getting my deploy working in the meantime.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @melzoghbi,

I had more success with a different Linux target. However I am still having issues with this. I'm wondering how you have your project set up. I built the SDK on my Linux box and performed a make install to place the headers and binaries into a location in my home directory. I tried to set up the flags in VS 2017 to have the code find the includes and link with the libraries. Though it was able to find the appropriate includes, it is failing to find the aziotshardutil library. I checked the command line for the linker options and it appears to be correct.

Is this how you are trying to build your application?

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Closing this since it is using prerelease software (VS 2017)

**Comment by Injac** [comment]
I had the same problem compiling the **iothub_client_sample_device_method** example for the **iothub_client**. It turned out, that the _cmake_ file used **/usr/include** instead of **/usr/local/include**. After compiling the **azure-iot-sdk** and running _make install_ it will install the headers in **/usr/local/include** instead of **/usr/include**.
