### ISSUE TITLE
Build error with iothub_message.h

### ISSUE THREAD

**Issue by gri6507** [Azure/azure-iot-sdk-c#2045]
The following code compiles just fine without any warnings/errors
```c
if (IOTHUB_MESSAGE_OK != IoTHubMessage_SetCorrelationId(message_handle, "MY_CORE_ID"))
```

However, the following code doesn't
```c
if (IOTHUB_CLIENT_OK != IoTHubMessage_SetContentTypeSystemProperty(message_handle, "application%2fjson"))
{
}
if (IOTHUB_CLIENT_OK != IoTHubMessage_SetContentEncodingSystemProperty(message_handle, "utf-8"))
{
}
```
Both of those functions, despite the documentation on https://docs.microsoft.com/en-us/azure/iot-hub/iot-c-sdk-ref/iothub-message-h generate the following
```
comparison between ‘enum IOTHUB_CLIENT_RESULT_TAG’ and ‘IOTHUB_MESSAGE_RESULT’ {aka ‘enum IOTHUB_MESSAGE_RESULT_TAG’} [-Werror=enum-compare]
```

I am building with `2021-01-Ref01-1` using GCC 9.3 on Ubuntu 20.04. Since I am build with `-Werror` this is problematic

**Comment by danewalton** [comment]
Hi @gri6507 not sure what the problem is here. The return value of `IoTHubMessage_SetContentTypeSystemProperty()` and `IoTHubMessage_SetContentEncodingSystemProperty()` is an `IOTHUB_MESSAGE_RESULT` not `IOTHUB_CLIENT_RESULT`. `IOTHUB_CLIENT_OK ` is an `IOTHUB_CLIENT_RESULT`. Is there a specific point in our code where this occurs or is this application code?

**Comment by gri6507** [comment]
@danewalton - You are absolutely correct. I was too close to the problem to see it as a basic copy and paste issue. Thank you!

**Comment by danewalton** [comment]
@gri6507 No worries happens to all of us!
