### ISSUE TITLE
SDK client status not recovering from the idle status

### ISSUE THREAD

**Issue by sathyendranv** [Azure/azure-iot-sdk-c#2058]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**
Cross Compiled on Ubuntu 18.04 using GCC 6.3.0

**SDK Version (Please Give Commit SHA if Manually Compiling)**

SHA-1: 6b6e2449672d229d4a0fc9503d8fd3b2b2dde5f1

**Protocol**
MQTT

Env 
armv5

**Describe the Bug**
We are running sdk with x509 provisioning and publishing message to hub in a regular interval (in hours). After 2 weeks of run, the iothub client goes into idle status when we are querying IoTHubDeviceClient_LL_GetSendStatus api. Even though the data is sending to the linkedlist it never comes out of the idle status and send the data to iothub. 

Is this expected behavior ? How do we get the client handle out of idle status? Currently we are restarting the service to send the data.

**Comment by danewalton** [comment]
Hi @sathyendranv do you happen to have any logs at all? Can you confirm that the device is indeed still connected?

I have recently also been letting customers know on 32 bit platforms with issues after running for several weeks of this fix we have here: https://github.com/Azure/azure-c-shared-utility/pull/557 with the original issue here: https://github.com/Azure/azure-c-shared-utility/issues/526. It may or may not be relevant to your issue but if anything of the original issue looks familiar please feel free to give the fix a try. Otherwise, more detailed logs would be great if you have them.

**Comment by danewalton** [comment]
Similar (maybe same) issue here: https://github.com/Azure/azure-iot-sdk-c/issues/1992#issuecomment-913361803

**Comment by danewalton** [comment]
Since [this issue](https://github.com/Azure/azure-iot-sdk-c/issues/1992#issuecomment-913361803) seems to be tracking the same problem, I'm going to go ahead and close this one. Please let us know if you feel that isn't true and we can track it separately.
