### ISSUE TITLE
MQTT client is left with dangling pointer after SAS token expiry

### ISSUE THREAD

**Issue by AGlass0fMilk** [Azure/azure-iot-sdk-c#2060]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Cross compiled on Ubuntu 20.04 using GCC ARM 9.2.1 20191025 for ARM Cortex M4 running Mbed-OS

Please note: this is an embedded microcontroller target with 1MB of flash and 256kB of RAM

**SDK Version (Please Give Commit SHA if Manually Compiling)**

2bff372a9b22b54d3d4bc9a3e74e349f68fcde46

LTS_07_2020_Ref01

**Protocol**

MQTT

**Describe the Bug**

When using SAS token authentication over MQTT, the SAS token must be periodically refreshed after it expires. This is an expected occurrence and shouldn't cause any issues.

During a disconnection, the XIO transport handle is freed at the Azure IoTHub Client layer:

https://github.com/Azure/azure-iot-sdk-c/blob/2bff372a9b22b54d3d4bc9a3e74e349f68fcde46/iothub_client/src/iothubtransport_mqtt_common.c#L1860

While it also calls `mqtt_client_disconnect`, this function does not set the XIO transport pointer stored in the MQTT client structure to NULL. 

https://github.com/Azure/azure-umqtt-c/blob/0c9cd1b323e58816fafe8d4db303b17ac2101b19/src/mqtt_client.c#L1232-L1294

This leaves a dangling pointer to the deleted XIO transport. The checks in the `mqtt_client` functions to catch this do not work, since the pointer is not set to NULL. The MQTT `do_work` function is subsequently called, which dereferences this dangling pointer and causes a hard fault.

Even if you manually disconnect and reconnect to refresh the SAS token, this hard fault still occurs.

I introduced a fix in the mqtt client here: https://github.com/AGlass0fMilk/azure-umqtt-c/commit/7e12aada6714077f6a8be140b8a955af79e84636

I left the client running overnight and have not seen any further issues/crashing.

I'm not sure if there's interest in upstreaming this patch because support for the above version ended last month. However, it is a critical bug that makes stable use of the Azure IoTHub client over MQTT impossible.

See ARMmbed/mbed-os-example-for-azure#33 for more details.

**Console Logs**
[test-1.log](https://github.com/Azure/azure-iot-sdk-c/files/7047600/test-1.log)

**Comment by AGlass0fMilk** [comment]
Tentatively, this looks fixed when updating to the latest LTS release. Running long term tests before marking as resolved.

Let me know if the fix mentioned above should be upstreamed.

**Comment by danewalton** [comment]
Hi @AGlass0fMilk this looks like a familiar problem. Can you see if the resolution from this thread helps here?
https://github.com/Azure/azure-iot-sdk-c/issues/1666

**Comment by AGlass0fMilk** [comment]
@danewalton Yes, that appears to be the same issue. Is there any reason it's not been backported to the LTS release the bug is present in? When the bug was discovered and fixed the LTS version was still supported.

I have tested the latest LTS release with Mbed-OS and can confirm this issue is no longer present.

**Comment by danewalton** [comment]
Good to hear the issue is fixed!

As far as the LTS go, we tend to focus on security issues and critical bugs to be backported to reduce the churn on long term supported branches. If customers have a critical need to have bugs backported and can't upgrade to a newer LTS as an option, we welcome requests for specific scenarios.

**Comment by ericwol-msft** [comment]
To keep churn in LTS releases to a minimum, we only backport bug fixes by requests only. As always, the ask is to keep up-to-date on the latest LTS releases, as they will contain fixes for specific reported issues. We do understand that new LTS releases will require more extensive end testing and there is always an option to ask for a bug to be back ported to your LTS release that is still supported so that there is a minimal impact to your SDK dependency.
