### ISSUE TITLE
STM32 Discovery kit IoT node - Provisioning registration fails

### ISSUE THREAD

**Issue by ademyankov** [Azure/azure-iot-sdk-c#2096]
Hi,
   I am using STM32 B-L475E-IOT01A Discovery kit with Azure IoT. Using the pre-built demo firmware to connect to Azure IoT Hub.

As per the instructions I created IoT Hub, DPS, linked them together, created the device using symmetric authentication but provisioning fails.

![image](https://user-images.githubusercontent.com/13845895/135507173-7462c14d-63d7-4ccc-94af-7c41be3079e0.png)

Console on the device:

```
-----------------------------
Saved Azure IoT Central Device Information:
        Saved ScopeID   : 0ne003D5A75
        Saved UseDPS    : Manual Provisioning
        Saved DeviceID  : B-L475E-001
        Saved PrimaryKey: ax/gg9DPaxGsisBsETOau60PW8z85RJBsI7U5hggJrw=
Wait 3 seconds for allowing User Button Control for changing it
-----------------------------
- Network Interface starting:
- Network Interface started:
   - Device Name : Inventek eS-WiFi.
   - Device ID : ISM43362-M3G-L44-SPI.
   - Device Version : C3.5.2.3.BETA9.
   - MAC address: C4:7F:51:06:1D:EA.
- Network Interface connecting:
- Network Interface connected:
   - IP address :  192.168.86.94.
Real Time Clock Intialized: 09-30-2021 17:56:15
Platform Init Done
Main Application Compiled Mar  8 2021 09:58:15
Serializer Initialized
RIOT hsm_client_x509_init
FW_SDK_DPS <<FP 5.1.1 SDK 1.3.6 Prov 1.3.6 id 003c0033384750102035314b>>
RIOT hsm_client_x509_init
   Provisioning API Version: 1.3.6
Ok calling Prov_Device_LL_Create
ok Prov_Device_LL_SetOption OPTION_TRUSTED_CERT
Ok Prov_Device_LL_Set_Provisioning_Payload
Ok calling Prov_Device_LL_Register_Device
-> 17:56:17 CONNECT | VER: 4 | KEEPALIVE: 0 | FLAGS: 194 | USERNAME: 0ne003D5A75/registrations/B-L475E-001/api-version=2019-03
-31&ClientVersion=1.3.6 | PWD: XXXX | CLEAN: 1
<- 17:56:17 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x0
-> 17:56:17 SUBSCRIBE | PACKET_ID: 1 | TOPIC_NAME: $dps/registrations/res/# | QOS: 1
Provisioning Status: PROV_DEVICE_REG_STATUS_CONNECTED
<- 17:56:17 SUBACK | PACKET_ID: 1 | RETURN_CODE: 1
-> 17:56:17 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $dps/registrations/PUT/iotdps-regist
er/?$rid=1 | PAYLOAD_LEN: 132
<- 17:56:18 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: $dps/registrations/res/401/?$rid=1
| PACKET_ID: 2 | PAYLOAD_LEN: 143
Error: Time:Thu Sep 30 17:56:18 2021 File:C:\nobackup\Code\repo\FP-CLD-AZURE1_New\Firmware\Middlewares\Third_Party\azure-iot-s
dk-c_public_preview\provisioning_client\src\prov_device_ll_client.c Func:prov_transport_process_json_reply Line:670 Unsuccessf
ul json encountered: {"errorCode":401000,"trackingId":"65bdb858-3ef7-4e77-b843-159f5a746e36","message":"Unauthorized","timesta
mpUtc":"2021-09-30T17:56:22.6721138Z"}
Error: Time:Thu Sep 30 17:56:18 2021 File:C:\nobackup\Code\repo\FP-CLD-AZURE1_New\Firmware\Middlewares\Third_Party\azure-iot-s
dk-c_public_preview\provisioning_client\src\prov_transport_mqtt_common.c Func:prov_transport_common_mqtt_dowork Line:1036 Unab
le to process registration reply.
Error: Time:Thu Sep 30 17:56:18 2021 File:C:\nobackup\Code\repo\FP-CLD-AZURE1_New\Firmware\Middlewares\Third_Party\azure-iot-s
dk-c_public_preview\provisioning_client\src\prov_device_ll_client.c Func:on_transport_registration_data Line:770 Failure retri
eving data from the provisioning service
-> 17:56:18 DISCONNECT
DPS call to Prov_Device_LL_Destroy
Provisioning registration failed!

Err Type AZURE_ERR_IOT_START
```

I can see messages going to the Hub

![image](https://user-images.githubusercontent.com/13845895/135507359-b8142089-844d-4827-8432-dd0cb9f21db4.png)

Does anyone know what is going on or what I am doing wrong? Or how can I triage the possible issues?

Thanks!

**Comment by danewalton** [comment]
Hi @ademyankov thanks for the question.

First off, I want to make sure that you are aware that you posted the SAS key and hub name for the device. This opens the possibility for anyone to use your credentials to connect to your hub and run up resource usage. I would recommend you roll your keys on the device to new ones whenever possible (se the "Manage Keys" section of the screenshot you posted).

Second I would love to encourage you to try using our recently released [Azure IoT middleware for FreeRTOS](https://github.com/Azure/azure-iot-middleware-freertos) with our [B-L475 Discovery Sample](https://github.com/Azure-Samples/iot-middleware-freertos-samples/tree/main/demos/projects/ST/b-l475e-iot01a) for that project. It brings smaller code size and increased performance with a more "constrained device" approach. We have a very simple demo showcasing DPS and IoT Hub.

With your situation here though (if you would like to stick to this SDK), what I can see here from the logs is that `hsm_client_x509_init()` is getting called which is suspect since you are using a SAS key. In the below screenshot, the red circle is the code path it looks to be taking instead of the green one. 

![image](https://user-images.githubusercontent.com/36710865/135527362-ce5a1ba8-c1ed-4fec-8a81-00903f6c2ae2.png)

[You should be able to select the SAS key auth option here and commenting out the line above it for `_X509`.](https://github.com/Azure/azure-iot-sdk-c/blob/d1a663b8710893e95bc8421470aee03aa565a550/provisioning_client/samples/prov_dev_client_ll_sample/prov_dev_client_ll_sample.c#L159)

Please let us know if that helps!

**Comment by ademyankov** [comment]
> you posted the SAS key and hub name for the device.

Oh! Don't worry :) those are free test account. And as soon as I posted the question I regenerated the keys. ;)

Thanks for the answer, I will try to do it and let you know...

**Comment by ademyankov** [comment]
Thanks, @danewalton! I was able to run the PNP demo. All seems fine except one tiny thing. The telemetry does not work in IoT Explorer. Couldn't figure out why. But it's not a big deal for me.

Thank you for your help.
