### ISSUE TITLE
iothub_service_client: High CPU load using ScheduleWork_Thread/ThreadAPI_Sleep

### ISSUE THREAD

**Issue by Styne13** [Azure/azure-iot-sdk-c#2253]
Hi,

we are experiencing high CPU load on our embedded device operating iothub_client (close to the iothub_client without LL functions) and tracing points out the client operates in 1ms cycles.

For us it looks like it is a result of calling the ThreadAPI_Sleep every 1ms in ScheduleWork_Thread in iothub_messaging.c and this has already been discussed in #126

Would it be valid to increase the sleep e.g. to 10ms or is there another option to decrease CPU load? We are using cloud2device and device2cloud messaging.

BR

Marcel

**Comment by danewalton** [comment]
Hi @Styne13 
I want to first be absolutely clear: the iothub_service_client is deprecated and won't be updated. With that, I'll try and see what we can help with here.

That seems reasonable. We usually allow the value to be between 1 and 100 ms in the iothub client as an option. [You can see that being used here](https://github.com/Azure/azure-iot-sdk-c/blob/9a5c9ca96dc17e28ac8cb8f0aeb3a2913da30b73/iothub_client/src/iothub_client_core.c#L821-L839).

**Comment by Styne13** [comment]
Hi @danewalton ,
thank you for your quick response.

You are right and I pointed to the wrong client: We are using the iothub_client (corrected that in my first post now) and adapting DO_WORK_FREQ_DEFAULT to 20ms decreased cpu load significantly for us.
Think you can close the question.

BR

Marcel

**Comment by brendanrempel** [comment]
Quick question: why does this code have to poll? I assume if this is about device2cloud, it should be able to sleep indefinitely and wake up when telemetry is queued. For cloud2device, is there a way to wake up on network event?

I'm asking because without any messages to/from the hub, my service is one of the highest consumers of CPU, behind only Edge. I'd prefer to see my service as one of the most efficient in the stack.
