### ISSUE TITLE
Connection Not Accepted: 0x5: Not Authorized in device with mips processor DPS

### ISSUE THREAD

**Issue by Karolis1661** [Azure/azure-iot-sdk-c#2255]
Hello,
Got many devices with arm and mips processors. When trying to register device in dps with individual enrollment and  x509 leaf certificate, every device with arm processor works fine, but when trying to register mips device, it fails - "mqtt_operation_complete_callback: Connection Not Accepted: 0x5: Not Authorized"
Same procedure for every device. Cant find any clues why this failing for mips architecture. Sdk for C language, build is exact same for all devices. 

Update: seems like device with mips architecture can't extract common name from certificate, or fails somewhere in this context.

**Comment by momuno** [comment]
@Karolis1661 Can you please provide more information, such as the tls client you are using, a callstack, or a wireshark trace?Thanks.

**Comment by Karolis1661** [comment]
Sdk is compiled for linux devices, with openssl.
I've been testing according to prov_dev_client_sample.c with default settings. The function "register_device_callback" in client_sample file on mips architecture gives iothub_uri and device_id as NULL. On arm it sets as valid values.

Errors i get 
"Func:mqtt_operation_complete_callback Line:205 Connection Not Accepted: 0x5: Not Authorized"
"prov_transport_mqtt_common.c Func:mqtt_error_callback Line:136 MQTT communication error"
"prov_device_ll_client.c Func:on_transport_registration_data Line:552 Failure retrieving data from the provisioning service"

Is there anything more additional that i should check as Dane mentioned "mbedtls" for device architecture? Atm everything is equal, certificate, sdk build etc..

**Comment by danewalton** [comment]
I can say that sometimes it has to do with the time functionality on the device. If the time is off, it won't authorize the connection. Are you able to get a Wireshark trace at all? Post full logs with the following option enabled:

https://github.com/Azure/azure-iot-sdk-c/blob/9a5c9ca96dc17e28ac8cb8f0aeb3a2913da30b73/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L124-L125

**Comment by ericwol-msft** [comment]
I suspect the client cert is not correct on the TLS session. Can you capture a wireshark trace on the connection?

**Comment by ericwol-msft** [comment]
From the DPS logs the error is:

`    Microsoft.Azure.Devices.Registration.Bond.RegistrationServiceException: Invalid certificate, client and enrollment certificate mismatch.`

You would need a wireshark capture to see what client cert you are presenting in the client TLS HELLO connection.

**Comment by Karolis1661** [comment]
I've tried to capture tls handshake. Tested with 3 devices, 2 arm architecture 1 mips and one certificate. For both arm devices certificate hash and hex representation is equal, for mips it was different. I've only received 3 packets for mips - 
![image](https://user-images.githubusercontent.com/67113855/158165121-7b864ad1-a220-4520-b82a-511e04dd6e6f.png)

Altought info such as organization name, country name, common name is same for all devivces. 
Differences - 
Mips: 
![image](https://user-images.githubusercontent.com/67113855/158166493-18be4567-4514-4533-b3d4-c9c36fe5c601.png)

Arm: 
![image](https://user-images.githubusercontent.com/67113855/158166580-2af6f3dc-d517-4b8e-80ab-104b6b4934f3.png)


Mips has one byte more than arm for certificates, 
so hash differs by 1 value: 

Mips: Certificate: 3082018**6**3082012ba00302010202050e0d0c0b0a300a0608… (id-at-organizationName=MSR_TEST,id-at-countryName=US,id-at-commonName=riot-signer-core)

Arm: Certificate: 3082018**5**3082012ba00302010202050e0d0c0b0a300a0608… (id-at-organizationName=MSR_TEST,id-at-countryName=US,id-at-commonName=riot-signer-core)

**Comment by momuno** [comment]
Can you see what the differing byte is?  Can you try saving the correct certificate to the mips device?

**Comment by momuno** [comment]
Can you see what the differing byte is?  Please try saving the correct certificate to the mips device.

**Comment by CIPop** [comment]
If you are not planning to use Microsoft DICE/RIOT as your HSM and instead want to use your own certificates, please see our new feature https://github.com/Azure/azure-iot-sdk-c/tree/main/provisioning_client/samples/prov_dev_client_ll_x509_sample

If you do use DICE/RIOT, the system will generate different certificates on each authentication (the Alias certificate). You may want to expand the entire structure, export it to a text file and diff between MIPS and ARM at that level. (The single byte difference you are seeing is likely due to the difference in Certificate TLS record length - 394 vs 393)

**Comment by Karolis1661** [comment]
"**Please try using the correct certificate on the mips device"**: what is correct certificate? I wasn't able to find any info about certificate depends on architecture, microsoft azure provides global certificate creation tutorial. So if it works on arms, but not on mips, how can i distinguish certificate creation procedure?

Also for both arm devices, which started from clear session certificate encryption values is the same, and only in mips device the values differs. Can this be that somehow the extra byte in mips changes certificate hash and it gets rejected on the server?

**Comment by CIPop** [comment]
>  So if it works on arms, but not on mips, how can i distinguish certificate creation procedure?

If you use the same certificate on ARM and MIPS it should work as you point out.
Please try to use openssl s_client to verify both your TLS stack and your X509 certificates are correct, on both ARM and the MIPS machine outside of our SDK:

Example:
`​openssl s_client -connect <yourhub>.azure-devices.net:8883 -cert ~/test/dev1-ecc_cert.pem -key ~/test/dev1-ecc_key.pem`

In both cases, our service should allow the connection and OpenSSL should not exit (use Ctrl+C to exit). If this is working on ARM but not on MIPS, please post the logs (you may want to remove your hub URI and other private information).

> Can this be that somehow the extra byte in mips changes certificate hash and it gets rejected?

It appears that you are trying to use DPS + the RIOT HSM (which is what hsm_x509 was defaulting to in previous versions and our LTS branches). We've made substantial recent changes to how DPS and X509 certificates work in https://github.com/Azure/azure-iot-sdk-c/pull/2229. 
[RIOT](https://www.microsoft.com/en-us/research/project/dice-device-identifier-composition-engine/?msclkid=c3930b5ca54711ec885b207b7cc7af3a) is a low-level hardware-security module system for embedded devices that is not meant to be used on Linux. 

The RIOT simulator uses hardcoded ECC keys and mbedTLS internally to generate an Alias certificate at runtime. I don't believe we've tested the simulator on MIPS.

Since your goal is to use OpenSSL, I recommend you use our latest C-SDK version and switch to the https://github.com/Azure/azure-iot-sdk-c/tree/main/provisioning_client/samples/prov_dev_client_ll_x509_sample sample instead. The usage is a lot simpler (similar to how the IoTHub device client configures certificates), and has OpenSSL Engine support.

**Comment by Karolis1661** [comment]
Thank you for your answer, i'l consider updating to new samples for openssl support. Outside of sdk openssl command seems to be working fine when making connection for both devices. Closing this issue.

**Comment by CIPop** [comment]
Thank you @Karolis1661! Please open a new issue if the new DPS X509 feature doesn't work for you.
