### ISSUE TITLE
How to access Device Connection String without hardcoding it?

### ISSUE THREAD

**Issue by TheAifam5** [Azure/azure-iot-sdk-c#2275]
Hey,

I'm searching for a solution to somehow get the IoTHubClient without ever storing the connection string in the source code. The idea is that the device connects to the IoT Hub and initially updates the device twin etc. Pretty much every sample I've seen requires to hard code the device connection string. Maybe provisioning would be a solution? (I need the connection all the time, after reboot, after module update...).

Or maybe differently, how can I update the device twin without storing the connection string in the source code? :D

Best regards,
TheAifam5

**Comment by danewalton** [comment]
Not hardcoding credentials leaves you with options which will store the credentials effectively "behind a wall". With a large windows or linux machine that can be a certificate store. With embedded systems, that usually ends up being a hardware layer, otherwise known by several names like hardware secure module (or HSM), secure element, or TPM. (Links [here](https://cerberus-laboratories.com/blog/iot_hsms/) and [here](https://www.wolfssl.com/difference-hsm-tpm-secure-enclave-secure-element-hardware-root-trust/) for some docs). With this SDK, we have support for OpenSSL engines which will offload things like private keys behind that kind of abstraction, where private keys are effectively links within another module ([link here for an example](https://github.com/Azure/azure-iot-sdk-c/blob/9a5c9ca96dc17e28ac8cb8f0aeb3a2913da30b73/provisioning_client/samples/prov_dev_client_ll_x509_sample/prov_dev_client_ll_x509_sample.c#L56-L58)).

With SAS keys it is possible to store the keys in a similar element and then feed it into the SDK. But that might be more cumbersome than using something like x509 certificates.

**Comment by ericwol-msft** [comment]
The ideal solution is to use client side TLS certificates and not SAS tokens. These certs can be stored in your cert store or on your wifi module if supported. What platform is this on?

**Comment by danewalton** [comment]
I'm going to go ahead and close this for now. If you need additional help or would like it reopened please let us know.
