### ISSUE TITLE
Are C2D messages received spontaneously?

### ISSUE THREAD

**Issue by dangerousHobo** [Azure/azure-iot-sdk-c#2280]
Hello,

I'm attempting to add support for C2D messages to my existing app. I've been following the sample here:
https://github.com/Azure/azure-iot-sdk-c/blob/main/iothub_client/samples/iothub_convenience_sample/iothub_convenience_sample.c

My app currently launches two threads from `main()` using `ThreadAPI_Create()`. One handles the device-twin, while the other handles telemetry. From `main()` I call `IoTHubDeviceClient_SetMessageCallback()` for my callback to handle C2D messages.

I can send a C2D message using either the IoT Hub portal or the `az` cli tool. I eventually get the message but I noticed it's only when the one child thread handling device-twins run (it sleeps and run every 2 minutes). I'm using the convenience API, so I'm not controlling the `DoWork` thread. I was expecting my C2D callback to be called whenever a new message is sent but it seems the message isn't received till my device-twin thread awakes and requests the device-twin from the cloud that the C2D callback is ran.

Is this expected behavior? If not, any suggestions on what I could look at further?

Thanks.

**Comment by ewertons** [comment]
Hi @dangerousHobo ,

as you mentioned correctly, the convenience API launches a separate/dedicated thread to run `IoTHubClientCore_LL_DoWork`.

First, of course, you create the client instance with, for example, `IoTHubDeviceClient_CreateFromConnectionString`.
At that point, the separate thread for DoWork is not yet created.
Only after you either subscribe to any messaging feature (C2D messages, Twin or Direct Methods) or if you actively send any message (Telemetry, Twin reported properties update, Get Twin request), the thread for DoWork is launched.
You can inspect all cases where the dedicated DoWork thread is launched by listing all calls to `StartWorkerThreadIfNeeded` in
https://github.com/Azure/azure-iot-sdk-c/blob/main/iothub_client/src/iothub_client_core.c

That is called underneath if you call `IoTHubDeviceClient_SetDeviceTwinCallback` and `IoTHubDeviceClient_SetDeviceTwinCallback`, for example.

Just to clarify, a call to either function will launch just one thread for DoWork. If one is already running, of course another will not be launched.

Now the main thing here could be locks and semaphores.
When a Twin or a C2D message is received, you get them in your application through a callback, which is being invoked by the same DoWork dedicated thread. The Azure IoT C SDK callbacks **MUST** be able to execute quickly and return, otherwise the DoWork thread gets stuck waiting, and no I/O nor any callback dispatching are performed.

First verify if you are allowing the callbacks to return freely. 
The fact of you spawning other threads to handle the incoming C2D and Twin (which I assume you are putting them in queues, which are properly protected by locks for your threads to safely write and read to/from) should not directly influence the DoWork thread, unless you have any locking preventing the callbacks to return.

If you still have an issue, we might need to see your code to understand what could be going wrong.
Also, make sure you share what version of the SDK you are using.

Thanks,
Azure IoT SDK Team

**Comment by ewertons** [comment]
Hi @dangerousHobo , we will close this issue for now, but please feel free to reopen it or file a new one if you would like to follow up.
Thanks,
Azure IoT SDK Team
