### ISSUE TITLE
iothub_ll_client_x509_sample doesn't work with error on Func:_decode_crypt_object

### ISSUE THREAD

**Issue by lutoepfer** [Azure/azure-iot-sdk-c#2302]
- **OS and MS VS version used:** Windows 10 & Microsoft Visual Studio Professional 2017
- **SDK version used:** LTS_01_2022_Ref01

# Description of the issue:

I build the SDK via cmake:

git clone -b <release-tag> https://github.com/Azure/azure-iot-sdk-c.git
cd azure-iot-sdk-c
git submodule update --init

mkdir cmake
cd cmake

cmake -Duse_prov_client:BOOL=ON .. 

I followed the procedure to create certitificates from link below.
https://github.com/Azure/azure-iot-sdk-c/blob/main/tools/CACertificates/CACertificateOverview.md

After that i edited the following variables from the sample connectionString ,x509certificate with content from ...-public.pem and 
x509privatekey with content from ...-private.pem

When I run iothub_ll_client_x509_sample, it fails at x509_schannel.c Func:_decode_crypt_object.

Here's the full error messages.
Error: Time:Tue May 17 08:34:17 2022 File:D:\Projekte\vcpkg\buildtrees\azure-c-shared-utility\src\38163cefc7-e51409bfe4.clean\adapters\x509_schannel.c Func:_decode_crypt_object Line:101 Failed to CryptDecodeObjectEx x509 private key

Thanks for your help. 
# Console log of Issue:

Creating IoTHub handle
Error: Time:Tue May 17 08:34:17 2022 File:D:\Projekte\vcpkg\buildtrees\azure-c-shared-utility\src\38163cefc7-e51409bfe4.clean\adapters\x509_schannel.c Func:_decode_crypt_object Line:101 Failed to CryptDecodeObjectEx x509 private key
Error: Time:Tue May 17 08:34:17 2022 File:D:\Projekte\azure-iot-sdk-c\c-utility\src\xlogging.c Func:_xlogging_LogErrorWinHTTPWithGetLastErrorAsStringFormatter Line:133 GetLastError: Bei der Codierung bzw. Decodierung ist ein Fehler aufgetreten.
.
Error: Time:Tue May 17 08:34:17 2022 File:D:\Projekte\vcpkg\buildtrees\azure-c-shared-utility\src\38163cefc7-e51409bfe4.clean\adapters\x509_schannel.c Func:_x509_schannel_create Line:371 Failure decoding x509 private key
Error: Time:Tue May 17 08:34:17 2022 File:D:\Projekte\vcpkg\buildtrees\azure-c-shared-utility\src\38163cefc7-e51409bfe4.clean\adapters\tlsio_schannel.c Func:_tlsio_schannel_setoption Line:1463 x509_schannel_create failed
Error: Time:Tue May 17 08:34:17 2022 File:D:\Projekte\azure-iot-sdk-c\iothub_client\src\iothub_client_core_ll.c Func:_IoTHubClientCore_LL_SetOption Line:2256 unable to IoTHubTransport_SetOption
failure to set options for x509, aborting
Press any key to continue

**Comment by CIPop** [comment]
@lutoepfer it's very likely you are using a certificate or key not supported by Windows SChannel. To check if your certificate can be opened by Windows, please rename the certificate file from .pem to .crt or .cer and open it in Windows Explorer (double-click the file to open it). Unfortunately, there is no easy way to test the key (which is the cause of your failure).

The PEM format is not actually supported by Windows. Our SDK works around this by _assuming_ the certificate/key is in the correct format: `X509_ASN_ENCODING | PKCS_7_ASN_ENCODING` (PKCS#1 or PKCS#7) and simply removing the incompatible PEM begin/end markers. 

From my experience, some OpenSSL versions will default to generate keys in PKCS#8 format which is not supported by Windows. To convert the key to PKCS#1, use:

```sh
openssl rsa -in private_pkcs8.pem -out private_pkcs1.pem
```

Another potential problem could be the text-file format and line terminations:
1. The SDK also assumes correct Windows terminations (CR, LF) instead of (LF only).
2. Anything outside of a Base64 blob between --begin--/--end-- statements will not work.
3. Password protected keys are not supported by our SDK.

**Comment by CIPop** [comment]
@lutoepfer please let me know if this answers your question or if you need this reopened.

**Comment by lutoepfer** [comment]
Hi @CIPop , 
thank you very much for the quick help. My question is completely answered.
