### ISSUE TITLE
missing branch: lts_08_2023

### ISSUE THREAD

**Issue by JanZachmann** [Azure/azure-iot-sdk-c#2517]
Hello
For the [latest release](https://github.com/Azure/azure-iot-sdk-c/releases/tag/LTS_08_2023) there exists only a tag but no branch. On the other hand the branch is mentioned in [docu](https://github.com/Azure/azure-iot-sdk-c/tree/main#lts-schedule)?

Furthermore the *_Ref0x prefix is missing this time. Why?

BR
Jan Zachmann

**Comment by RLeclair** [comment]
Hi @JanZachmann, thank you for your question. With a tag you can branch off from the LTS, do you have a specific reason why you need a LTS branch? 

Regardless, we've created a LTS [branch](https://github.com/Azure/azure-iot-sdk-c/tree/lts_08_2023)

We removed the Ref because LTS should only be named LTS with no addition, when we need to add a revision (because of a security issue for example) we will add a tag with the suffix appended to it.

**Comment by RLeclair** [comment]
Hi @JanZachmann no more information for the last 3 weeks so closing for now. Please feel free to add re-open the issue if needed.
