### ISSUE TITLE
OPTION_BATCHING documentation ( batching multiple messages )

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#255]
IoT Hub SDK docs([1](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/Iothub_sdk_options.md#http-tansport)) refers to OPTION_BATCHING. But there is no clear explanation on this option will do. 

1. Is it possible to document the option and its effects? Does it batch messages? If yes, what is window period?
2. Is this option limited to HTTP protocol?

**Comment by jspaith** [comment]
I'm researching HTTP and can get you an answer early next week (and we'll put all this into docs of course, not just here).  There's no time window but **I think** there's some side effects in terms of base64 encoding things it may not need to in some paths, but I have to dig a bit deeper.

AMQP also supports batching as of about Sept 2017 and it's on always.  It works as you'd expect - if you have 5 messages ready to be sent, they're sent in 1 AMQP message (assuming they fit into the max transmission size the link allows of course) instead of 5 individual messages which is friendly over the network.  AMQP can always be on since the overhead is quite low (only 5 bytes).  We don't do any sort of time windowing on it - i.e. I don't wait 200ms before sending a message to let more queue up.  

MQTT does not support batching.

**Comment by kiranpradeep** [comment]
@jspaith Thanks. But, if there is no windowing, how can you batch? If a message is put to the wire as early it arrives, how can you batch it the next message which is going to arrive 10ms later?

**Comment by jspaith** [comment]
Your concern is correct and something I've also pondered.  There's 2 factors in play - one is simplifying code to some extent (and waiting for someone to ask), the other is optimizing around lower level devices.

The IoTHub has 2 modes - the "convenience layer" and the LL (lower level) where it's single threaded, where the caller "manages" the scheduling.  This is especially important on constrained devices.

Iothub-client-Turn-on-batching
IoTHubClient_LL_SendEventAsync(message1)
IoTHubClient_LL_SendEventAsync(message2)
IoTHubClient_LL_DoWork() 

We only send the message on the DoWork() cranking through the pending queue, so in this case the caller can guarantee that batching will be enabled.

That said, if you have need for batching on convenience layer (where the queue happens on another thread, e.g. no "LL") then you can open a new GitHub request on requesting a new option for window-time.

**Comment by jspaith** [comment]
I've updated formal docs also, see ee3d9046.
