### ISSUE TITLE
SSL linking problem in Raspbian GNU/Linux 9 (stretch)

### ISSUE THREAD

**Issue by mcampos19cr** [Azure/azure-iot-sdk-c#265]
Hello,

I am using Raspbian GNU/Linux 9 (stretch), Release: 9.1.

I am using the latest version of a Azure IoT SDK for C (downloaded today).

I am trying to compile an example, which use the following libraries in the CMakeList.txt file:

  target_link_libraries(app wiringPi
                          serializer
                          iothub_client
                          iothub_client_mqtt_transport
                          umqtt
                          aziotsharedutil
                          ssl
                          crypto
                          curl
                          pthread
                          m
                          crypto)

But I am getting an error, it appears to happen in libaziotsharedutil and it is related to SSL versions during linking:

[ 33%] Building C object CMakeFiles/app.dir/main.c.o
[ 66%] Building C object CMakeFiles/app.dir/bme280.c.o
[100%] Linking C executable app
/usr/bin/ld: warning: libssl.so.1.0.2, needed by /usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/libcurl.so, may conflict with libssl.so.1.1
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/6/../../../libaziotsharedutil.a(tlsio_openssl.c.o): undefined reference to symbol 'SSL_load_error_strings@@OPENSSL_1.0.2d'
//usr/lib/arm-linux-gnueabihf/libssl.so.1.0.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

It seems the new distro has only SSL 1.1.0 libraries, so references to SSL 1.0.2 break.

Wonder if you can investigate the issue or provide a work around (maybe a way to reference SSL 1.0.2 libraries).

Regards,
Miguel

**Comment by markrad** [comment]
Hi @mcampos19cr 

I see the same issue when compiling on my RPi Stretch but, in my case, it does not cause the build to fail. I'm looking into this further.

_Mark Radbourne MSFT_

**Comment by alankroenlein** [comment]
I have the exact same error when going through an Azure training module through Microsoft.  Below are the messages I am getting when trying to deploy to my Raspberry Pi using ./deploy.sh.  Any help is appreciated, since I can't continue until this issue is resolved.  

alan@DESKTOP-T0B9QUD:/mnt/c/Users/AlanKroenlein/Documents/IoTDeviceFolderProjects/Mod1Lab4$ ./deploy.sh
Deploying to Pi
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
GNU
arm
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/AzureIoT
Scanning dependencies of target app
[ 33%] Building C object CMakeFiles/app.dir/main.c.o
[ 66%] Building C object CMakeFiles/app.dir/bme280.c.o
[100%] Linking C executable app
/usr/bin/ld: warning: libssl.so.1.0.2, needed by /usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/libcurl.so, may conflict with libssl.so.1.1
/usr/bin/ld: warning: libssl.so.1.0.2, needed by /usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/libcurl.so, may conflict with libssl.so.1.1
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/6/../../../libaziotsharedutil.a(tlsio_openssl.c.o): undefined reference to symbol 'SSL_load_error_strings@@OPENSSL_1.0.2d'
//usr/lib/arm-linux-gnueabihf/libssl.so.1.0.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/app.dir/build.make:120: recipe for target 'app' failed
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/app.dir/all' failed
make[2]: *** [app] Error 1
make[1]: *** [CMakeFiles/app.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
sudo: ./app: command not found

**Comment by markrad** [comment]
Hi @mcampos19cr, @alankroenlein,

I've researched this issue further and now have a circumvention. The problem is that libcurl requires OpenSSL shared objects version 1.0.2. This version of OpenSSL is installed by default when you install Stretch. However, when you prepare to compile the Azure IoT SDK for C (also for Python) you are required to install the package libssl-dev. This will install version 1.1. The CMake script that creates the make files to compile the SDK will search for the OpenSSL header file that contains the version number of the current OpenSSL development package. This is found in the file /usr/include/opensslv.h. In there you will see the preprocessor line:
```C
# define SHLIB_VERSION_NUMBER "1.1"
```
With this information, CMake will (correctly) direct the make files to link with libssl.so.1.1. This will generate the mismatched OpenSSL libraries issue that you are seeing. 

To circumvent this, you need to install an older version of the OpenSSL development package. Unintuitively this is not packaged as a different version of the libssl-dev package but has been given its own unique package name which is libssl1.0-dev. 

If you have already installed libssl-dev then you will need to remove it first with the command
```
sudo apt-get purge libssl-dev
```
Now install the older version of the OpenSSL development package with
```
sudo apt-get install libssl1.0-dev
```
After performing those steps you should be able to successfully build the Azure IoT SDK for C.

Thanks to the Raspberry Pi forums for assisting me with this: https://www.raspberrypi.org/forums/viewtopic.php?f=33&t=195750&p=1227270#p1224600

_Mark Radbourne MSFT_

**Comment by TomK7** [comment]
Hi Mark,

after I proceed your described solution steps I get the next problem. The execution of the make produces this error:
```
_pi@raspberryfruit:~/Mod1Lab4 $ make all
[ 33%] Linking C executable app
/usr/bin/ld: warning: libssl.so.1.0.2, needed by /usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/libcurl.so, may conflict with libssl.so.1.1
/usr/bin/ld: warning: libssl.so.1.0.2, needed by /usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/libcurl.so, may conflict with libssl.so.1.1
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/6/../../../libaziotsharedutil.a(tlsio_openssl.c.o): undefined reference to symbol 'SSL_load_error_strings@@OPENSSL_1.0.2d'
//usr/lib/arm-linux-gnueabihf/libssl.so.1.0.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/app.dir/build.make:120: die Regel für Ziel „app“ scheiterte
make[2]: *** [app] Fehler 1
CMakeFiles/Makefile2:67: die Regel für Ziel „CMakeFiles/app.dir/all“ scheiterte
make[1]: *** [CMakeFiles/app.dir/all] Fehler 2
Makefile:83: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2_
```

Do you have a solution for this problem? It seems that the Azure IoT SDK for C will also removed with the execution of
`sudo apt-get purge libssl-dev`

Best Regrds
Thomas

**Comment by markrad** [comment]
Hi @TomK7,

Are you using apt-get to acquire any parts of the Azure IoT SDK? That will likely not work. You will need to build the entire SDK from scratch including the sub modules. 

Also possible is that you used the setup script in the SDK. This will inadvertently reinstall the wrong version of OpenSSL. If you do that then follow the instructions above once again to get back to the correct version of OpenSSL.

_Mark Radbourne MSFT_

**Comment by walterdekok** [comment]
Hi Mark,

I've tried the instructions above but it still doesn't work.
Can you please explain to me how I can get the right version libssl combined with the Azure-sdk.
As you can imagine I'm a totaly new to this kind of stuff.... 

Best regards,
Walter

**Comment by markrad** [comment]
Hi @walterdekok, 

You will need to provide specifics for me to help you. What doesn't work?

_Mark Radbourne MSFT_

**Comment by walterdekok** [comment]
Hi Mark,

Thanks for getting back to me.

I'm havving the exact same problem as mcampos19cr.
I'm doing the Microsoft: DEV225x Developing IoT Solutions with Azure IoT
course and get this error:

-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/AzureIoT
[ 33%] Linking C executable app
/usr/bin/ld: warning: libssl.so.1.0.2, needed by
/usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/libcurl.so,
may conflict with libssl.so.1.1
/usr/bin/ld: warning: libssl.so.1.0.2, needed by
/usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/libcurl.so,
may conflict with libssl.so.1.1
/usr/bin/ld:
/usr/lib/gcc/arm-linux-gnueabihf/6/../../../libaziotsharedutil.a(tlsio_openssl.c.o):
undefined reference to symbol 'SSL_load_error_strings@@OPENSSL_1.0.2d'
//usr/lib/arm-linux-gnueabihf/libssl.so.1.0.2: error adding symbols: DSO
missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/app.dir/build.make:120: recipe for target 'app' failed
make[2]: *** [app] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/app.dir/all' failed
make[1]: *** [CMakeFiles/app.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I have replaced the ssl version with the older version as you suggested in
this thread but I must be doing something wrong because it still doesn't
work....

I might be instlling the SDK the wrong way, maybe you can tell me how that
must be done...

Best regards,
Walter


2018-05-04 1:31 GMT+02:00 Mark Radbourne <notifications@github.com>:

**Comment by markrad** [comment]
I'll look into this further and get back to you.

**Comment by rhawley26** [comment]
Walter,

I am doing the same course.

Just download "Jessie" 

https://downloads.raspberrypi.org/raspbian/images/raspbian-2017-07-05/2017-07-05-raspbian-jessie.zip

The examples work with that version.

**Comment by markrad** [comment]
Hi @rhawley26, @walterdekok,

Indeed @rhawley26 is correct. The course will run successfully on Jessie since that version of Raspbian does not have the OpenSSL dev conflict. 

Since this is just for educational purposes that might be the easyiest way to address this. If, however, you actually want to run the SDK on stretch then you will need to download the entire SDK. Do not apt-get any portions of the Azure IoT SDK. Build the entire SDK from source using my example above https://github.com/Azure/azure-iot-sdk-c/issues/265#issuecomment-339794097. 

_Mark Radbourne MSFT_
