### ISSUE TITLE
mqtt handle, retry policies and dual intentions

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#266]
- **OS and version used:** macOS 10.12 

- **SDK version used:** 1.1.25
<VERSION> 

# Description of the issue:

I create an Azure IoT Hub connection handle using MQTT transport. I am using the same handle for two purposes
1. Accept direct-method invocation from the cloud. I would still like my application to reconnect and receive messages from the cloud, even if we lost network connectivity for an hour or so.
2. Send heartbeat messages([1](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-identity-registry#device-heartbeat)) to cloud to let cloud that I am alive. I don't want SDK to retry sending these heartbeat messages if connectivity is lost for a while.

What retry policy should I use? The moment I set it to IOTHUB_CLIENT_RETRY_IMMEDIATE, the connection status is restored. But it keeps all messages in a buffer still network connectivity is restored and then send them.

I like to ignore failed messages. But connection reestablishment should happen so that cloud can invoke direct methods once network connectivity is restored.

**Comment by ewertons** [comment]
That cannot be done.
If there is a retry policy in place, the transport layer will attempt to send all messages previously queued.
The MQTT transport waits up to 1 minute for a Device-to-Cloud message (i.e., "event") to be sent (i.e., when an ACK is received from the Azure IoT Hub). Then, it retries sending it once, waiting another 1 minute. If the second attempt fails, the pending event is delivered back to the user through the callback provided.

These values (the wait time and number of retries) cannot be changed, they are hardcoded. Perhaps it can be suggested as an improvement if you would like.

Please see the code here for details:
https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransport_mqtt_common.c#L2512

**Comment by ewertons** [comment]
Now, the question is: why do you need to send these heartbeats yourself?
MQTT transport already sends a heartbeat to the hub itself.

**Comment by ewertons** [comment]
Hi @kiranpradeep ,
we will close this issue, but please feel free to reopen it if you need to and have chance to follow up on the topic.
Thanks,
Azure IoT SDK Team

**Comment by kiranpradeep** [comment]
@ewertons Sorry for late reply.

 Our server side code needed to know if the device is online or offline so as to raise alerts and workflows. Initially we were depending on `connectionState` field in device twin. But saw a specific recommendation from Microsoft to only use `connectionState` for development/debugging. Then we implemented the heartbeat pattern as suggested in Azure docs([1](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-identity-registry#device-heartbeat)).

As you said, `connectionState` could rely on MQTT heartbeat itself. Why did MS suggested to avoid using connectionState ?

**Comment by ewertons** [comment]
Sure @kiranpradeep , I am inquiring the team responsible to know why the property cannot be used.

**Comment by ewertons** [comment]
@kiranpradeep,
sorry but the writers of that article were out for a few weeks, but I got a reply back.
According to the writers of the document the reasoning for the comment is pretty much the same written there:
"A field indicating connection status: either Connected or Disconnected. This field represents the IoT Hub view of the device connection status. **Important: This field should be used only for development/debugging purposes. The connection state is updated only for devices using MQTT or AMQP. Also, it is based on protocol-level pings (MQTT pings, or AMQP pings), and it can have a maximum delay of only 5 minutes. For these reasons, there can be false positives, such as devices reported as connected but that are disconnected.**"

So  the concern is that there could be a delay between when a device gets disconnected and when that property gets updated. Since that delay could be misleading it was recommended that users should implement their own keep-alive mechanism to be sure.

**Comment by kiranpradeep** [comment]
@ewertons Is that a real concern? The lib user can decrease the MQTT ping interval to 60 seconds or any level appropriate. I cannot see any advantage in user sending keep-alives. Please advise if you feel other wise.

**Comment by ewertons** [comment]
Hi @kiranpradeep ,
sorry for the delay.

The concern from our side is real since we need to be conservative and not over-promise on the time it would take for the property to be updated on the service.

However, if your solution is resilient enough and don't need to detect disconnections right away you could consider not using the pings.

But that is a design decision you must make, and it will depend on how resilient your solution is supposed to be.

**Comment by ewertons** [comment]
Thanks for using the Azure IoT SDKs.
Please feel free to reopen this issue if you would like to follow up on this topic.
Thanks,
Azure IoT Team

**Comment by tameraw** [comment]
@kiranpradeep thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
