### ISSUE TITLE
Docs mention --skip-unittests which does not seem to exist

### ISSUE THREAD

**Issue by fschwarzer** [Azure/azure-iot-sdk-c#29]
The docs:
- doc/devbox_setup.md
- doc/SDK_cross_compile_example.md
mention the --skip-unittests option for the build.sh script but it does not seem to exist.

**Comment by olivierbloch** [comment]
Hi @fschwarzer 
Thanks for bringing this to our attention. We have indeed changed the option so that unit tests are not built and run by default. Now by default we don't run unit tests when the build script is ran, and if someone wants to run them, they can use the --run-unit-tests option.
I have just pushed a PR #35   fixing the docs.
