### ISSUE TITLE
DPS (Device Provisioning Service) without HSM

### ISSUE THREAD

**Issue by Patrik-Berglund** [Azure/azure-iot-sdk-c#307]
Hi,

Is it possible to use the DPS (Device Provisioning Service) in a secure way with a device without HSM?

Best Regards
Patrik Berglund

**Comment by jebrando** [comment]
Patrik,

Thanks for the question,  I just added a document describing how to create a custom HSM using the SDK (https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/devdoc/using_custom_hsm.md).  This doc describes how you would make a custom repo and connect to it using our SDK (through the magic of cmake).  Since this document just got updated a few days ago, let me know if you have any questions.

Jelani

**Comment by Patrik-Berglund** [comment]
Hi,

Thanks, we will look in to that documentation and come back to you if needed. 

BR
Patrik B
