### ISSUE TITLE
[Linux] Installation seems to be broken

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdk-c#31]
Hi,

I've used to compile and install the SDK in a specific location before using it into my project. But it seems that the installation process is broken at least on linux.

1 - Using ./build.sh --install-path-prefix install_folder --use-websockets
Nothings is installed, note that I can't event find the folder install_folder

2 - Trigger the build from cmake :  cmake ../azure-iot-sdk-c/ -DCMAKE_INSTALL_PREFIX=install_folder -Duse_wsio=ON
The only thing being installed is libwebsocket

```
> Install the project...
> -- Install configuration: ""
> -- Installing: /home/lmussier/workspace/build-sdk/install_folder/lib/pkgconfig/libwebsockets.pc
> -- Installing: /home/lmussier/workspace/build-sdk/install_folder/lib/libwebsockets.a
> -- Installing: /home/lmussier/workspace/build-sdk/install_folder/include/libwebsockets.h
> -- Installing: /home/lmussier/workspace/build-sdk/install_folder/include/lws_config.h
> -- Installing: /home/lmussier/workspace/build-sdk/install_folder/lib/libwebsockets.so.6
> -- Installing: /home/lmussier/workspace/build-sdk/install_folder/lib/libwebsockets.so
> -- Up-to-date: /home/lmussier/workspace/build-sdk/install_folder/include/libwebsockets.h
> -- Up-to-date: /home/lmussier/workspace/build-sdk/install_folder/include/lws_config.h
> -- Installing: /home/lmussier/workspace/build-sdk/install_folder/bin/libwebsockets-test-client
> -- Installing: /home/lmussier/workspace/build-sdk/install_folder/bin/libwebsockets-test-server
> -- Installing: /home/lmussier/workspace/build-sdk/install_folder/bin/libwebsockets-test-server-pthreads
> -- Installing: /home/lmussier/workspace/build-sdk/install_folder/bin/libwebsockets-test-server-extpoll
> -- Up-to-date: /home/lmussier/workspace/build-sdk/install_folder/bin/libwebsockets-test-client
> -- Installing: /home/lmussier/workspace/build-sdk/install_folder/bin/libwebsockets-test-fraggle
> -- Installing: /home/lmussier/workspace/build-sdk/install_folder/bin/libwebsockets-test-ping
> -- Installing: /home/lmussier/workspace/build-sdk/install_folder/bin/libwebsockets-test-echo
> -- Installing: /home/lmussier/workspace/build-sdk/install_folder/share/libwebsockets-test-server/favicon.ico
> -- Installing: /home/lmussier/workspace/build-sdk/install_folder/share/libwebsockets-test-server/leaf.jpg
> -- Installing: /home/lmussier/workspace/build-sdk/install_folder/share/libwebsockets-test-server/libwebsockets.org-logo.png
> -- Installing: /home/lmussier/workspace/build-sdk/install_folder/share/libwebsockets-test-server/test.html
> -- Installing: /home/lmussier/workspace/build-sdk/install_folder/share/libwebsockets-test-server/libwebsockets-test-server.key.pem
> -- Installing: /home/lmussier/workspace/build-sdk/install_folder/share/libwebsockets-test-server/libwebsockets-test-server.pem
> -- Installing: /home/lmussier/workspace/build-sdk/install_folder/lib/cmake/libwebsockets/LibwebsocketsConfig.cmake
> -- Installing: /home/lmussier/workspace/build-sdk/install_folder/lib/cmake/libwebsockets/LibwebsocketsConfigVersion.cmake

```

In the two cases we can read 

```
CMake Warning at CMakeLists.txt:238 (message):
  This package may only be installed when 'use_installed_dependencies' is ON

```
Could you explain how to build and install the SDK in a defined folder?
Thanks

**Comment by fschwarzer** [comment]
Not an sdk dev but have you read
https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#linux ?

I am asking because you are doing things a bit different than said there (cmake folder outside of project folder).
 
In general setting options in CMake works with the -D parameter. So your above command would look like this:

```
cmake ../azure-iot-sdk-c/ -DCMAKE_INSTALL_PREFIX=install_folder -Duse_wsio=ON -Duse_installed_dependencies=ON
```

Can you try it?
For me that does not work since then cmake is not able to find some config files. Do you see the same?

**Comment by damonbarry** [comment]
I reproduced this. @andrew-buckley, any thoughts?

**Comment by andrew-buckley** [comment]
Hi @fschwarzer and @lmussier, in order to install this SDK each of it's dependencies must also be installed on your machine. This is why for you, @fschwarzer it may have given you an error saying it couldn't find a package configuration file under the name azure_c_shared_utilityConfig.cmake. What it means is that it's searching your machine for this installed package and it cannot find it. 

You will have to individually install [azure-c-shared-utility](https://github.com/Azure/azure-c-shared-utility/), [umqtt](https://github.com/Azure/azure-umqtt-c/), [uamqp](https://github.com/Azure/azure-uamqp-c/). If you wish to run the tests, you will also need to install [azure-ctest](https://github.com/Azure/azure-ctest/), [azure-c-testrunner-switcher](https://github.com/Azure/azure-c-testrunnerswitcher/), and [umock-c](https://github.com/Azure/umock-c/).

**Comment by andrew-buckley** [comment]
Installation instructions should be on the man README pages of those repositories.

**Comment by andrew-buckley** [comment]
@lmussier, like @fschwarzer mentioned above you will have to pass the additional flag to your cmake command before attempting to install (`-Duse_installed_dependencies=ON`). Next, yes you will need to have each of the dependencies installed on your machine using cmake. 

> i.e clone / cmake /make install won't work.

The above should work so long as you make sure to pass the flag `-Duse_installed_dependencies=ON`, and have the dependencies installed. The flow is this:

1. Clone the sdk and dependencies
2. Navigate to the dependencies and cmake install them
3. Go to your top-level build folder and run `cmake -Duse_installed_dependencies=ON <any other flags> <path to root>`

We do not plan to go back to the previous install mechanism as it was incorrect (even though it ended up working). The way it works now is all dependencies need to be on the machine in order to install the SDK.

You may use the `CMAKE_INSTALL_PREFIX` flag when you install the dependencies or the top-level sdk, but you'll have to be careful to also set the `CMAKE_PREFIX_PATH` for any installation that depends on packages that are installed in non-standard locations. The `CMAKE_PREFIX_PATH` is an additional location for CMake to search for installed packages.

Hope this helps.
Thanks,
-Andrew

**Comment by lmussier** [comment]
@andrew-buckley Thanks for the 'how to'.
