### ISSUE TITLE
Logging the connectivity in the IoT HUb

### ISSUE THREAD

**Issue by 59985** [Azure/azure-iot-sdk-c#311]
Hi there! 

I am tryring to implement the SDK in an embedded device. It seem like the SSL connection is working so that should be ok. I am using the "Iothub_client_sample_http", but with no luck. My problem is that I don't have any logging to see what is going when I am trying to the Iot Hub . I Azure you can only log what is going on after the device is connected as far as I know. 

So my question is. Do anybody know a tool for logging in the iot hub? 

/Kasper

**Comment by 59985** [comment]
Actually is seems like my problem could be related to this issue. https://github.com/Azure/azure-iot-sdk-c/issues/278

**Comment by ewertons** [comment]
Hi @59985 ,
no your issue is that you are not enabling verbose logging, correct?
How is that related to #278?

To assist you on that, could you give some basic details of the system you are using?
What is the OS you are using? And version of the C SDK?
Are you looking for a way to see the HTTP traffic?

**Comment by ewertons** [comment]
Hi @59985 ,
please let us know once you have more details to share. 
We will close this issue for now, but please feel free to reopen it once you have the details above. Thanks.
