### ISSUE TITLE
Bob_UploadFromSasUri Timeout Value

### ISSUE THREAD

**Issue by MichaelDenczek** [Azure/azure-iot-sdk-c#323]
- **OS and version used:** Windows 7 x64
- **SDK version used:** Latest SDK

# Description of the issue:
Cannot find way to set timeout value.  Need way to recognize network connectivity loss and return from HTTPAPIEX_ExecuteRequet.

The Bob_UploadFromSasUri method from blob.c is being used to upload files to blob storage.  The default timeout is very long and a way to set the timeout to a lower value in order to response to loss of network connectivity in a timely manner is needed.  Unsuccessfully tried using the HTTPAPIEX_SetOption method using the OPTION_MESSAGE_TIMEOUT, OPTION_C2D_KEEP_ALIVE_FREQ_SECS, and OPTION_CBS_REQUEST_TIMEOUT options.

**Comment by ewertons** [comment]
Hi @MichaelDenczek ,
the root cause of this issue is related to https://github.com/Azure/azure-iot-sdk-c/issues/188
At this time there is no timeout. 
We will work on exposing it once we get to this work item.
Although the fix is not so straightforward (it is related to at least 2 layers in the solution), please feel free to submit a PR if you need the fix earlier.

As a workaround, have you explored the new API [IoTHubClient_UploadMultipleBlocksToBlobAsync](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/inc/iothub_client.h#L362) ?
It breaks an upload in smaller chunks, and might give you more control of when you want to stop an upload (it doesn't address you request directly, but checking anyway in case it mitigates the issue for you).

**Comment by MichaelDenczek** [comment]
Unfortunately, I need to stop file uploads when the network connection is broken.  Will attempt to submit a PR...

**Comment by MichaelDenczek** [comment]
Is there a way to force the call to HTTPAPIEX_ExecuteRequest to return if a different thread detects the network connectivity loss?  Can a call be made on the different thread that would result in an immediate return from the HTTPAPIEX_ExecuteRequest call?

**Comment by MichaelDenczek** [comment]
A valid work-around is to set the CURLOPT_LOW_SPEED_LIMIT and CURLOPT_LOW_SPEED_TIME options via the HTTPAPIEX_SetOption method, since they do get processed correctly by the curl implementation.
