### ISSUE TITLE
iothub_messaging_sample.c 

### ISSUE THREAD

**Issue by Purnanandj** [Azure/azure-iot-sdk-c#334]
Logs are like as following:
iotHubServiceClientHandle has been created successfully
Creating Messaging...
Messaging has been created successfully
Opening Messaging...
IoTHubMessaging_LL_Send accepted data for transmission to IoT Hub.

In sendCompleteCallback function it is failing 
Send failed

**Comment by jspaith** [comment]
Hi @Purnanandj .  We need some more information to debug this, namely:
* Which OS are you doing this on?
* The code that you're using - is it a modified sample adding your connection strings, or if not could you give us some snippets.
* The logs themselves.

Thanks

**Comment by Purnanandj** [comment]
Hi @jspaith . Thank you for answering.

- I am working on Yocto based Embedded Linux

- The Code that i am using is with the connection string generated from Azure Cloud Package in Azure portal.

- Coming To logs, they are as it is in above question. But Strangely i get such kind of Issue after Transmitting 50 Messages to cloud and on the other end no one is there to download the message. And from the 51st message the problem comes as Send Failed.

**Comment by jspaith** [comment]
If you checkout https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-c2d, "Each device queue holds at most 50 cloud-to-device messages. Trying to send more messages to the same device results in an error".

Pretty sure you're hitting this error.  I played around with sample and saw same behavior, but if I had a client listening and consuming the messages as they arrive then everything worked fine.

For iothub_messaging_ll_sample.c sample and if you're sending >50 messages, it may help for your testing if after the final * IoTHubMessage_Destroy(messageHandle);* you add something like

```c
    printf("Beging DoWork...\n");
    IoTHubMessaging_LL_DoWork(iotHubMessagingHandle);
    printf("Completed DoWork...\n");
    ThreadAPI_Sleep(100);
```

When you call `IoTHubMessaging_LL_Send`, the message is queued to be sent at client level but you need to call the `IoTHubMessaging_LL_DoWork` to manually drain out the queue.  By adding my lines above to the loop, instead of getting 100 messages all showing up at IOTHub in the (existing) final `IoTHubMessaging_LL_DoWork` call, you send a message and then push it up to Cloud.

If you don't want to mess with the `IoTHubMessaging_LL_DoWork` and you have a device where you're OK with a worker thread, you can look into `IoTHubMessaging_SendAsync` which spins up a worker thread that is sending up the data in background without your thread needing to explicitly invoke `IoTHubMessaging_LL_DoWork`.

**Comment by jspaith** [comment]
Feel free to re-open (or open new issue) if you need further guidance here or this doesn't address issue.
