### ISSUE TITLE
[CA Certificate Sample] Exception while creating the device

### ISSUE THREAD

**Issue by surabhshah** [Azure/azure-iot-sdk-c#370]
- **OS and version used:** <VERSION> 
Windows 10, Build 16299.192
- **SDK version used:** <VERSION> 
.NET Core SDK 2.1.2

# Description of the issue:
Hello,

I was trying out Device Provisioning Service with certificate based authentication and had to create CA based certificates for the same. While creating the certificates, I landed into an exception on 3rd (would take it as a different issue) and 4th step where the issue seems to be similar. 
I have attached a screen showing the issue below.

![dps_cert_error_1](https://user-images.githubusercontent.com/8298707/35682837-1733fbd6-0788-11e8-89ae-2db9f98318c0.PNG)

# Code sample exhibiting the issue:

# Console log of the issue:

PS D:\DPS_certs> New-CACertsDevice myDevice
WARNING: Generating certificate CN=myDevice which is for prototyping, NOT PRODUCTION.  It has a hard-coded password and will expire in 30 days.
New-SelfSignedCertificate : Cannot convert 'System.Object[]' to the type 'Microsoft.CertificateServices.Commands.Certificate' required by parameter 'Signer'. Specified method is not supported.
At D:\Azure IOT SDK\azure-iot-sdk-c\tools\CACertificates\ca-certs.ps1:86 char:38
    write (New-SelfSignedCertificate @selfSignedArgs)
                                      ~~~~~~~~~~~~~~~
 CategoryInfo          : InvalidArgument: (:) [New-SelfSignedCertificate], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CannotConvertArgument,Microsoft.CertificateServices.Commands.NewSelfSignedCertificateCommand

Thanks in advance,
Surabh

**Comment by jspaith** [comment]
The problem here sounds like you already have multiple certs with the same CA name installed in your cert store.  I have a fix for a better error message already queued in https://github.com/Azure/azure-iot-sdk-c/tree/cert-tool-extra-checking to prevent you from being able to get yourself into this state.

Everytime you start this process of creating a new root cert you should start with a `Test-CACertsPrerequisites`, and the fix enforces this, but i've added extra check as error is hit enough and non-intuitive.

Closing out since i'm like 98% sure this is the problem but reopen by all means if i'm wrong.
