### ISSUE TITLE
Semicolons after macros cause errors when compiling with '-pedantic'

### ISSUE THREAD

**Issue by schmidt-daniel** [Azure/azure-iot-sdk-c#381]
- **OS and version used:** Debian Linux 9.2 

- **SDK version used:** commit a7e59fdfe64f5f4cb6ede89f8b91a82ca8a7dbbf (Feb 12, 2018) 

# Description of the issue:
When compiling an IoT SDK project with the '-pedantic' flag, "error: extra ‘;’" will be reported.

# Code sample exhibiting the issue:
azure-iot-sdk-c/iothub_client/inc/iothub_client_ll.h:46
```
DEFINE_ENUM(IOTHUB_CLIENT_RESULT,(url) IOTHUB_CLIENT_RESULT_VALUES);
```

azure-c-shared-utility/blob/master/tools/macro_utils_h_generator/macro_utils.tt:306
```
#define DEFINE_ENUM(enumName, ...) typedef enum C2(enumName, _TAG) { FOR_EACH_1(DEFINE_ENUMERATION_CONSTANT, __VA_ARGS__)} enumName; \
    extern const char* C2(enumName,Strings)(enumName value); \
extern int C2(enumName, _FromString)(const char* enumAsString, enumName* destination);
```

Having a semicolon at the end of the macro definition as well as having one when expanding it results in a double semicolon.

# Console log of the issue:

e.g.
```
In file included from /usr/local/include/azureiot/iothubtransport.h:13:0,
                                      from /usr/local/include/azureiot/iothub_client.h:23,
                                     from ../../../git/atom/tools/TestApp.cc:68:
/usr/local/include/azureiot/iothub_client_ll.h:46:63: error: extra ‘;’ [-Werror=pedantic]
                                   DEFINE_ENUM(IOTHUB_CLIENT_RESULT, IOTHUB_CLIENT_RESULT_VALUES);
```

**Comment by ewertons** [comment]
Hi @schmidt-daniel ,
Thanks for bringing this up.
We see that the code would not behave as expected if building with pedantic mode on, however the SDK never commit to have that supported.
At this point we would not have capacity available to make that improvement ourselves, but upon discussing the issue we decided it would be ok to have that change if you would like to submit a pull request.
Notice that changing the macro definition would not be a good move, since that would break any customers currently using such macros. So any fixes for the pedantic flag to work would need to be on the calls to such macros across the SDK code. If you would like to submit a PR, we would review it ASAP.

Thanks,
Azure IoT Team

**Comment by jspaith** [comment]
In addition to what Ewerton called out, we build with warnings as errors on both Visual Studio (w4, which is the max) and for gcc we set "-Werror".  We do take warnings seriously, if not to the pedantic level.

**Comment by ewertons** [comment]
Hi @schmidt-daniel ,
we will close this issue but please feel free to reopen it if you have any further comments or would like to follow up with a discussion for a PR.
Thanks,
Azure IoT Team.
