### ISSUE TITLE
MQTT over WebSockets send-timeout (using CURL)

### ISSUE THREAD

**Issue by pboettch** [Azure/azure-iot-sdk-c#385]
- **OS and version used:** Debian Testing amd64

- **SDK version used:** 2018-01-29

# Description of the issue:
I'm implementing an IoTHub-client using the LL-API to send messages and receive direct-method-calls. I'm creating my connection with the `MQTT_WebSocket_Protocol`.
Right now I'm testing the behavior when a connection is lost, comes back and so on.

These are the steps I'm undertaking:

- calling `IoTHubClient_LL_CreateFromConnectionString()`
- setting my callbacks `IoTHubClient_LL_SetMessageCallback`, `IoTHubClient_LL_SetDeviceMethodCallback_Ex` and `IoTHubClient_LL_SetConnectionStatusCallback`
- starting the thread which runs `IoTHubClient_LL_DoWork()` with an interval of 50msecs.
- Waiting for `IOTHUB_CLIENT_CONNECTION_AUTHENTICATED` with the `IOTHUB_CLIENT_CONNECTION_OK` reason.

Then I disconnect the network and try to send a message via `IoTHubClient_LL_SendEventAsync()`.

The SendAsync call is successfully returning. In my DoWork-thread I see that the SendStatus is now `IOTHUB_CLIENT_SEND_STATUS_BUSY`. I can't send the message. Only after quite exactly 2 minutes the message-callback is called.

_Here's my question_: how can reduce this timeout in my setup?

I tried 
```C
ret = IoTHubClient_LL_SetOption(iotHubClientHandle_, "timeout", &timeout);
```
I'm getting an error (contrary to the documentation):

```
Error: Time:Sun Feb 25 22:19:36 2018 File:/home/pmp/devel/ett/emc2-router/external/azure/azure-iot-sdk-c/c-utility/src/uws_client.c Func:uws_client_set_option Line:1867 xio_setoption failed.
Error: Time:Sun Feb 25 22:19:36 2018 File:/home/pmp/devel/ett/emc2-router/external/azure/azure-iot-sdk-c/c-utility/src/wsio.c Func:wsio_setoption Line:687 Setting the option timeout failed
Error: Time:Sun Feb 25 22:19:36 2018 File:/home/pmp/devel/ett/emc2-router/external/azure/azure-iot-sdk-c/iothub_client/src/iothub_client_ll.c Func:IoTHubClient_LL_SetOption Line:1783 underlying transport failed, returned = IOTHUB_CLIENT_INVALID_ARG
```

I tried 
```C
tickcounter_ms_t timeout_msg = 10000; 
ret = IoTHubClient_LL_SetOption(iotHubClientHandle_, "messageTimeout", &timeout_msg);
```
No error is returned, but my problem persists.

**Comment by ewertons** [comment]
Hi @pboettch ,

The azure-iot-sdk-c has roughly speaking 3 layers. 
1. An upper layer client, threaded.
2. A non-threaded client (with APIs containing _LL_ in their name; this layer is used by the above).
3. A layer that translates the client I/Os to/from the specific protocol you are using (aka transport layer).

The option "messageTimeout" applies only to layers 2 and 3 above. As soon as _DoWork() runs, the pending messages are transferred from the client layers to the transport layer, so the option loses its effect. That is a design we will refine in the future, we apologize for that.

However, upon disconnection you should get callbacks with the failures sending messages.

To reduce the time the transport layer takes to consider the connection as broken, you can set this option:

```
int timeout_connection_secs = 60; 
ret = IoTHubClient_LL_SetOption(iotHubClientHandle_, OPTION_CONNECTION_TIMEOUT, &timeout_connection_secs);
```

See https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransport_mqtt_common.c#L2684

The result you saw from _GetSendStatus() function is expected. It will return IDLE if no messages are pending to be sent (i.e., messages that were sent but you didn't get the completion callback invoked for), and BUSY otherwise.

**Comment by ewertons** [comment]
Please feel free to reopen the issue if you would like to follow up.
Thanks,
Azure IoT Team
