### ISSUE TITLE
Create a 5 minute quick start

### ISSUE THREAD

**Issue by idavis** [Azure/azure-iot-sdk-c#401]
- **OS and version used:** <VERSION> 
ALL
- **SDK version used:** <VERSION> 
ALL

# Description of the issue:

Getting up and going with the SDK takes a long time. A five minute quick start would lower the barrier to entry and help get people excited to use the SDK.

**Comment by yzhong94** [comment]
This is part of our MVC plan.

**Comment by samanaz** [comment]
yzhong94 what do you mean by that?

I am a beginner and I would like to find a simple instruction to cross compile between windows (Visual Studio 2017) and Raspberry but there is no good instructions outside at all. It has been more than four weeks that I even could not run a simple demo.

Thanks to Microsoft there is no Tutorial about that. Not on Microsoft Virtual Academy. Not on Linda which is purchased by Microsoft. Not on on Channel 9. Not on Linkedin Academy which is the new version of Linda.

I am not sure why Microsoft needs so many teaching channels and on none of them there is tutorial about it.

**Comment by markrad** [comment]
Hi @samanaz,

I'm not sure if cross compiling the Azure IoT SDK for any Linux based system is viable with Windows and Visual Studio. It may be possible but I have not tried it. The document that @yzhong94 indicated in her above comment will require that you use Linux to cross compile. If you don't have a LInux environment available then you can install one in a Hyper-V machine or any other virtual machine host. You might also be able to cross compile in the Linux subsystem for Windows. I have done this successfully on occasion. See [here](https://docs.microsoft.com/en-us/windows/wsl/install-win10) for further information.

Another alternative available to you is to use a docker image. I recently posted a dockerfile that cross compiles our SDK along with all of the prerequisite components for a MIPS32 based device. You can find this here: https://github.com/Azure/azure-iot-sdk-c/issues/484#issuecomment-394497509.  In general though, you will not need to cross compile OpenSSL, curl or uuid for the Raspberry Pi because you can acquire those binaries from the device itself as shown in the referenced article.

One question though, what operating system are you running on your Raspberry Pi? My comments assume you are running Raspbian or another Linux distro. If you are running Windows IoT Core then we can help you with that too.

_Mark Radbourne MSFT_

**Comment by samanaz** [comment]
Hi Markrad,

Thanks so much for informing me about this. But why in no article it is mentioned. Microsoft is saying that we should be able to cross compile with Visual Studio 2017 latest version.

Do you think it is possible to use an Ubuntu as host machine with Visual Studio Code, and the Raspberry as a gust to cross compile? I can easily spin up my Hyper-V and install an Ubuntu.

I still think Microsoft needs to use its teaching channels and websites to teach people like me. Linda has been a great teaching platform and I could educate myself with that many good skills. But I am seeing from the time that it is purchased by Microsoft seems to be stopped and no new subject is found on that. But Why?


I love Microsoft and I have been with Microsoft from Server 2000 until now that I am using Azure AD and Intune. But sometimes they do strange things. Please tell them we need good and constant teaching methods. Customers need to learn technologies otherwise they cannot use it.


Thanks again and I really appreciate it.

Kind regards,
Saman

**Comment by samanaz** [comment]
@yzhong94 

Hi,
Thanks so much for your reply. I have not tried that because I was thinking that it is possible to do that with Windows 10 and Visual Studio 2017. Apparently as @markrad mentioned it is not possible to do it with Windows 10 and Visual Studio 2017.

I am going to test that with Ubuntu and Visual Studio Code as a host machine and Raspberry as a guest.
Please let me know if this setup is not going to work,

I will follow the instruction that is mentioned in your comment and I will let you know how it goes.

Thanks so much for your help.

Kind regards,
Sam

**Comment by samanaz** [comment]
@markrad 

I forget to mention yes I use Raspbian.

**Comment by yzhong94** [comment]
Here is the doc for 5min quickstart: https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-send-telemetry-c

I will leave issue open as there is unfinished question around RaspPi

**Comment by massand** [comment]
@yzhong94 I believe @markrad has pointing out the latest docs for [Raspberry Pi](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/SDK_cross_compile_example.md)

**Comment by az-iot-builder-01** [comment]
@samanaz, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
