### ISSUE TITLE
Question about IoT Hub Certificates policy

### ISSUE THREAD

**Issue by mm-mhr** [Azure/azure-iot-sdk-c#42]
I have a question about the policy of the TLS certificates used in IoT Hub.
Updating my embedded devices with new Certificates once they are released to customers is a severe issue for me.
So I want to know how long my "things" can work with Azure IoT hub.

The IoT hub is using a certificate "*.azure-devices.net". It will expire next year.
It is signed by a certificate "MSIT". It wil lexpire next year, too.
The root certifictae "baltimore" will expire in 2025.

Will the next certificates ("*.azure-devices.net" and "MSIT") be signed with the "baltimore" root certificate again?

**Comment by dcristoloveanu** [comment]
@mm-mhr 

"Will the next certificates ("*.azure-devices.net" and "MSIT") be signed with the "baltimore" root certificate again?"
Yes, that is correct. In fact you only need the Baltimore certificate on your device (we'll be updating the certs.c to remove the other 2 certs so it is not misleading anymore).

Thanks!
/Dan

**Comment by dcristoloveanu** [comment]
If this answers your question feel free to close the issue.

Thanks,
/Dan

**Comment by mm-mhr** [comment]
Thank you for the quick anwser. 
This gives me two more years.

"Baltimore" cerificate will expire in 2025.
So this means that in best case my IoT "thing "will work until 2025.
As a consequence I need a mechanism to update the certificate in my "thing" if I want to support a longer lifetime.
Is this understanding correct?

**Comment by dcristoloveanu** [comment]
@mm-mhr

Yes, that is correct, in order to be able to put a new certificate on the device, a way to send that new certificate to the device and save it on the device must be implemented.

There are many ways that this can be achieved. For example, one of them would be sending the certificate payload via a C2D command to the device, when the command is received saving the payload in a proper location on the device. Then the file content could be read then and passed as certificate information to the SDK.

Hope this helps,
/Dan
