### ISSUE TITLE
IoTHubClient_CreateFromConnectionString return non-null handle with wrong connection string

### ISSUE THREAD

**Issue by syedelec** [Azure/azure-iot-sdk-c#422]
- **OS and version used:** <VERSION> 
Ubuntu 16.04

- **SDK version used:** <VERSION> 
master

# Description of the issue:

Any connection string provided with any URL as hostname does return a non-null handle. Is there any check to verify that connection string is valid ?

# Code sample exhibiting the issue:

```
const char *connectionstring = "HostName=example.com;DeviceId=foo;SharedAccessKey=bar"
handle = IoTHubClient_CreateFromConnectionString(connectionstring);
// handle is non-NULL

const char *connectionstring = "HostName=example;DeviceId=foo;SharedAccessKey=bar"
handle = IoTHubClient_CreateFromConnectionString(connectionstring);
// handle is NULL
```

Python Azure SDK does produce the same output so I suppose this is a wanted behavior.

# Console log of the issue:

Thanks

**Comment by jebrando** [comment]
We did not want to limit the Hostname in any way due to the differences in region and preferences.  The SDK will allow any string in the hostname and the failure will happen when attempting to send the message.

Thanks for the issue and if you would like further clarification, just reopen the issue.
