### ISSUE TITLE
Receiving more than one message with low-level iothub_ll_client

### ISSUE THREAD

**Issue by VitSolcik** [Azure/azure-iot-sdk-c#428]
Hi,

I am developing application on Freescale and NXP MCU SDK. We are using FreeRTOS and iothub_ll_client library.

My problem is that I can receive only one cloud-to-device message on my device after successful handshake.

Receive loop looks like this:

```
while(1)
{
    IoTHubClient_LL_DoWork(iotHubClientHandle);
    ThreadAPI_Sleep(1);
}
```
I also noticed, that You removed iothub_ll_client samples and replaced them with threaded one. Are you still going to support this library in future?

Thanks for reply.
Vit Solcik.

**Comment by jspaith** [comment]
For the first question about only receiving one message, could you please post additional logs (making sure you remove any connection strings or private info).  Logging for our layer is done via

```c
    bool traceOn = true;
    IoTHubClient_LL_SetOption(iothub_ll_handle, OPTION_LOG_TRACE, &traceOn);
```

For the 2nd question RE samples, the new `iothub_ll_telemetry_sample` which consolidated some of the old ones is indeed _LL_ based.  We're **absolutely** going to continue to support all our API's and any intentionally back-compat breaking change we would (a) get a lot of feedback from community 1st, (b) have a lot of warning, and (c) is not something we're planning in short/mid term.

Was there another sample you were thinking of here that was threaded?

**Comment by VitSolcik** [comment]
Hi,
I have some difficulties to make additional logs, after executing this code:
```
bool traceOn = true;
IoTHubClient_LL_SetOption(iotHubClientHandle, OPTION_LOG_TRACE, &traceOn);
```
I got this errors:

> Info: unknown option logtrace
> Error: Time:Sat Mar 24 13:51:36 2018 File:C:\GIT4\mcu-sdk-2.0\middleware\azure_iot\c-utility\src\httpapiex.c Func:HTTPAPIEX_SetOption Line:609 error code = HTTPAPIEX_INVALID_ARG
> Error: Time:Sat Mar 24 13:51:36 2018 File:C:\GIT4\mcu-sdk-2.0\middleware\azure_iot\iothub_client\src\iothubtransporthttp.c Func:IoTHubTransportHttp_SetOption Line:2430 HTTPAPIEX_SetOption failed
> Error: Time:Sat Mar 24 13:51:36 2018 File:C:\GIT4\mcu-sdk-2.0\middleware\azure_iot\iothub_client\src\iothub_client_ll.c Func:IoTHubClient_LL_SetOption Line:1794
>  underlying transport failed, returned = IOTHUB_CLIENT_INVALID_ARG

The rest of the application behaves just as described above.

After quick debugging I assume there isn't "logtrace" option in httpapi_compact.c file (HTTPAPI_SetOption function).

Regards,
Vit Solcik.

**Comment by ewertons** [comment]
Hi @VitSolcik ,

with the logs on your last post we were able to understand a little more of your context. 
You are using the device client SDK with HTTP transport, so "logtrace" won't have any effect (it works with AMQP and MQTT transports).

Could you confirm which version of the azure-iot-sdk-c you are using? 
Are you getting it straight from master branch, or you modified the code?

If you are getting at least one c2d message successfully that is good news. It means the connection itself is getting established.

Since you are using HTTP, have you played with the option [OPTION_MIN_POLLING_TIME](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/inc/iothub_client_options.h#L33)?
If not, it could be that the frequency with which the client is polling for c2d messages is too low and getting just the first one you send. 
The default polling frequency used by the SDK with HTTP transport is [once every 25 minutes](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransporthttp.c#L851), you must adjust it to the frequency that better suits your application.

That can be done using the following:

```
unsigned int minimumPollingTimeInSeconds = 1; // i.e., one polling per second.
(void)IoTHubClient_LL_SetOption(iothubClientllHandle, OPTION_MIN_POLLING_TIME, &minimumPollingTimeInSeconds);
```

Could you provide the details above and confirm if tweaking the polling frequency addresses the issue you are experiencing?

**Comment by jspaith** [comment]
Hi @VitSolcik  - since this thread has been quiet about a week, we're going to close it.  It doesn't look like you have resolution though, so if you need further assistance on this please reactivate with info Ewerton requested and/or create a new issue.  Thanks

**Comment by tameraw** [comment]
@VitSolcik thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
