### ISSUE TITLE
Question: Access to message_queue management functions

### ISSUE THREAD

**Issue by truschival** [Azure/azure-iot-sdk-c#450]
- **OS and version used:** Linux

- **SDK version used:** 1.2

## Description of the ~~issue~~ question:

Somewhat related to #427.  When the connection is (temporarily) I would like to discard older messages or limit the lifetime of messages in the queue.
I have found functions in `azureiot/message_queue.h` that seem to offer what I am looking for. Unfortunately all functions require a `MESSAGE_QUEUE_HANDLE*  message_queue` argument and I have no idea how I can obtain this handle after/during/between call of `IoTHubClient_CreateFromConnectionString` and `IoTHubClient_SendEventAsync`. 

Is there any way to access the message_queue?
If not, could you please give me a pointer where to look for limiting the number of queued message and discarding old messages? 

Thanks in advance.

**Comment by ewertons** [comment]
Hi @truschival ,

message_queue is an internal component used in one of the modules within the Azure IoT C SDK.
As we evolve the code we eventually work on individual modules to refactor/advance the code. That's a continuous and independent process, and some modules might use new tools/libraries while others await for their time to enjoy improvements like message_queue.

We do not plan on exposing it though.

You can always limit the overall time a message stays on the queue by calling _SetOption and using option "telemetry_event_send_timeout_secs" (for AMQP; takes size_t* value). MQTT transport does not expose a way to control the maximum queue time.
None of the queues have size caps, so that is not configurable as well.

**Comment by ewertons** [comment]
@truschival ,
we will close this issue but please feel free to reopen it if you would like to follow up on the question.

Thank you for using the Azure IoT SDKs. 
Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)

**Comment by tameraw** [comment]
@truschival thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
