### ISSUE TITLE
Serializer, Device Twin Desired/Reported property with the same name

### ISSUE THREAD

**Issue by Patrik-Berglund** [Azure/azure-iot-sdk-c#458]
Hi,

How do i model this with the serializer library?

```
{
    "properties": {
        "desired": {
            "updateFrequency": 10
        },
        "reported": {
            "updateFrequency": 10
        }
    }
}

```

This results in "error: duplicate member 'updateFrequency'
```
DECLARE_DEVICETWIN_MODEL(Twin,
                         WITH_DESIRED_PROPERTY(int32_t, updateFrequency, onUpdateFrequency),
                         WITH_REPORTED_PROPERTY(int32_t, updateFrequency));
```

**Comment by ewertons** [comment]
Hi @Patrik-Berglund ,

Which compiler are you using? and in which OS?

When building on VS2015 I get this error:

```log
1>------ Build started: Project: devicetwin_simplesample, Configuration: Debug Win32 ------
1>  devicetwin_simplesample.c
1>E:\Repos\shelf2\azure-iot-sdk-c\serializer\samples\devicetwin_simplesample\devicetwin_simplesample.c(60): error C2020: 'lastOilChangeDate': 'struct' member redefinition
========== Build: 0 succeeded, 1 failed, 12 up-to-date, 0 skipped ==========
```

This is the change I made:

```c
DECLARE_DEVICETWIN_MODEL(Car,
    WITH_DESIRED_PROPERTY(ascii_char_ptr, lastOilChangeDate, onLastOilChangeDateChanged),
    WITH_REPORTED_PROPERTY(ascii_char_ptr, lastOilChangeDate), /*this is a simple reported property*/
```

**Comment by Patrik-Berglund** [comment]
Hi @ewertons 

We are using the ESP-IDF SDK (3.0-rc1) for the ESP32 SoC. 

Ok, so you got the same error at least as I did. So it's not possible to have a property with the same name in both desired and reported?

I was using this example as a reference, https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins

Might be that I'm missing something obvious here, we just started with the device twin this week.. :)

Ended up doing like this.. but the model doesn't look that nice..
```
{
    "properties": {
        "desired": {
            "desiredUpdateFrequency": 10
        },
        "reported": {
            "reportedUpdateFrequency": 10
        }
    }
}
```

```
DECLARE_DEVICETWIN_MODEL(Twin,
                         WITH_DESIRED_PROPERTY(int32_t, desiredUpdateFrequency, onUpdateFrequency),
                         WITH_REPORTED_PROPERTY(int32_t, reportedUpdateFrequency));
```

Thanks for your quick reply as always :).

**Comment by ewertons** [comment]
Hi @Patrik-Berglund , my pleasure.

So the situation here is that the twin document itself - as defined by the IoT Hub service - does support having two properties with the same name in the two blocks (desired and reported). 

If instead of Serializer you use the Azure IoT C SDK to receive twin documents ([IoTHubClient_LL_SetDeviceTwinCallback](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/inc/iothub_client_ll.h#L526)) you will be able to access those properties.

The error you see is isolated to the Serializer client, which seem to be a bug.
I'll add John here to comment on the priority for fixing it (I am not sure how high it is given what we have in our backlog).

The workaround you have for now, and sorry for being so obvious, is to use different property names.

**Comment by jspaith** [comment]
I'll just be upfront here and say we'll probably never fix this one - or if we did it'd be part of a much larger serializer rework.

We're continuing to support serializer for critical fixes, but the bar is quite high at this stage.  Per https://github.com/Azure/azure-iot-sdk-c/issues/388#issuecomment-369992487 there are a number of limitations with the serializer you should be aware of going in.  We need to document this as another limitation, so I'm tagging this as an area-documentation since we do need to more formally doc this & the issues in the link.

Sorry I don't have better answer here.

**Comment by Patrik-Berglund** [comment]
Hi @jspaith 

Thanks for your upfront answer, no idea to sugarcoat it.

The main issue I think is that we will probably want to align the twin model with devices that doesn't use the c sdk.

Regarding the issues in #388 , it's of minor concern i our case. The twin will not be that large and the ESP32 has quite a lot of ram.

There's not that many examples using the device twin without the serializer. Found this one but it doesn't do any processing of the desired/reported props.
https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_client_sample_device_twin

Could you provide a more extensive example?
Maybe using this as a base, https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins

**Comment by Patrik-Berglund** [comment]
Sounds good, keep this issue open until such an example is available?

**Comment by ewertons** [comment]
Hi @Patrik-Berglund ,
the new sample showing how to consume and update Device Twin properties using iothub_client and a json parser (instead of Serializer) was just checked in. 
Please take a look at [iothub_client_device_twin_and_methods_sample](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_client_device_twin_and_methods_sample).

**Comment by ewertons** [comment]
We will close this issue but if you have any follow up questions please feel free to reopen it.

Thanks for using the Azure IoT SDKs!
