### ISSUE TITLE
Question with Regard to Retry Policy

### ISSUE THREAD

**Issue by mm-mhr** [Azure/azure-iot-sdk-c#47]
It looks like that currently the Retry Policy "Exponential_BackOff_With_Jitter" is the only one implemented.
For one of my use cases I would need something which retries e.g. every 2 minutes.
Is there a way to tweak "Exponential_BackOff_With_Jitter" to behave in such a way?

Do you have plans to implement additional retry policies ?

**Comment by olivierbloch** [comment]
Hi @mm-mhr 
We do intend to implement more retry policies such as linear back-off, or interval retries (like the one you are looking for). We don't have a clear timeline for this just yet though.
Stay tuned for updates.
Thanks

**Comment by ewertons** [comment]
Just an update: the Azure IoT C SDK, when using AMQP transport, is capable of supporting different types of the retry policies we plan to have.

However, the current API design (across all layers) exposes setting the retry policy which includes only the frequency function (e.g., ...EXPONENTIAL_WITH_BACKOFF) and the maximum retry time. Setting the interval is not exposed. @olivierbloch , what do you think about modifying that?

AMQP transport is kinda prepared for this change, since internally there is module it uses called iothub_client_retry_control.h which exposes setting the retry "interval".
