### ISSUE TITLE
Expansion of macro MOCKABLE_FUNCTION fail in Arm gcc and Keil MDK-ARM

### ISSUE THREAD

**Issue by DavidJurajdaNXP** [Azure/azure-iot-sdk-c#498]
Dear Sir or Madam,

My environment is:
- **OS and version used:** <VERSION> Windows 10
- **SDK version used:** <VERSION> 1.2.4

# Description of the issue:
I am not able to expand macro MOCKABLE_FUNCTION by following preprocessors:
armgcc 7 2017-q4-major
Keil MDK V5.24.2.0

I am able to expand it only by:
IAR 8.22.2.15996

Preprocessors failed to expand macro MOCKABLE_FUNCTION defined in umock_c_prod.h. 
Issue can be tracked to macro_utils.h, which is very difficult to debug. Do you have any experience with such behavior? Could you provide any recommendation of third party compilers' settings?

# Code sample exhibiting the issue:
`MOCKABLE_FUNCTION(, STRING_HANDLE, STRING_new); `

# Console log of the issue:
[arm_gcc_build_log.txt](https://github.com/Azure/azure-iot-sdk-c/files/2032082/arm_gcc_build_log.txt)

I would be glad for any hints.

Regards,
David Jurajda

**Comment by jspaith** [comment]
OK, I *think* what's happening 

```
In file included from c:\git\m\middleware\azure_iot\c-utility\inc\azure_c_shared_utility\strings.h:7:0,
                 from c:\progra~2\gnutoo~1\72017-~1\arm-none-eabi\include\string.h:24,
                 from c:\git\m\middleware\azure_iot\c-utility\inc\azure_c_shared_utility\macro_utils.h:17,
                 from c:\git\m\middleware\azure_iot\c-utility\inc\azure_c_shared_utility\threadapi.h:12,
                 from C:\GIT\m\boards\src\azure_examples\azure_http\iothub_client_sample_http.c:12:
```

`macro_utils.h` is bringing in `string.h` but on your platform this `string.h` including `strings.h`.  It's likely wanting its own private implementation of `strings.h` but it turns out that its trying to use the `strings.h` in the IoT C SDK because we must be ahead of it in the include path order.  And because this is at the top of the `macro_utils.h` file, it hasn't got a chance to define its `IF` macro yet.

I think if you fix the include path to make it favor the system strings.h over ours you should be OK.

Interestingly in `/usr/include/linux/string.h` and also `/usr/include/strings.h` there's comments about not wanting string.h to automatically bring in strings.h, so this is how we've been sidestepping this on other platforms.

**Comment by DavidJurajdaNXP** [comment]
Hi John,

Thank you for help. You are correct. I had defined include paths to locations:
```
azure_iot\c-utility\inc\azure_c_shared_utility
azure_iot\c-utility\inc
```

It eliminated benefit of absolute paths in includes (#include "azure_c_shared_utility/macro_utils.h") and introduced issue with system headers.

I have fixed it by removing include path:
`azure_iot\c-utility\inc\azure_c_shared_utility`

Regards,
David
