### ISSUE TITLE
CMake Error at CMakeLists.txt:186 (set_platform_files):

### ISSUE THREAD

**Issue by ZenChang** [Azure/azure-iot-sdk-c#503]
CMake Error at CMakeLists.txt:186 (set_platform_files):
  Unknown CMake command "set_platform_files".

**Comment by jspaith** [comment]
My guess here is that you need you recursively clone the C SDK repo.  So it needs to be a 'git clone **--recursive** https://github.com/Azure/azure-iot-sdk-c.git'.  the set_platform_files is part of the c-utility subrepo which the C SDK needs in order to build.

I'd recommend starting the git clone recursive from scratch in a new dir instead of updating the existing.

If this doesn't help, we'll need to know more info like which platform you're building on, the commit ID of both the azure-iot-sdk-c as 'git submodule' output.

**Comment by jspaith** [comment]
Since this has been inactive > 1 week, closing out for book-keeping.  If you have followups by all means re-open this or create a new issue.  Thanks.
