### ISSUE TITLE
Valgrind reports memory loss during SAS token renewal via MQTT

### ISSUE THREAD

**Issue by vjrantal** [Azure/azure-iot-sdk-c#51]
I got a valgrind report like this https://gist.github.com/vjrantal/bbf91a11f24b472d86cd632fecceafc6 with the following steps:

1. The repository was checked out at commit 1865cd132073b1669ccf4fdea42143ecbaa45f65
2. I applied this diff https://gist.github.com/vjrantal/59c7edec8bdf5dbe6e67ecfc8de427ea so that SAS token got expired and renewed every now and then
3. Run the app with command like this:
```
vjrantal@ubuntu:~/Software/azure-iot-sdk-c/cmake/iotsdk_linux/iothub_client/samples/iothub_client_sample_mqtt$ valgrind --leak-check=full ./iothub_client_sample_mqtt
```
4. After the 200 messages were sent, sent a C2D message "quit" to the device so that it calls `IoTHubClient_LL_Destroy` and exists cleanly.

**Comment by anporumb** [comment]
Hello @vjrantal ,

When you forcefully close the app, the cleanup code does not have a chance to execute. This is a very interesting investigation for us, as we run all of our tests under valgrind (including e2e tests). 
In order to investigate this further, I would need a sample that "naturally" exits (not forcefully by CTRL+C) and calls the cleanup code and that still fails under valgrind.

Thank you.

Best Regards,
Andrei Porumb

**Comment by vjrantal** [comment]
@anporumb Updated the repro steps to involve a clean exit and providing here the valgrind report from that scenario https://gist.github.com/vjrantal/bbf91a11f24b472d86cd632fecceafc6 .

**Comment by anporumb** [comment]
Hello @vjrantal ,

Thank you for your report. It so happens that we were already working on these leaks and we will release a fix soon. 

Best Regards,
Andrei Porumb

**Comment by anporumb** [comment]
Published.
