### ISSUE TITLE
Upload image file to azure blob

### ISSUE THREAD

**Issue by komalpharate** [Azure/azure-iot-sdk-c#520]
used IoTHubClient_LL_UploadToBlob to upload text  to File on Blob.
It works good.
But not finding the way to upload an image to blob in C.
Any help?

**Comment by ewertons** [comment]
Hi @komalpharate, the functions in the Azure IoT C SDK for file upload only handle bytes, they have no knowledge of the type of the file.

As shown in the [sample](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_upload_to_blob/iothub_client_sample_upload_to_blob.c#L73), to upload an image all you need is to change the file name, then upload the image bytes.

Example:
```
#include <stdio.h>
...

FILE *fp;
size_t numOfBytesRead;
size_t fileSize = 10240; // This your file size.
const unsigned char* buffer;

buffer = malloc(sizeof(const unsigned char*) * fileSize);
fp = fopen("./myimage.jpg", "r");
numOfBytesRead = fread(buffer, sizeof(unsigned char*), fileSize, fp);

IoTHubClient_LL_UploadToBlob(iotHubClientHandle, "subdir/myimage.jpg", (const unsigned char*)buffer, fileSize);
``` 

However, since image file sizes are usually much larger than 10 KB (as in the example above), you should consider using the other function we have, [IoTHubClient_LL_UploadMultipleBlocksToBlobEx](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_upload_to_blob_mb/iothub_client_sample_upload_to_blob_mb.c#L113)

**Comment by githubmobiliya** [comment]
Thanks a lot. It worked for me.

**Comment by ewertons** [comment]
@komalpharate ,
we will close this issue for now but feel free to reopen it if you would like to follow up.
Thanks for using the Azure IoT SDKs!

**Comment by ewertons** [comment]
@komalpharate  , thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)

**Comment by arulraj17993** [comment]
Hi,
Is it possible to upload video files of 50-100MB (even more) using azure-iot-sdk c? 
Can I follow the same procedure which was used to upload the image as given above?

Thanks.

**Comment by PranjaliSoni** [comment]
Hi @komalpharate 

Same Code for image upload is not working for png file . Is there any way to upload png file using C SDK
