### ISSUE TITLE
OPTION_CURL_VERBOSE reference in iothub_client_ll_uploadtoblob.c

### ISSUE THREAD

**Issue by alexmrtn** [Azure/azure-iot-sdk-c#528]
- **OS and version used:** Windows

- **SDK version used:** 2018-06-15

# Description of the issue:
Hi,

In the file `iothub_client/src/iothub_client_ll_uploadtoblob.c` there is a call to a `SetOption` function using the parameter `OPTION_CURL_VERBOSE` for the underling HTTPAPI:

https://github.com/Azure/azure-iot-sdk-c/blob/2d4e03f9b7e1471e9fb64be3c067a255537e4868/iothub_client/src/iothub_client_ll_uploadtoblob.c#L862

On Linux this works fine, but it on Windows this cause an error log at execution time because the winhttp adapter (in c-utility) does not support this option.

What you think would be the best solution:
- remove the ability to set verbose mode for upload blob feature;
- have a common `OPTION_VERBOSE` option for all platforms, and ignoring it when it does not apply;

Thanks,
Alexis

**Comment by ewertons** [comment]
Hi @alexmrtn ,
yes that has been in our list of improvements for a while, it just couldn't get enough priority to get done yet.
We will track it as an improvement.
If you would like to give it a stab and send a PR we can help review and merge it.
Thanks,
Azure IoT SDK Team

**Comment by jspaith** [comment]
I've implemented a fix.  My concern with the common `OPTION_VERBOSE` is I'd rather have the callee fail if it can't support an option instead of ignoring it.  Wininet/Winhttp don't have console logging capability.

I think correct fix is that UploadToBlob has no business setting this curl option unless the user explicityl asked.  So we need a tri-state: curlUnset, curlOn, curlOff.  I've coded this up in branch `curl-verbose-clean` and have out for internal review.

**Comment by jspaith** [comment]
Was out for a bit, but fix is in now.  eb649d0da00df492c65a1c2297fba12409da6108.

**Comment by az-iot-builder-01** [comment]
@alexmrtn, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by alexmrtn** [comment]
Hi @jspaith, thanks for the fix!
