### ISSUE TITLE
Support Multiplexing with Device Twins over AMQP

### ISSUE THREAD

**Issue by docsteer** [Azure/azure-iot-sdk-c#546]
# Environment
* Windows 7 64-Bit, MSVC
* Using libraries from Nuget
  * Microsoft.Azure.C.SharedUtility.1.1.5
  * Microsoft.Azure.IoTHub.AmqpTransport.1.2.3
  * Microsoft.Azure.IoTHub.IoTHubClient.1.2.3
  * Microsoft.Azure.IoTHub.Serializer.1.2.5
  * Microsoft.Azure.uamqp.1.2.5

# Description of the issue:
I am attempting to build a gateway-type device which interfaces to multiple legacy devices, and it would be desirable to interface with those devices using all the Azure IOT feature. It appears that connection multiplexing works using AMQP for messaging and telemetry, but does not work for use of device twins. This is shown by error messages produced by the libraries, for example:

```
iothub_client/src/iothubtransport_amqp_common.c line 1709
LogError("Device Twin not supported on device multiplexing scenario");
```
It appears, although I do not yet have a working sample, that this could be supported by the AMQP protocol; so this is a feature request to add support for device twin multiplexing (or a question as to why it is not supported if I am missing something!).

**Comment by jspaith** [comment]
@docsteer  - just to touch base here, your reading of the code is correct.  We will track this on our backlog.  I don't really have an ETA here, but to be honest I don't see it coming out in next few months even at best case.

And re-reading this description, if you're trying to build a gateway have you looked into IoT Edge?  It lets legacy devices connect through a single Edge device to the Cloud, and these devices can either run IoT Edge or you can author custom modules to translate TCP/IP or even non-IP.  I'm pretty sure it has built-in multiplexing since all communication to Cloud goes over AMQP.

https://azure.microsoft.com/en-us/services/iot-edge/

**Comment by docsteer** [comment]
@jspaith thanks for the update. I did some hacking of the SDK myself and was able to get it to work, but my changes have probably broken other transport mechanisms - I will attempt to clean it up and submit a pull request if I get some time.

I have looked at IoT Edge, but I think the SDK is the same either way (based on looking at the example here : https://github.com/Azure/azure-iot-edge-c-module)

So I would be able to multiplex with IoT edge, but I would need to spin up multiple containers in the edge device, or have multiple processes within one container all with separate connections. Since I have existing legacy C code to interface to which provides connections to multiple devices, it would still be convenient for me to be able to connect them to multiple "devices" in the cloud via a single process if possible.

**Comment by docsteer** [comment]
Thanks @jspaith, looking at this link:

https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-as-gateway

I think my scenario is most accurately described by the identity translation gateway, in that I have multiple legacy devices which I would like to represent each of as an Azure IoT device. I wasn’t clear how to do that from that doc - let me know if there’s a better place to ask these questions!

**Comment by damonbarry** [comment]
Hi @docsteer 

To represent legacy devices in Azure IoT you'd go into the portal and create a device identity for each one. Or you can do it programmatically using the service SDK. Then, these legacy devices could use one of our IoT device SDKs to communicate with IoT Edge. If they don't have the right protocol stacks (AMQP or MQTT) or can't use our SDKs for whatever reason, then you should be able to write a module that runs on IoT Edge and exposes a custom endpoint that your devices can communicate with. Your module would translate messages, and IoT Edge would process them.

The source code for IoT Edge is here: https://github.com/Azure/iotedge. If you find bugs you can file issues there.

If you have coding questions about IoT Edge you can ask them on Stack Overflow: https://stackoverflow.com/questions/tagged/azure-iot-edge

You can provide feedback and open issues or pull requests against our documentation as well (there are links on each page): https://docs.microsoft.com/en-us/azure/iot-edge

**Comment by jspaith** [comment]
One thing to watch out for here is that you're on Windows 7, which isn't a supported Edge platform.  Don't know if that's a hard-target for your product run or if this is just your initial dev setup?

**Comment by jspaith** [comment]
@docsteer - I'm curious if Edge is going to be a viable way to address your problem, or do you still have the desire for the twin multiplexing that kicked off this discussion initially?  Thanks

**Comment by jspaith** [comment]
@docsteer - since this has been dormant for a bit and is not something on our even next few months radar, I'm going to close it out.  

We'd still think using Edge is ideal, but understand your hardware constraints may not allow.

If you still would like this please open up an issue on https://feedback.azure.com/forums/321918-azure-iot.  We'll be triaging through these, and as an advantage there's a better up-vote mechanism in case others need this, too.  Thanks

**Comment by az-iot-builder-01** [comment]
@docsteer, @damonbarry, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
