### ISSUE TITLE
add 'file list' package support 

### ISSUE THREAD

**Issue by SergiyIvanovAtGTI** [Azure/azure-iot-sdk-c#549]
- **OS and version used:** Ubuntu 16.04.

- **SDK version used:** 0.2.0.0-7xen 

======
Please, add in your package for linux-like environment a 'file' feature so utilites like 
apt-file search 
apt-file list
could work against your package

**Comment by ewertons** [comment]
Thanks for the suggestion, @SergiyIvanovAtGTI 
We will add this item to our list of enhancements.

**Comment by jebrando** [comment]
@SergiyIvanovAtGTI I'm unfamilar with the apt-file search application.  Does it just crawl the repository looking for these files.  I'm unaware of any file that needs to be to make this work.  Do you have any pointers as to how this process works?  We are using LaunchPad as a debian repository and this may be a factor.

**Comment by SergiyIvanovAtGTI** [comment]
Hi, @jebrando . The purpose of apt-file under apt is to see files within package and see what files belong to package. I don't know whether they have own repository or use the same as apt-get (and i believe the latter is a case), but apt-file client also have 'update' command so, i believe, repository just should propose file(s) that apt-file understand.

**Comment by jspaith** [comment]
@SergiyIvanovAtGTI - for files already on your box, there is `dpkg -S` though I understand it's not the same as the apt-file repository search of uninstall pkgs.

Unfortunately for apt-file specifically, we're going to close this.  There are two possibilities as to why this isn't working with the C SDK:
* Apt-file needs some sort of special logic to tie into the launchpad repository that hosts our apt-get packages, the same way that you have to tell apt on your Linux about our repository for even the install to work.  I've researched how to do this - if its the answer - and asked a few of our Linux experts around but can't find any answers.
* We need to put some sort of special contents logic into our release process.  This would be nice to have.  But it doesn't meet our bar now, and I can't ever see a time when it'd meet our bar, either.  So we're just going to close this rather than letting it drag on forever.

Sorry I can't give you a better answer.  If you ever stumble across across an answer on local apt-file changes (if there is one), please let us know.

**Comment by az-iot-builder-01** [comment]
@SergiyIvanovAtGTI, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)
