### ISSUE TITLE
Digest authentication is not performed when connecting to a proxy server that requires authentication

### ISSUE THREAD

**Issue by rmanaka** [Azure/azure-iot-sdk-c#568]
- **OS and version used:** <VERSION> 
Windows 8.1
(Build environment)
Visual Studio 2017

- **SDK version used:** <VERSION> 
Azure IoT device SDK for C (target OS: Windows)
master/release_2018_06_15
1.2.5

# Description of the issue:

I am trying to implement device code using Azure IoT device SDK for C.
I consider the possibility that a proxy server requiring authentication intervenes when connecting from IoT device to IoT Hub. Therefore, the connection protocol adopted MQTT over WebSockets.
I created a test code based on the sample code and tested the connection via the proxy server.

At this time, a problem was found in the connection to the proxy server requiring authentication.
Digest authentication is not performed in the authentication process of the authentication proxy server.
Basic authentication is always done.

I confirmed the Azure IoT SDK source code.
[/azure-iot-sdk-c/c-utility/src/http_proxy_io.c]
As far as verifying the above code, it seems that code to handle Digest authentication is not included.
Is this recognition correct?
If this recognition is correct, please handle Digest authentication when connecting to a proxy server requiring authentication.
Or, by making some configuration changes, can the SDK support Digest authentication?

Regards,
rmanaka

# Code sample exhibiting the issue:

iothub_ll_telemetry_sample.c
(Added proxy setting code only)

**Comment by BigPeteB** [comment]
@rmanaka, We've looked into what would be required to implement this, and unfortunately it's a rather substantial change. The current HTTP proxy client is a trivial implementation, and it would need to have a lot of functionality added in order to properly parse a proxy server's response and make a request with digest authentication.

This is really the first we've heard of a proxy needing digest authentication. Most HTTP proxies these days are typically inside corporate networks where basic authentication is sufficient. Quite a few HTTP proxies don't even support digest authentication.

We're going to close this issue for now, but you're welcome to suggest this feature at https://feedback.azure.com/forums/321918-azure-iot. If you do know of any specific HTTP proxies that use or require digest auth, or if you can share which customers are using those proxies, that would be helpful information to include to give a sense of how widespread or urgent the need for digest auth is.

**Comment by az-iot-builder-01** [comment]
@rmanaka, @BigPeteB, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
