### ISSUE TITLE
Please expose configuration options to disable unneeded projects

### ISSUE THREAD

**Issue by jiriappl** [Azure/azure-iot-sdk-c#59]
Hello,

Trying to compile on raspberry pi here and it is taking decent amount of time. Please consider adding additional CMAKE configuration options to disable uamqp, umqtt and iot_client_service.

Regards,
Jiri

**Comment by olivierbloch** [comment]
Hi @jiriappl 
Such flags already exist. Type the below command at the root of the repo to get a list:
cmake . -LH

**Comment by jiriappl** [comment]
Imho these do not cover what I am asking; setting use_mqtt/use_amqp to OFF will not stop building uamqp and umqtt.

**Comment by olivierbloch** [comment]
I see.
Let me tag this issue as an enhancement request as this is a good idea but not something we have added to our backlog at this point.

**Comment by jiriappl** [comment]
Sounds good, thanks.

**Comment by ewertons** [comment]
Hi @jiriappl , I made a small change to fix the cmake dependencies and now you can build the C SDK clients for HTTP without adding uamqp, umqtt or iothub_sevice_client*.
You can use the command bellow, which will strip down a lot of other projects you don't necessarily need to build to create your application.

```
cd <azure-iot-sdk-c path>
mkdir cmake
cd cmake
cmake -Duse_http=ON -Duse_mqtt=OFF -Duse_amqp=OFF -Drun_unittests=OFF -Drun_e2e_tests=OFF -Dskip_samples=ON  ..
```

* you can disable only iothub_service_client by passing -Dbuild_service_client=OFF. However, since it depends on AMQP and HTTP, if you disable any of these `build_service_client` will be set to OFF automatically.

**Comment by ewertons** [comment]
81373738ab1830faf021d407c46d53be75d00d3f
