### ISSUE TITLE
General file names causing conflicts with other middlewares

### ISSUE THREAD

**Issue by DavidJurajdaNXP** [Azure/azure-iot-sdk-c#610]
- **OS and version used:**  Windows 10

- **SDK version used:** 1.2.8

# Description of the issue:

Some files are named in very general way. It is causing conflicts with other middlewares (lwip). Issue can be avoided by selecting of unique name space for file names. Perhaps "azure" prefix/postfix could be suitable solution.

Affected files:
hmac.c
version.h
sha1.c
base64.c

**Comment by massand** [comment]
@DavidJurajdaNXP - there are a few projects riding on the c-shared-utility repo (where this issue truly belongs btw, but I'll address here since it is very closely tied to azure-iot-sdk-c repo). So, a refactor is not in our immediate plans - although we could consider it if we rework our PAL layer in c-shared-utility someday. All the platform + compiler options we have built for haven't run into this issue (other than minor filename confusions at times). 

Do you have the ability to build static libraries out of the SDK and link that with your project, instead of adding the file directly to a flat folder structure? I am closing for now, but reopen for discussion on this issue, if you have seen frequent reports of this.

**Comment by DavidJurajdaNXP** [comment]
Hi @massand, thanks for reaction. Static library is not a solution, because we are typically delivering examples without precompiled libraries. This is not big deal, I am currently adding _azure suffix to conflicting files. My goal is to point out occurrence of this issue in combination of Azure SDK and lwip. File rename seems to be most straightforward fix.

Regards,
David
