### ISSUE TITLE
"IoTHubRegistryManager_GetDeviceList" is deprecated.

### ISSUE THREAD

**Issue by ahidaka** [Azure/azure-iot-sdk-c#640]
- **OS and version used:** Ubuntu 16.04, 18.04, etc... 

- **SDK version used:** azure-iot-sdk-c 1.2.9 

# Description of the issue:

"IoTHubRegistryManager_GetDeviceList" is deprecated and may be removed from a future release.
Which API shall I use to get list of all device list instead of this? This is not described anywhere.

# Code sample exhibiting the issue:

Those are related code and documents below in SDK.
- iothub_service_client/devdoc/requirement_docs/iothubserviceclient_registrymanager_requirements.md
- iothub_service_client/src/iothub_service_client.def
- iothub_service_client/src/iothub_registrymanager.c
- iothub_service_client/tests/iothub_rm_ut/iothub_rm_ut.c
- iothub_service_client/inc/iothub_registrymanager.h

# Console log of the issue:

**Comment by ahidaka** [comment]
I found the fact that should be IoTHubRegistryManager_GetModuleOrDeviceList().
Is this correct?

**Comment by ahidaka** [comment]
OK, I found IoTHubRegistryManager_GetModuleOrDeviceList() doesn't work.
Is there any way to get the list of devices?

**Comment by massand** [comment]
@ahidaka IoTHubRegistryManager_GetModuleOrDeviceList is an internal API (not exposed by the SDK for external consumption). IoTHubRegistryManager_GetDeviceList can be used externally at the moment, until it is deprecated, but it has a max limit of 1000 devices due to the nature of the REST API it calls. 

If you would like better support for device query, I recommend using the C# SDK service client's [CreateQuery call](https://github.com/Azure/azure-iot-sdk-csharp/blob/6df87c4394907ceba3d3f4ff80694152a85d0213/iothub/service/src/RegistryManager.cs#L559) to achieve supported service client functionality.

**Comment by az-iot-builder-01** [comment]
@ahidaka, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by ahidaka** [comment]
OK, now I'm checking that IoTHubRegistryManager_GetDeviceList doesn't work only for one device with Segmentation fault, not 1000 devices. I forgot to tell this problem. I will create new issue for this.

**Comment by ahidaka** [comment]
Thanks for your advice. I confirmed "IoTHubRegistryManager_GetDeviceList" is working well.
Please don't deprecate "IoTHubRegistryManager_GetDeviceList".
I send the pull request for new samples with this. It will help iothub-explorer retire.
