### ISSUE TITLE
Failed to connect to iothub when use DPS individual enrollment

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-iot-sdk-c#647]
- **OS and version used: mbedOS5** 

- **SDK version used: 1.2.8**

# Description of the issue:
When using the DPS individual enrollment to connect IoT DevKit with IoTHub, passed the provision and assigning stage but failed when connect to IoTHub. 

# Code sample exhibiting the issue:
Refer the [DPS tutoriall](https://github.com/Microsoft/vscode-iot-workbench/blob/master/docs/iot-devkit/devkit_dps.md) to setup the dev env, before compile, get the [DevKit SDK](https://github.com/Microsoft/devkit-sdk/tree/1-28-backup) which use the 1.2.8 and replace the installed sdk under Arduino folder. 
Then follow the tutorial, will get the error. 

# Console log of the issue:
```
Registration Information received from service: devkit-dps-demo.azure-devices.net!
2018-09-20 20:45:09 INFO:  >>>IoTHubClient_LL_CreateFromDeviceAuth devkit-dps-demo.azure-devices.net, mydevkit0917, 0x20017698
2018-09-20 20:45:11 ERROR: File:iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1613, Connection Not Accepted: 0x5: Not Authorized
```

**Comment by lakshmisivareddy** [comment]
Hi @ArthurMa1978 

DPS and IOT  uses same authentication module  see below Document 

https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/devdoc/using_custom_hsm.md#hsm-x509-api

in your case authentication not happening to IOT hub because . Authentication module  not providing device authentication in formation like  (Device private key , conman name, Device public key ) iothub client

**Comment by az-iot-builder-01** [comment]
@ArthurMa1978, @lakshmisivareddy, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
