### ISSUE TITLE
Question: Access To Device-Twin Metadata

### ISSUE THREAD

**Issue by raycon94** [Azure/azure-iot-sdk-c#687]
Hello,

is there a way to get some meta-Information of an property (like an timestamp, when it was last set?).

Thanks!

**Comment by lakshmisivareddy** [comment]
Hi @raycon94 
yes we can able to get the last set time refer below document 
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins

**Comment by lakshmisivareddy** [comment]
Hi @raycon94 
from device -side  you can send a http request to get the device twin or IoTHubClient_LL_SetDeviceTwinCallback  register your  deviceDesiredTwinCallback once you get the twin message from IoT hub parse the object 
example: 
json_object_set_number(obj,"timestamp",seconds);
you will get the time stamp

**Comment by raycon94** [comment]
hello @lakshmisivareddy 
we are using MQTT.
What I want is to get the Metadata for each specific property.
When I get a (desired-)twinnotification over the sdk-callback, the payload of the message only contains the property itself and its versionnumber as metadata-information. But the timestamp when the property was last changed is missing.

**Comment by raycon94** [comment]
The devicetwin itself contains already this meta-information for each property:  "$lastUpdated".
My intention is, to read this information on device-side...

**Comment by massand** [comment]
Hi @raycon94 - thanks for your patience. There has been a new GetTwinAsync method added to the iothub_client API in the last release. In order to conserve bandwidth on the device side, all full device twin GET calls and PATCH updates receive property updates only.  The only way to achieve your task (reading metadata for twin properties) on a device is using the iothub_service_client IoTHubDeviceTwin_GetTwin for a specific deviceId. This requires service connect access key when creating the device twin handle using IoTHubDeviceTwin_Create. This returns the entire twin as seen in the portal (including tags, properties, metadata).

**Comment by az-iot-builder-01** [comment]
@lakshmisivareddy, @raycon94, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
