### ISSUE TITLE
Mqtt not timing out messages when can't reconnect

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#688]
Initially opened on https://github.com/Azure/azure-iot-sdk-python/issues/216

If MQTT is unable to establish a connection, it will keep trying and once it succeeds queued messages will be sent to the Cloud.

However, if for some reason we can't get past the initial connection phase, then SDK does not respect message timeouts.  An easy way to repro this is to just send a few messages with networking enabled via convenience sample, then disable your network in middle.

What is happening is that in `IoTHubTransport_MQTT_Common_DoWork`, we have logic that will compare max # of retries and ultimately call `sendMsgComplete(mqttMsgEntry->iotHubMessageEntry, transport_data, IOTHUB_CLIENT_CONFIRMATION_MESSAGE_TIMEOUT);` which tells caller that we should timeout.

However - if the initial call to `InitializeConnection` at the top of this function fails, then we never get into the correct spot in the loop to check the timeouts.  

Note there is at IoTHub_Client layer a `DoTimeouts` API.  However it doesn't save us here because its already transferred the messages from its pending queue to MQTT's waitingForAck.

To fix this
A) Checking for message timeouts should not be conditional on state of MQTT itself.  And 
B) It feels more natural to be the timeout based on actual timing, instead of checking whether a retry has occurred or not.  
C) The code in the block `Codes_SRS_IOTHUB_TRANSPORT_MQTT_COMMON_07_057` also needs review.  After we timeout the 1st timed out message, it looks like we unconditionally run through the queued messages and reset their retryCount=0.  If we just did (B) though, this would be moot.

**Comment by ravitejaveeragandam** [comment]
Hi,

Even i am facing some issue in "DoTimeouts" function from which control is not coming out.
The same i posted in the issues #698. Please tell us once it is resolved the issue or u have any other solution.

Regards
Raviteja V

**Comment by ravitejaveeragandam** [comment]
Hi,

I taken the latest software and started working. Observed a strange behavior.

I will explain my scenario first
On power on i use to send 9 packets of data, each size of 14 bytes. And my program waits for response for the 9 packets what i sent. Once it get response it will send next packets.

With earlier software version 1.2.8, i am able to receive the response message and send the data(10th packet) one or two times and gets hang in "DoTimeouts".

But with software version 1.2.10, i am able to receive correct response for one of the 9 packets which i am sending and able to place next one packet data in IOT buffer to transfer. But from IOT i am unable to send the data to Server(not able to receive in TWIN device explorer). And also i confirmed that "SendConfirmationCallback" is not getting called.

Is there anything extra care i need to take in new software? I have doubt like did connection gets closed once after first transaction? Because every time i restart i am able to send the data.. Once after first transaction i am not able send data.

**Comment by jebrando** [comment]
@ravitejaveeragandam I updated the SDK to timeout messages even when the device is not connected.  If you see any issues with the latest code feel free to reopen this issue or open another issue detailing the problem.

**Comment by az-iot-builder-01** [comment]
@ravitejaveeragandam, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
