### ISSUE TITLE
IoTHubDeviceClient_LL_SetDeviceMethodCallback callback is not working

### ISSUE THREAD

**Issue by Pavan2358** [Azure/azure-iot-sdk-c#716]
Hi,
I am trying to use Device Method Callback with appropriate methodCalback function as mentioned in the sample program, but while calling it from the cloud with the method name its not even entering the callback function. I have modified telemetry sample and have attached complete code in it as "DeviceMethod.txt". Please let me know if its a bug from your side as it is a straight forward API which has to work or I have made a mistake. **Note: **I am able to run stand alone device method which uses totally a different type of client** "IOTHUB_DEVICE_CLIENT_HANDLE", but former uses "IOTHUB_DEVICE_CLIENT_LL_HANDLE". Both are having totally different paramters****
[DeviceMethod.txt](https://github.com/Azure/azure-iot-sdk-c/files/2603460/DeviceMethod.txt)

**Comment by Pavan2358** [comment]
Can someone please respond on this issue

**Comment by ewertons** [comment]
Hi @Pavan2358 ,

did you try running the Device Method and Twin sample as is before?

I took a look at your code, I see a few problems with it.
First, you are mixing IoTHubClient_LL_* and IoTHubDeviceClient_LL_* functions (e.g., IoTHubClient_LL_DoWork). That is the first thing you need to fix.
Please use IoTHubDeviceClient_LL_*.

Next, did you notice on line 170 of your code that after the 5 telemetry messages are sent the g_continueRunning is set to false?
That causes the while loop to end. That look calls IoTHubClient_LL_DoWork (which should be IoTHubDeviceClient_LL_DoWork).
If IoTHubDeviceClient_LL_DoWork is not being called, no I/O happens on the IoTHubDevice client.
So it would be expected for you not to have your callback invoked.

Please refactor your sample so it keeps running the _DoWork() function continuously at least every 100 milliseconds.

Another point is tht while(1) you wrote. It seems broken, I don't see the block properly written. Not sure what you intended there. I did not compile your code, but I'm suspicious it would fail because of that.

Last, you should always destroy the instances you create in your program. You should not comment IoTHubDeviceClient_LL_Destroy.

If you prefer, please use [this sample](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_device_twin_and_methods_sample/iothub_client_device_twin_and_methods_sample.c) as a base for your test.

**Comment by Pavan2358** [comment]
Hi @ewertons 

Sorry for the delayed response. Thank you for suggestion. It is working fine now

**Comment by az-iot-builder-01** [comment]
@Pavan2358, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
