### ISSUE TITLE
IoTHubDeviceClient_SetDeviceMethodCallback with NULL callback fails to unsubscribe

### ISSUE THREAD

**Issue by ling0015** [Azure/azure-iot-sdk-c#719]
- **OS and version used:** <VERSION> 
Ubuntu 16.04 and Custom ARM Based Linux

- **SDK version used:** <VERSION> 
lts_10_2018

# Description of the issue:
I was having some issues with a race condition in my application shutdown when a device method callback was in progress. In an attempt to fix this, I added the following to the start of my shutdown function:
```
IoTHubDeviceClient_SetDeviceMethodCallback(iotHubClientHandle, NULL, NULL);
```
In the belief that this would unsubscribe me from callbacks. This seemed to execute successfully on my workstation but failed with the following error on ARM:
```
Error: Time:Tue Nov 20 18:51:10 2018 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransportamqp_methods.c Func:iothubtransportamqp_methods_unsubscribe Line:897 unsubscribe called while not subscribed
```
The root cause seems to be that in IoTHubClientCore_LL_SetDeviceMethodCallback the subscribe function call uses the deviceHandle and the unsubscribe function call uses the transportHandle. 
The reason this seems to work against x86 and not on ARM appears to be in IoTHubTransport_AMQP_Common_Unsubscribe_DeviceMethod, when the value of device_state->subscribe_methods_needed is uninitialized on ARM it was 240 and on x86 it was 0. Since there is no else statement it just quietly fails.

**Comment by YoDaMa** [comment]
Hi @ling0015, to try to understand your issue better I reproduced the error by creating a simple application that called `SetDeviceMethodCallBack` to subscribe then immediately called it again passing in NULL to unsubscribe from Device Methods. This was run on Visual Studio in Windows.

    (void)IoTHubDeviceClient_SetDeviceMethodCallback(device_handle, device_method_callback, NULL);
    (void)IoTHubDeviceClient_SetDeviceMethodCallback(device_handle, NULL, NULL);

I set a breakpoint in `iothubtransportamqp_methods_unsubscribe` and saw that it did fail with the error you are seeing

    Error: Time:Thu Jan  3 17:31:25 2019 File:e:\gitrepos\azure-iot-sdk-c\iothub_client\src\iothubtransportamqp_methods.c Func:_iothubtransportamqp_methods_unsubscribe Line:892 unsubscribe called while not subscribed

This error occurs because with the treading of the convenience layer (non-LL), the unsubscribe is called before the first call to `SetDeviceMethodCallback` is completed.

The information you provided on the error doesn't give us enough to understand exactly what issue you are running into. It could be that you are unsubscribing from the same connection twice, unsubscribing. 

So that we may investigate this further, would you mind turning on **log tracing and adding a log trace of the error**? Once you add the log trace here we can provide a better investigation.

**Comment by ling0015** [comment]
Hi @YoDaMa,
To clarify, I am not currently experiencing an issue with unsubscribing. My original issue was my application was destroying resources that were being used in callbacks, I originally attempted to use unsubscribe to address this issue. In the end I was able to use IoTHubClient_Destroy to wait for callbacks to close before destroying the resources to fix my problem. 

I opened this issue as it seemed like a bug you guys might be interested in. 

I believe you may be correct about the race condition because in the sample program attached the error is exhibited when the sleep on line 60 is small, and is not exhibited when it is large.

Could you explain the reason behind calling subscribe on the device handle and calling unsubscribe on the transporthandle? 

[main.txt](https://github.com/Azure/azure-iot-sdk-c/files/2727378/main.txt)

**Comment by YoDaMa** [comment]
Good to hear you managed the problem! As to your question, let me give it a crack. 

The difference between the two comes down to the fact that in particular with the AMQP protocol you have the option to use multiplexing through the transport to weave the data of multiple so-called 'Devices' through a single communication point. So a device handle will point to a struct that has information related to a 'Device'. A transport handle will point to a struct that has information related to the transport (AMQP).

To your question of why would subscribe use the device handle and unsubscribe use the transport handle, the question must be understood through the context of *where* the calls are being made. 

In `IoTHubClientCore_LL_SetDeviceMethodCallback` both calls for subscribe and unsubscribe are made using the device handle. This makes sense since we are calling into `IoTHubTransport_Subscribe`, which in AMQP takes in a device handle to subscribe that device to method callbacks (it doesn't make sense if you are multiplexing to use a transport handle to subscribe a single device to a method callback). 

In `iothubtransportamqp_methods_subscribe` we are just adjusting the device state to indicate that it needs to subscribe to methods. During the transport's DoWork call, it will check for this device state and if indicated it will update the transport by calling into `_iothubtransportamqp_methods_unsubscribe` which will unsubscribe the device via the transport method handle. 

Hopefully this explanation is helpful! If I didn't explain it well enough or answer your question don't be shy.

**Comment by az-iot-builder-01** [comment]
@YoDaMa, @ling0015, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
