### ISSUE TITLE
2018-11-20 release fails to link

### ISSUE THREAD

**Issue by larsonmpdx** [Azure/azure-iot-sdk-c#732]
with a source-built library installed this way:
````
RUN git clone -b 2018-11-20 --recursive https://github.com/Azure/azure-iot-sdk-c.git \
  && cd azure-iot-sdk-c \
  && mkdir cmake-build \
  && cd cmake-build \
  && cmake .. \
  && make -j4 \
  && make install \
  && ldconfig
````
then building my own project with this cmake configuration:

````
target_link_libraries(myproject
        iothub_client
        iothub_client_mqtt_transport
        aziotsharedutil
        pthread
        curl
        ssl
        crypto
        m
        umqtt
          # shouldn't be needed. see issue https://github.com/Azure/azure-iot-sdk-c/issues/550
	  # prov_auth_client # causes conflicts on source-built sdk, nov 2018
	  # hsm_security_client # causes conflicts on source-built sdk, nov 2018
        uhttp
        uuid
        parson
        )
````
gives this error:
````
//usr/local/lib/libumqtt.a(mqtt_message.c.o): In function `mqttmessage_getTopicLevels':
mqtt_message.c:(.text+0x510): undefined reference to `StringToken_Split'
collect2: error: ld returned 1 exit status
````
stringtoken_split should come from aziotsharedutil but it's not working. things worked with this same build process with the 2018-09-11 release

the recommended linker options are given here:
https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/ubuntu_apt-get_sample_setup.md

see also #621, #550

**Comment by larsonmpdx** [comment]
I tested with the 2018-10-03 release and it works with the above build steps

**Comment by jebrando** [comment]
@larsonmpdx you hit a quirk with the gcc compiler, I'll try to explain (very poorly) below.  Moving the umqtt lib above aziotsharedutil will fix the issue and we shall fix our documentation to make it more clear.  Your target_link_libraries code should look like this:

target_link_libraries(myproject
        iothub_client
        iothub_client_mqtt_transport
        umqtt
        uhttp
        aziotsharedutil
        pthread
        curl
        ssl
        crypto
        m
          # shouldn't be needed. see issue https://github.com/Azure/azure-iot-sdk-c/issues/550
	  # prov_auth_client # causes conflicts on source-built sdk, nov 2018
	  # hsm_security_client # causes conflicts on source-built sdk, nov 2018
        uuid
        parson
        )

The reason this error occurred is that gcc gathers the dependencies as it goes along from top to bottom if a dependency is encountered of a library that has been previously scanned, the code won't be found, generating a undefined reference error.  The StringToken_Split is a new function and this is the first release where it's been used and it's only being used in umqtt.  Since no other library above the aziotsharedutil is using that function when gcc get to that library it discards that function to save space, not knowing that later on umqtt will need this function.

Let me know if you have any more question on this.

**Comment by larsonmpdx** [comment]
thanks, that got me unstuck

**Comment by az-iot-builder-01** [comment]
@larsonmpdx, @jebrando, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by dbuijsma** [comment]
Just a note, this is not a quirk: gcc scans dependencies start to end and this is well documented. In case you have circular dependencies between libraries, you can use the -Wl,--start-group/-Wl,--end-group commands.
