### ISSUE TITLE
[edge module] Build fail

### ISSUE THREAD

**Issue by adashen** [Azure/azure-iot-sdk-c#738]
Please first tell us a little bit about the environment you're running:

- **OS and version used:** <VERSION> 
Build in docker container, the base image is ubuntu:xenial
And the project uses the edge module template https://github.com/Azure/azure-iot-edge-c-module

- **SDK version used:** <VERSION> 
the latest azure-iot-sdk-c

# Description of the issue:
I create the module with the released iot edge c template. The module could be built successfully. However it failed today.  And I checked the the sdk has a new release on 11/27 

# Code sample exhibiting the issue:
https://github.com/Azure/azure-iot-edge-c-module/blob/master/main.c
https://github.com/Azure/azure-iot-edge-c-module/blob/master/CMakeLists.txt

# Console log of the issue:
error log:
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /app
Removing intermediate container 53b204fcafda
 ---> dfe644b9b12d
Step 8/14 : RUN make
 ---> Running in ceb29f4b60dc
Scanning dependencies of target main
[ 50%] Building C object CMakeFiles/main.dir/main.c.o
[100%] Linking C executable main
/usr/lib/gcc/arm-linux-gnueabihf/5/../../../../lib/libumqtt.a(mqtt_message.c.o): In function `mqttmessage_getTopicLevels':
(.text+0x396): undefined reference to `StringToken_Split'
collect2: error: ld returned 1 exit status
CMakeFiles/main.dir/build.make:94: recipe for target 'main' failed
make[2]: *** [main] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/main.dir/all' failed
make[1]: *** [CMakeFiles/main.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
The command '/bin/sh -c make' returned a non-zero code: 2

**Comment by jebrando** [comment]
@adashen you hit a quirk with the gcc compiler, I'll try to explain (very poorly) below. Moving the umqtt lib above aziotsharedutil will fix the issue and we shall fix our documentation to make it more clear. Your target_link_libraries code should look like this:

target_link_libraries(main
    iothub_client_mqtt_transport
    iothub_client
    parson
    umqtt
    prov_auth_client
    hsm_security_client
    uhttp
    aziotsharedutil
    pthread
    curl
    ssl
    crypto
    m
     uuid
)

The reason this error occurred is that gcc gathers the dependencies as it goes along from top to bottom if a dependency is encountered of a library that has been previously scanned, the code won't be found, generating a undefined reference error. The StringToken_Split is a new function and this is the first release where it's been used and it's only being used in umqtt. Since no other library above the aziotsharedutil is using that function when gcc get to that library it discards that function to save space, not knowing that later on umqtt will need this function.

Let me know if you have any more question on this.

**Comment by az-iot-builder-01** [comment]
@adashen, @jebrando, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
