### ISSUE TITLE
Blob Upload > 64 MB

### ISSUE THREAD

**Issue by MichaelDenczek** [Azure/azure-iot-sdk-c#74]
When uploading files larger than 64 MB to blob storage in the Azure Government cloud, chunking fails to include the md5 in the headers for the individual chunks.  This causes overall validation to fail.  Sending files less than 64 MB results in correct functionality and successful validation.

**Comment by MichaelDenczek** [comment]
The solution is to a add a x-ms-blob-content-md5 header containing the Base64 encoded md5 file hash to the final put block list request.

**Comment by anporumb** [comment]
Hello @MichaelDenczek ,

We will look at this in March (this month).

Best Regards,
Andrei Porumb

**Comment by anporumb** [comment]
Hello @MichaelDenczek ,

I am a bit puzzled.

IoTHub does not have a presence in Azure Government cloud. Even if you had a storage account in Azure Government cloud and an IoTHub in a public cloud, it would not be possible to link them because data cannot flow between the 2 clouds.

About the missing header, [MSDN documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/put-block-list) lists it as `optional` for Put Block List. 

Is Azure government cloud requiring this header? I just want to verify that this is exactly the problem you're having and not something else.

Best Regards,
Andrei Porumb

**Comment by MichaelDenczek** [comment]
We are currently using IoTHub outside of the Azure Gov cloud.  

The references MSDN document indicates the x-ms-blob-content-md5 is an optional MD5 hash of the blobb content, not validated as the hashes for the individual blocks are validated.

I found this to be just the opposite, with the only changes made to the Blob_UploadFromSasUri method being the addition of the x-ms-blob-content-md5 header and overall MD5, validation succeeded.  There were no headers added nor MD5 values calculated (by me) for the individual chunks.

**Comment by tameraw** [comment]
@MichaelDenczek - We captured this in our backlog as an enhancement in the SDK.

**Comment by ewertons** [comment]
Hi @MichaelDenczek ,
this item has been lingering for quite a while, sorry for that.

I verified uploading a 100 MB (10^8 bytes) to a regular blob storage and it worked fine with the latest client (Azure IoT SDK 1.1.28).
The log is attached in case you want to check it out.

Would you be able to verify if you still have the issue?
[100000000bytes.txt](https://github.com/Azure/azure-iot-sdk-c/files/1493370/100000000bytes.txt)

**Comment by ewertons** [comment]
Here is the file uploaded on that test:
![image](https://user-images.githubusercontent.com/12401690/33102599-6648149e-ced2-11e7-9f6b-7c44ad87efc0.png)

**Comment by ewertons** [comment]
Hi @MichaelDenczek ,
this issue will be closed for now, but please feel free to reopen it once you have chance to follow up on the verification as per the last post.
Thanks,
Azure IoT Team
