### ISSUE TITLE
Expansion of macro MOCKABLE_FUNCTION fails in pc-lint/flexelint

### ISSUE THREAD

**Issue by AlataMors** [Azure/azure-iot-sdk-c#763]
- **OS and version used:** Debian 9 

- **SDK version used:** 1.2.0 

# Description of the issue:

When the pc-lint preprocessor encounters a `MOCKABLE_FUNCTION` macro it doesn't fully expand all of the child macros. There is usually and instance of `IF1(, void)` or `IF0(, void)` remaining in the middle of the function declaration.

# Code sample exhibiting the issue:

From c-utility/inc/azure_c_shared_utility/singlylinkedlist.h line 41
`MOCKABLE_FUNCTION(, SINGLYLINKEDLIST_HANDLE, singlylinkedlist_create);` will expand to 
`SINGLYLINKEDLIST_HANDLE singlylinkedlist_create(IF0(, void) );;`

# Console log of the issue:

[lint_log.txt](https://github.com/Azure/azure-iot-sdk-c/files/2664370/lint_log.txt)

[test_file.txt](https://github.com/Azure/azure-iot-sdk-c/files/2664373/test_file.txt)

**Comment by jspaith** [comment]
Our `MOCKABLE_FUNCTION` logic is indeed fairly complex for pre-processor and its sounding like pc-lint isn't able to handle it.  We've never hit issues with pre-processors from clang, gcc, Visual Studio, or the other embedded compilers that have been used against us, though I know it's not much help to you.

A bit ago I came up with a proof of concept change where we got rid of these MOCKABLE_FUNCTION's because they were complicated our docs story.  It's still around https://github.com/Azure/azure-iot-sdk-c/tree/mockable - though it's a few months old and is not something we're updating.  You may be able to try running your tools against that, at least for purposes of having pc-lint checking your code and not having IoT SDK get in way.  

We're not going to merge that into master and I should delete the branch at some point (so let's reference the commit id for future, 55c75005a184952cc9637bff26ab602a8ce02926).  We're not taking to master because there's other ways to post-process docs and team was concerned with duplicating header declarations for test/product.

For correct long-term fix, I'd recommend you reach out to pc-lint so they can at least track this issue.  Sorry we don't have a better fix for now for you.

**Comment by jspaith** [comment]
Since this thread has been quiet for a bit, I'm going to close it out.  Wish I had a better answer, but the MOCKABLE_FUNCTION is pretty tightly interwoven into the SDK (both C and many of our submodules) so ultimately it needs preprocessor support.

As always, if there's followups on this or other issues by all means reactivate this issue or create a new one.

**Comment by az-iot-builder-01** [comment]
@AlataMors, @jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
