### ISSUE TITLE
IOT C SDK messages are lost

### ISSUE THREAD

**Issue by ajaskumarpa** [Azure/azure-iot-sdk-c#803]
I am using IoT hub C sdk in my code. Protocol is HTTP. I have registered to IoTHubMessage_CreateFromByteArray for receiving the messages. But when I am trying to communicate to IOT I can see IOT is sent 2 messages to sdk and I received only one in my program. This is not heppening everytime. Sometimes I am observing this. Please help

**Comment by YoDaMa** [comment]
Hey @ajaskumarpa, do you mind including a code snippet of what it is _exactly_ you're doing. Are you sending messages from your device client to IoT Hub and noticing that after sending two, only one arrives? 

Based on your comment you are receiving messages over HTTP and then in the recieve message callback calling **IoTHubMessage_CreateFromByteArray**, which seems incorrect from the face of things, since usually in this situation you'd use **IoTHubMessage_GetByteArray**...

**Comment by ajaskumarpa** [comment]
Hi @YoDaMa


Sorry for the mistake. I have used IoTHubMessage_GetByteArray for receiving the messages. For more clarification I will post my code snippet in few minutes

**Comment by ajaskumarpa** [comment]
My sample code spinet is 

{
int receiveContext = 0;
	unsigned int timeout = 0;//241000;
	bool isBatching = false;
unsigned int minimumPollingTime = 5;
if (IoTHubClient_SetOption(m_IoTHubClientHandle, "timeout", &timeout) != IOTHUB_CLIENT_OK)
	{
		APPLICATION_DEBUG("WfId", "failure to set option ");
	}

	if (IoTHubClient_SetOption(m_IoTHubClientHandle, "Batching", &isBatching) != IOTHUB_CLIENT_OK)
	{
		APPLICATION_DEBUG("WfId", "Rfailure to set batching option ");
	}
	if (IoTHubClient_SetOption(m_IoTHubClientHandle, "MinimumPollingTime", &minimumPollingTime) != IOTHUB_CLIENT_OK)
	{
		APPLICATION_DEBUG("WfId", "failure to set option ");
	}
	APPLICATION_DEBUG("WfId", "SetOptions() SUCCESS ");

if (IoTHubClient_SetMessageCallback(m_IoTHubClientHandle, iotResponseCallBack, &receiveContext) != IOTHUB_CLIENT_OK)
	{
		APPLICATION_DEBUG("WfId", "ERROR: IoTHubClient_LL_SetMessageCallback..........FAILED! ");
	}
	else
	{
		APPLICATION_DEBUG("WfId", "IoTHubClient_LL_SetMessageCallback...successful ");
	}
}

IOTHUBMESSAGE_DISPOSITION_RESULT IOTCommunicationHandler::iotResponseCallBack(IOTHUB_MESSAGE_HANDLE message, void* userContext)
{
const char* cRecvdBuffer = nullptr;
	size_t iRecvdMsgSize;

	try
	{
		if (IoTHubMessage_GetByteArray(message, (const unsigned char**)&cRecvdBuffer, &iRecvdMsgSize) != IOTHUB_MESSAGE_OK)
		{
			throw IPCException("unable to IoTHubMessage_GetByteArray.\n");
		}

		if (iRecvdMsgSize <= 0 )
		{
			throw IPCException("Empty Message Received.");
		}

		std::string iotMsg;
		iotMsg.assign(cRecvdBuffer, (int)iRecvdMsgSize);

		APPLICATION_DEBUG("WfId", "Received message from IoT Hub %s", iotMsg.c_str());
}

**Comment by ajaskumarpa** [comment]
I can see from IOT hub logs that all messages sent. But in my callback funtion only one has received

**Comment by YoDaMa** [comment]
First, based on your code snippet I see you're manually entering in the Option names. It would be better coding practices to use the  `#include "azure_c_shared_utility/shared_util_options.h"` and then instead of for instance **"timeout"** use **OPTION_HTTP_TIMEOUT**. 

From what you're saying, your callback function is only called once? Not one time it is called and the next time it errors out? 

The code you have seems very similar to the iothub_ll_c2d_sample code. I've tried to repro the dropped message with no success. 

Try running the iothub_ll_c2d_sample code exactly and see if the message is dropped. Post the logs of the messages sent on the Service side but not received on the Device side. This'll maybe give us some better data to figure out the mystery dropping of HTTP packets. 

In the case of HTTP, the Device Client will query IoT Hub for any messages periodically. If a message for the device is there then it will retrieve it. The service client sending messages will show that it has sent a message when it uploads a message to IoT Hub, not when a message is delivered to the Device Client. So it could be many things causing a message to drop every once in a while between the service and your device...

**Comment by YoDaMa** [comment]
@ajaskumarpa we haven't heard from you in a few days. For now we'll wait until there is more information on how to investigate this issue.

**Comment by YoDaMa** [comment]
This issue has been inactive for a while so I'm going to go ahead and close it, however @ajaskumarpa feel free to reopen it if the problem is persisting and you have more information.

**Comment by az-iot-builder-01** [comment]
@YoDaMa, @ajaskumarpa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
