### ISSUE TITLE
Cross-compile Fail, azure-iot-sdk-c, Performing Test CXX_FLAG_CXX11 - Failed

### ISSUE THREAD

**Issue by terrychang1015** [Azure/azure-iot-sdk-c#807]
MCU: MT7620 MIPS 
Cross-compile Version: GCC 3.4.2
Cmake Version: 3.2.2

is any info I supposed to provide for the issue?

=====Error Message=====
maplerain@ubuntu:~/mtk/M2M/AMR301-Cellular/source/lib/azure-iot-sdk-c$ ./reconfigure.sh
-- The C compiler identification is GNU 3.4.2
-- The CXX compiler identification is GNU 3.4.2
-- Check for working C compiler: /opt/buildroot-gcc342/bin/mipsel-linux-gcc
-- Check for working C compiler: /opt/buildroot-gcc342/bin/mipsel-linux-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/buildroot-gcc342/bin/mipsel-linux-g++
-- Check for working CXX compiler: /opt/buildroot-gcc342/bin/mipsel-linux-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- IoT Client SDK Version = 1.2.11
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdbool.h
-- Looking for include file stdbool.h - found
-- target architecture: GENERIC
-- Performing Test CXX_FLAG_CXX11
-- Performing Test CXX_FLAG_CXX11 - Failed
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.1f")
-- Cross compiling not using pkg-config
-- Found CURL: /usr/local/lib/libcurl.so (found version "7.47.1")
-- Found CURL: /usr/local/lib/libcurl.so
-- target architecture: GENERIC
-- target architecture: GENERIC
-- target architecture: GENERIC
-- target architecture: GENERIC
-- iothub architecture: GENERIC
-- Configuring done
-- Generating done
-- Build files have been written to: /home/maplerain/mtk/M2M/AMR301-Cellular/source/lib/azure-iot-sdk-c/build

**Comment by maple760104** [comment]
-- reconfigure.sh --
maplerain@atrie-desktop:~/MIPSBuild/azure-iot-sdk-c$ cat ./reconfigure.sh
#!/bin/sh
rm -rf build/
mkdir build
cd build
cmake -D CMAKE_TOOLCHAIN_FILE=../Toolchain-mt7620.cmake ../

-- Toolchain-mips.cmake --
maplerain@atrie-desktop:~/MIPSBuild/azure-iot-sdk-c$ cat Toolchain-mips.cmake
RK_ROOT=/home/builder/MIPSBuild
TOOLCHAIN_ROOT=${WORK_ROOT}/OpenWrt-Toolchain-ramips-for-mipsel_24kec+dsp-gcc-4.8-linaro_uClibc-0.9.33.2
TOOLCHAIN_SYSROOT=${TOOLCHAIN_ROOT}/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2
TOOLCHAIN_EXES=${TOOLCHAIN_SYSROOT}/bin
TOOLCHAIN_NAME=mipsel-openwrt-linux-uclibc
AR=${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-ar
AS=${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-as
CC=${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-gcc
LD=${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-ld
NM=${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-nm
RANLIB=${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-ranlib

LDFLAGS="-L${TOOLCHAIN_SYSROOT}/usr/lib"
LIBS="-lssl -lcrypto -ldl -lpthread"
TOOLCHAIN_PREFIX=${TOOLCHAIN_SYSROOT}/usr
STAGING_DIR=${TOOLCHAIN_SYSROOT}

**error message**
=============================================
-- Found CURL: /lib/libcurl.so (found version "7.35.0")
-- Found CURL: /lib/libcurl.so
-- target architecture: GENERIC
-- target architecture: GENERIC
-- target architecture: GENERIC
-- target architecture: GENERIC
-- iothub architecture: GENERIC
-- Configuring done
CMake Warning at iothub_service_client/samples/iothub_deviceconfiguration_sample/CMakeLists.txt:20 (add_executable):
  Cannot generate a safe runtime search path for target
  iothub_deviceconfiguration_sample because files in some directories may
  conflict with libraries in implicit directories:

    runtime library [libcurl.so.4] in /lib may be hidden by files in:
      /usr/lib/x86_64-linux-gnu

  Some of these libraries may not be found correctly.
...

-- Generating done
-- Build files have been written to: /home/maplerain/MIPSBuild/azure-iot-sdk-c/build
===================================================

1. Can i changed libcurl.so file path to mips version libcurl.so? 
2. when i enter the build folder to make. it's below 
**===================================================**
maplerain@atrie-desktop:~/MIPSBuild/azure-iot-sdk-c/build$ make
Scanning dependencies of target parson
[  0%] Building C object CMakeFiles/parson.dir/deps/parson/parson.c.o
Linking C static library libparson.a
[  0%] Built target parson
Scanning dependencies of target aziotsharedutil
[  0%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/base32.c.o
cc1: error: unrecognized command line option "**-Wno-missing-field-initializers**"
**===================================================**

**Comment by maple760104** [comment]
> Hi @terrychang1015 ,
> the log you posted shows CMAKE completing with no issues.
> 
> Could you post the build logs with the failures you are seeing?
-- reconfigure.sh --
maplerain@atrie-desktop:~/MIPSBuild/azure-iot-sdk-c$ cat ./reconfigure.sh
#!/bin/sh
rm -rf build/
mkdir build
cd build
cmake -D CMAKE_TOOLCHAIN_FILE=../Toolchain-mt7620.cmake ../

-- Toolchain-mips.cmake --
maplerain@atrie-desktop:~/MIPSBuild/azure-iot-sdk-c$ cat Toolchain-mips.cmake
RK_ROOT=/home/builder/MIPSBuild
TOOLCHAIN_ROOT=${WORK_ROOT}/OpenWrt-Toolchain-ramips-for-mipsel_24kec+dsp-gcc-4.8-linaro_uClibc-0.9.33.2
TOOLCHAIN_SYSROOT=${TOOLCHAIN_ROOT}/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2
TOOLCHAIN_EXES=${TOOLCHAIN_SYSROOT}/bin
TOOLCHAIN_NAME=mipsel-openwrt-linux-uclibc
AR=${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-ar
AS=${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-as
CC=${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-gcc
LD=${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-ld
NM=${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-nm
RANLIB=${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-ranlib

LDFLAGS="-L${TOOLCHAIN_SYSROOT}/usr/lib"
LIBS="-lssl -lcrypto -ldl -lpthread"
TOOLCHAIN_PREFIX=${TOOLCHAIN_SYSROOT}/usr
STAGING_DIR=${TOOLCHAIN_SYSROOT}

**error message**
=============================================
-- Found CURL: /lib/libcurl.so (found version "7.35.0")
-- Found CURL: /lib/libcurl.so
-- target architecture: GENERIC
-- target architecture: GENERIC
-- target architecture: GENERIC
-- target architecture: GENERIC
-- iothub architecture: GENERIC
-- Configuring done
CMake Warning at iothub_service_client/samples/iothub_deviceconfiguration_sample/CMakeLists.txt:20 (add_executable):
  Cannot generate a safe runtime search path for target
  iothub_deviceconfiguration_sample because files in some directories may
  conflict with libraries in implicit directories:

    runtime library [libcurl.so.4] in /lib may be hidden by files in:
      /usr/lib/x86_64-linux-gnu

  Some of these libraries may not be found correctly.
...

-- Generating done
-- Build files have been written to: /home/maplerain/MIPSBuild/azure-iot-sdk-c/build
===================================================

1. Can i changed libcurl.so file path to mips version libcurl.so? 
2. when i enter the build folder to make. it's below 
**===================================================**
maplerain@atrie-desktop:~/MIPSBuild/azure-iot-sdk-c/build$ make
Scanning dependencies of target parson
[  0%] Building C object CMakeFiles/parson.dir/deps/parson/parson.c.o
Linking C static library libparson.a
[  0%] Built target parson
Scanning dependencies of target aziotsharedutil
[  0%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/base32.c.o
cc1: error: unrecognized command line option "**-Wno-missing-field-initializers**"
**===================================================**

**Comment by ewertons** [comment]
Hi @maple760104 ,
is this related to the issue @terrychang1015  has reported? the CMAKE output you posted is different than the one reported on the top.

The failure you showed indicates there is a conflict that needs to be fixed for the cross-compilation to succeed.
@markrad , have you seen something similar before?

**Comment by terrychang1015** [comment]
@maple760104 , the log you posted is the one you show to me?

**Comment by maple760104** [comment]
> @maple760104 , the log you posted is the one you show to me?

Yes, but some information on the picture and not post it.

**Comment by ewertons** [comment]
Hi @terrychang1015 ,
were you able to resolve the issues you were facing?
Please let us know so we can close this issue.
Thanks.

**Comment by mxxmusic** [comment]
have fixed?

**Comment by jspaith** [comment]
This has been inactive for a quite bit and it's not clear we have enough information to debug.  Please reactivate or open a new issue with additional logs of what's gone wrong if further support is needed.  Thanks

**Comment by az-iot-builder-01** [comment]
@ewertons, @maple760104, @terrychang1015, @mxxmusic, @jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
