### ISSUE TITLE
Any plan to implement mbedTLS?

### ISSUE THREAD

**Issue by mmdsantos** [Azure/azure-iot-sdk-c#81]
Hello,

I'm having some problems with the OpenSSL library required to run the Azure IoT C SDK, and I think the main issue is with OpenSSL. My device has an older version and I can't change it.
When I tried a different IoTplatform, it had support to mbedTLS instead of OpenSSL, and I had no problems  in compiling and running in my device. Is there any plans to include support for mbedTLS?

Thank you

**Comment by dcristoloveanu** [comment]
Hi @mmdsantos,

We have an adapter for mbedtls at https://github.com/Azure/azure-c-shared-utility/blob/8784f5fd21ad6488eabb8a0f41f34130c85ac8ec/adapters/tlsio_mbedtls.c 

Unfortunately this is not currently built as part of our gated system.
Some work needs to be done on it to make sure it builds on every build that we do and additionally tests need to be written for it.

Otherwise it has been used in a customer project, so it is a good starting point.

At the moment we are focused on clearing the issues around reconnect and reliability, so bringing the MBED adapter up to par is not a short term priority.

But contributions welcome if you would like to take such a project!

Thanks,
/Dan
