### ISSUE TITLE
Failed to build IoT Edge c sample project suddenly

### ISSUE THREAD

**Issue by blackchoey** [Azure/azure-iot-sdk-c#966]
Repo of IoT Edge c sample: [https://github.com/Azure-Samples/iot-edge-sample-c](https://github.com/Azure-Samples/iot-edge-sample-c)
We can build the sample project successfully (docker build Dockerfile.amd64) before but recently we found the build will fail with lots of `unknown type name` error. Could you help take a look?
Here's part of the error message:
```
[ 50%] Building C object CMakeFiles/main.dir/main.c.o

In file included from /usr/include/azureiot/iothub_client_core_common.h:13:0,
                 from /usr/include/azureiot/iothub_module_client_ll.h:31,
                 from /app/main.c:7:
/usr/include/azureiot/iothub_message.h:33:1: warning: data definition has no type or storage class
 DEFINE_ENUM(IOTHUB_MESSAGE_RESULT, IOTHUB_MESSAGE_RESULT_VALUES);
 ^
/usr/include/azureiot/iothub_message.h:33:1: warning: type defaults to 'int' in declaration of 'DEFINE_ENUM' [-Wimplicit-int]
/usr/include/azureiot/iothub_message.h:33:1: warning: parameter names (without types) in function declaration
/usr/include/azureiot/iothub_message.h:43:1: warning: data definition has no type or storage class
 DEFINE_ENUM(IOTHUBMESSAGE_CONTENT_TYPE, IOTHUBMESSAGE_CONTENT_TYPE_VALUES);
 ^
/usr/include/azureiot/iothub_message.h:43:1: warning: type defaults to 'int' in declaration of 'DEFINE_ENUM' [-Wimplicit-int]
/usr/include/azureiot/iothub_message.h:43:1: warning: parameter names (without types) in function declaration

In file included from /usr/include/azureiot/iothub_message.h:14:0,
                 from /usr/include/azureiot/iothub_client_core_common.h:13,
                 from /usr/include/azureiot/iothub_module_client_ll.h:31,
                 from /app/main.c:7:
/usr/include/azureiot/iothub_message.h:106:21: error: unknown type name 'IOTHUB_MESSAGE_RESULT'
 MOCKABLE_FUNCTION(, IOTHUB_MESSAGE_RESULT, IoTHubMessage_GetByteArray, IOTHUB_MESSAGE_HANDLE, iotHubMessageHandle, const unsigned char**, buffer, size_t*, size);
                     ^
/usr/include/azureiot/inc/azure_c_shared_utility/umock_c_prod.h:31:5: note: in definition of macro 'MOCKABLE_FUNCTION'
     result modifiers function(MU_IF(MU_COUNT_ARG(__VA_ARGS__),,void) MU_FOR_EACH_2_COUNTED(UMOCK_C_PROD_ARG_IN_SIGNATURE, __VA_ARGS__));
     ^

/usr/include/azureiot/iothub_message.h:130:21: error: unknown type name 'IOTHUBMESSAGE_CONTENT_TYPE'
 MOCKABLE_FUNCTION(, IOTHUBMESSAGE_CONTENT_TYPE, IoTHubMessage_GetContentType, IOTHUB_MESSAGE_HANDLE, iotHubMessageHandle);
```

**Comment by massand** [comment]
@blackchoey - We are taking a look today. Thanks for reporting.

**Comment by massand** [comment]
@blackchoey - I confirmed with @jebrando that we were midway through publishing our apt-gets currently - please retry in a few more hours. We will work on improving the process so that we can publish packages in 'draft' mode (so Edge tooling doesn't fetch dependencies that don't jive with SDK packages - we had a lot of refactors past month). This way, the dependencies and SDK package can be 'published' at once. If there are any ideas on achieving this, please let us know! 

Here is the page tracking our package publishing progress BTW - https://launchpad.net/~aziotsdklinux/+archive/ubuntu/ppa-azureiot/+builds?build_text=&build_state=all

**Comment by massand** [comment]
@blackchoey - all apt-get packages are now published. I tried building Edge modules and the docker build worked now. We will work to reduce the lag between package publish and I have updated our internal publishing process SOP to prevent this lag as much as possible. Thanks again!

**Comment by az-iot-builder-01** [comment]
@blackchoey, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by vbhardwaj1** [comment]
Still getting errors as below while building azure iot solution. Can you verify if attached docker file still makes sense after latest package update from your side, since I am able to cmake and  make in the directory itself.

[Dockerfile.zip](https://github.com/Azure/azure-iot-sdk-c/files/3110923/Dockerfile.zip)




/usr/include/azureiot/inc/azure_c_shared_utility/umock_c_prod.h:31:5: note: in definition of macro 'MOCKABLE_FUNCTION'
     result modifiers function(MU_IF(MU_COUNT_ARG(__VA_ARGS__),,void) MU_FOR_EACH_2_COUNTED(UMOCK_C_PROD_ARG_IN_SIGNATURE, __VA_ARGS__));
     ^
In file included from /usr/include/azureiot/inc/azure_c_shared_utility/xio.h:7:0,
                 from /usr/include/azureiot/inc/azure_c_shared_utility/platform.h:8,
                 from /app/main.c:12:
/usr/include/azureiot/inc/azure_c_shared_utility/optionhandler.h:39:94: error: expected declaration specifiers before ';' token
MOCKABLE_FUNCTION(, OPTIONHANDLER_HANDLE, OptionHandler_Clone, OPTIONHANDLER_HANDLE, handler);
                                                                                              ^
In file included from /usr/include/azureiot/inc/azure_c_shared_utility/optionhandler.h:20:0,
                 from /usr/include/azureiot/inc/azure_c_shared_utility/xio.h:7,
                 from /usr/include/azureiot/inc/azure_c_shared_utility/platform.h:8,
                 from /app/main.c:12:
/usr/include/azureiot/inc/azure_c_shared_utility/optionhandler.h:40:21: error: expected declaration specifiers before 'OPTIONHANDLER_RESULT'
MOCKABLE_FUNCTION(, OPTIONHANDLER_RESULT, OptionHandler_AddOption, OPTIONHANDLER_HANDLE, handle, const char*, name, const void*, value);

/usr/include/azureiot/iothub_client_core_common.h:234:7: error: declaration for parameter 'IOTHUB_CLIENT_DEVICE_CONFIG' but no such parameter
     } IOTHUB_CLIENT_DEVICE_CONFIG;
       ^
/usr/include/azureiot/iothub_client_core_common.h:210:7: error: declaration for parameter 'IOTHUB_CLIENT_CONFIG' but no such parameter
     } IOTHUB_CLIENT_CONFIG;
       ^
/usr/include/azureiot/iothub_client_core_common.h:158:18: error: declaration for parameter 'IOTHUB_CLIENT_INBOUND_DEVICE_METHOD_CALLBACK' but no such parameter
     typedef int(*IOTHUB_CLIENT_INBOUND_DEVICE_METHOD_CALLBACK)(const char* method_name, const unsigned char* payload, size_t size, METHOD_HANDLE method_id, void* userContextCallback);
                  ^
/usr/include/azureiot/iothub_client_core_common.h:157:18: error: declaration for parameter 'IOTHUB_CLIENT_DEVICE_METHOD_CALLBACK_ASYNC' but no such parameter
     typedef int(*IOTHUB_CLIENT_DEVICE_METHOD_CALLBACK_ASYNC)(const char* method_name, const unsigned char* payload, size_t size, unsigned char** response, size_t* response_size, void* userContextCallback);
                  ^
/usr/include/azureiot/iothub_client_core_common.h:156:19: error: declaration for parameter 'IOTHUB_CLIENT_REPORTED_STATE_CALLBACK' but no such parameter
     typedef void(*IOTHUB_CLIENT_REPORTED_STATE_CALLBACK)(int status_code, void* userContextCallback);
                   ^
/usr/include/azureiot/iothub_client_core_common.h:57:47: error: parameter 'IOTHUBTRANSPORT_CONFIG' has incomplete type
     typedef struct IOTHUBTRANSPORT_CONFIG_TAG IOTHUBTRANSPORT_CONFIG;
                                               ^
/usr/include/azureiot/iothub_client_core_common.h:57:47: error: declaration for parameter 'IOTHUBTRANSPORT_CONFIG' but no such parameter
/app/main.c:185:1: error: expected '{' at end of input
 }
