### ISSUE TITLE
Build IoT Edge c sample project failed 

### ISSUE THREAD

**Issue by blackchoey** [Azure/azure-iot-sdk-c#976]
Repo of IoT Edge c sample: [ https://github.com/Azure-Samples/iot-edge-sample-c]( https://github.com/Azure-Samples/iot-edge-sample-c)
By following the suggestion of #968 , we added `--no-cache` option when building docker image for the module but still get same error. Could you help investigate?
```
Step 8/14 : RUN make
 ---> Running in e5c85f97e1af
Scanning dependencies of target main
[ 50%] Building C object CMakeFiles/main.dir/main.c.o
/app/main.c: In function 'SetupCallbacksForModule':
/app/main.c:151:15: error: '__FAILURE__' undeclared (first use in this function)
         ret = __FAILURE__;
               ^
/app/main.c:151:15: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [CMakeFiles/main.dir/main.c.o] Error 1
CMakeFiles/main.dir/build.make:62: recipe for target 'CMakeFiles/main.dir/main.c.o' failed
make[1]: *** [CMakeFiles/main.dir/all] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/main.dir/all' failed
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
The command '/bin/sh -c make' returned a non-zero code: 2
```

**Comment by YoDaMa** [comment]
We've recently renamed all failures from `__FAILURE__` to `MU_FAILURE`, since `__FAILURE__` can easily overlap with other applications that might define a C Macro for a failure event. Also this complies better with C macro naming standards. 

To fix this you'll need to edit the main.c file from the cloned repo and replace the instance of `__FAILURE__` with `MU_FAILURE`

I'll submit a PR with the repo to fix that syntax there too.

**Comment by az-iot-builder-01** [comment]
@blackchoey, @YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
